elastic/ecs

- .travis.yml
- Makefile
- README.md
- scripts/requirements.txt
- scripts/use-cases.py
These checks ensures that all generated files are always up-to-date and follow formatting rules.
Further changes:
* Add dependencies in travis file
* Reorganize check to first run fmt and then check for the diff
* Fix reading directories to be sorted as otherwise not same order on all OS.
* Remove old commands used for python 3.
* Update `make setup` command
> Add travis file to run checks

- CHANGELOG.md
- README.md
- schema.csv
- schemas/cloud.yml
- template.json
The cloud.account.id can be a common field. All cloud providers have a
high level account id, org id, or subscription id that can be used in
this field. Anything more specific such as GCP's project id should go in
an extended schema for the specific cloud provider. Its important to put
GCP's project id in to a separate extended schema, because it does not
overlap conceptually with other cloud providers' structure.
For example. In GCP, you'll have an `organization id`. Under that
`organization id`, you can have multiple projects. This diverges quite
substantially from the flat AWS structure which is just a bunch of
linked accounts. For AWS, there is no subtree like GCP has for projects
or folders.
Azure has a top level organization as well. Under that there are …
> Adds cloud.account.id

- CHANGELOG.md
- README.md
- schema.csv
- schemas/http.yml
- template.json
HTTP response status code and body show up in different Beats as packetbeat, heartbeat, filebeat, apm-server and also in web server logs. They are so common that it makes sense to standardise on the naming which is not the case yet.
I initially thought of creating `response` object outside as it also exists for other protocols but came to the conclusion that it's not really useful to correlate for example response codes across different protocols.
> Add http.response.* fields

- CHANGELOG.md
- README.md
- schema.csv
- schemas/os.yml
- template.json
There were some previous discussions around the version field and if it should split up into major, minor, bugfix, patch. I chose to only go with `version` based on the assumption that if someone searches for a specific minor version he will know the major version. So searching for it can be done with a prefix query based on version keyword.
> Add fields for Operating System data

- .gitattributes
As the CHANELOG is updated in each PR this often leads to merge conflicts. As the CHANGELOG normally can be merged with a union merge this should reduce conflicts.
> Add union merge for CHANGELOG to reduce merge conflicts

- CHANGELOG.md
- README.md
- schema.csv
- schemas/log.yml
- template.json
The field `log.message` contains the full log message before splitting it up in multiple parts.
In contrast to the `message` field which can contain an extracted part of the log message, this field contains the original, full log message. It can have already some modifications applied like encoding or new lines removed to clean up the log message.
This field is not indexed and doc_values are disabled so it can't be
queried but the value can be retrieved from `_source`.
> Add log.message

- README.md
- schema.csv
- schemas/tls.yml
- template.json
While working on the TCP inputs for beats I am able to extract information about the TLS envelope,
this might be useful information for post-mortems or audit. Also, this was a feature requested on
the beats input on the Logstash side.
We are also extracting some information in [packetbeat](https://github.com/elastic/beats/blob/master/packetbeat/protos/tls/_meta/fields.yml) from the work of @adriansr.
Concerning the TCP or the beats input, I think we can extract the following field and provide some
useful information.
- TLS version
- Remote Certificates (mutual auth)
- ServerName
- Cipher used.
Where OR should this information be in the ECS schema? Maybe we could add a `transport` top level
key and have something like this.
| Field  | Description  | Type  | Example  |
|---|---|---|---| …
> Proposal: TLS related fields

- CONTRIBUTING.md
Summary:
- Edited text
- Chunked instructions into steps and sub-steps
- Added "Guidelines" section for naming fields, writing fields, etc.  (Pulled from README.md)
> Editing first pass for CONTRIBUTING.md

- CHANGELOG.md
- README.md
- schema.csv
- schemas/network.yml
- template.json
Added network.total.bytes and network.total.packets as response to PR #2
This came from the split-up of #43
> Added Network Total Metrics - From Split of #43

- README.md
- docs/use-cases-header.md
- scripts/helper.py
- scripts/use-cases.py
- use-cases/apm.md
- use-cases/apm.yml
- use-cases/auditbeat.md
- use-cases/beats.md
- use-cases/filebeat-apache-access.md
- use-cases/logging.md
- use-cases/metricbeat.md
* Add better description on how use cases are used
* Complete use cases table with ECS type, example, description if none is provided
* Adjust apm use case to use `@timestamp`
* Clean up generation script to not link `prefix.*` entries
* Refactor fields cleanup part
> More use cases cleanup

- Makefile
- use-cases/README.md
- use-cases/auditbeat.md
- use-cases/auditbeat.yml
There are a few new hash algorithms under the `hash` namespace used by Auditbeat.
- blake2b_256
- blake2b_384
- blake2b_512
- xxh64
> Add blake2b and xxhash to Auditbeat use-case fields

- CHANGELOG.md
- README.md
- schema.csv
- schemas/os.yml
- template.json
host.os.kernel contains the raw kernel version.
Example values:
- linux: `4.4.0-112-generic`
- windows: `6.3.9600.19000 (winblue_ltsb.180410-0600)` (taken from the FileVersion value on ntoskrnl.exe)
- darwin: `16.7.0`
Closes #60
> Add host.os.kernel field

- README.md
- docs/implementing.md
Explaining the multi-fields convention will help keep each field description more to the point. Right now there's an inconsistent quick explainer in many of the multi-fields, which is redundant. Having this section to explain it a bit better will let us clean these field descriptions up later.
I also like that we're already using `keyword` for most IDs (I haven't checked
them all out). But it's something I would have pushed for if that hadn't
been the case already.
> Create a section to explain some conventions used in ECS. Explain 2 conventions.

- CHANGELOG.md
- README.md
- schema.csv
- schemas/network.yml
- template.json
> Add network.name to track network names with human language :-)

- CHANGELOG.md
- README.md
- schema.csv
- schemas/log.yml
- template.json
log.message was confused with message. To bring it in line with https://github.com/elastic/ecs/issues/102 the field log.message was renamed to log.original.
> Rename log.message to log.original

- CHANGELOG.md
- README.md
- schema.csv
- schemas/event.yml
- schemas/user_agent.yml
- template.json
- use-cases/filebeat-apache-access.md
- use-cases/filebeat-apache-access.yml
* Rename `user_agent.raw` to `user_agent.original` and make it a keyword. I think this always should have been a keyword.
* Rename `event.raw` to `event.original`.
Closes https://github.com/elastic/ecs/issues/102
> Rename .raw to .original fields

- Makefile
- README.md
- fields.yml
- schemas/agent.yml
- schemas/base.yml
- schemas/cloud.yml
- schemas/container.yml
- schemas/destination.yml
- schemas/device.yml
- schemas/error.yml
- schemas/event.yml
- schemas/file.yml
- schemas/geo.yml
- schemas/host.yml
- schemas/http.yml
- schemas/kubernetes.yml
- schemas/log.yml
- schemas/network.yml
- schemas/organization.yml
- schemas/os.yml
- schemas/process.yml
- schemas/service.yml
- schemas/source.yml
- schemas/tls.yml
- schemas/url.yml
- schemas/user.yml
- schemas/user_agent.yml
- scripts/fields_header.yml
Add `type: group` to each prefix.
> Add Beats compatible fields.yml for ECS

- README.md
- fields.yml
- schema.csv
- schemas/base.yml
The `fields` entry example consists of a dictionary surrounded by quotes. This causes problems when the example is used for documentation in asciidoc format, as it is interpreted as an escaped attribute, and the docs generation fails because it cannot find a "key1" attribute.
Fixed by removing the quotes around the example, which isn't perfect because it looks a bit ugly in the generated README.md and CSV formats.
Suggestions welcome.
> Fix example when processed as asciidoc

- CHANGELOG.md
- README.md
- fields.yml
- schemas/file.yml
- schemas/network.yml
- schemas/url.yml
- template.json
> Rename all nested fields mentioned in #103 to .keyword

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/log.yml
- template.json
- use-cases/logging.md
These fields were too specific and does not fit ECS well. It is still fields tthat are used by filebeat and other logging tools but this does not mean they have to be in ECS.
> Remove log.offset and log.line from ECS

- README.md
- fields.yml
- schema.csv
- schemas/agent.yml
- schemas/base.yml
- schemas/cloud.yml
- schemas/container.yml
- schemas/destination.yml
- schemas/device.yml
- schemas/error.yml
- schemas/event.yml
- schemas/file.yml
- schemas/geo.yml
- schemas/host.yml
- schemas/http.yml
- schemas/log.yml
- schemas/network.yml
- schemas/organization.yml
- schemas/os.yml
- schemas/process.yml
- schemas/service.yml
- schemas/source.yml
- schemas/url.yml
- schemas/user.yml
- schemas/user_agent.yml
Subtasks:
This issue is only meant to cover assigning a level to the fields for #93. No modifications to the scripts in this PR.
> WIP add level (Core, Extended) on all fields.

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/device.yml
- schemas/file.yml
- schemas/http.yml
- schemas/network.yml
- schemas/organization.yml
- schemas/url.yml
- schemas/user_agent.yml
- template.json
- use-cases/auditbeat.md
- use-cases/filebeat-apache-access.md
We started to use multi fields in ECS and if we used a multi field, the base field was text as is the default in Elasticsearch. The problem with this is we decide in the future to make a field multi field, it would be breaking change as what was before a keyword now becomes text. To prevent this all fields except `message` are by default a keyword. Making a multifield out of a field is then a non breaking change.
On the ECS side we still need to figure out what our recommendation is for naming multiple fields like `.analyzed, .text` or others.
This change has also an affect on Beats as in ttps://github.com/elastic/beats/pull/8313 the fields.yml from ECS was added to Beats. There was even a breaking change I think we missed when switch to ECS there as the `http.response.body` in packetbeat …
> Switch most fields to keyword as the type

- scripts/requirements.txt
- scripts/schemas.py
A new release of autopep8 causes a small diff in all PRs. This should fix it by setting a predefined autopep8 version.
> Fix autopep8 version

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/url.yml
- template.json
Also in there:
- Replace example.com to continue using the elastic.co example we're breaking down everywhere in this TLO's documentation.
- Removed discussion about correlation via copying to `host.name`, as the correlation will instead happen via `related.*` soon, instead.
- Added changelog
> Rename `url.host.name` to `url.hostname`.

- CHANGELOG.md
- README.md
- docs/implementing.md
The nested field name is open for discussion. I started with the name `*.text`
because I think it will be intuitive even for less technical users. If they want
to search the text, they need to targed `fieldname.text`. To me it sounds
less technical than `*.analyzed` or `*.fts`.
I'm however open to discussing this point before merging.
> Introduce the new convention for multi-fields text indexing to the README.

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/host.yml
- template.json
- use-cases/kubernetes.md
- use-cases/kubernetes.yml
- use-cases/metricbeat.md
- use-cases/metricbeat.yml
This is to align with the industry's convention of using the word "hostname".
> Rename `host.name` to `host.hostname`.

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/agent.yml
- template.json
This is also inspired by the discussion in https://github.com/elastic/ecs/issues/142
> Add agent.type field and redefine agent.name

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/url.yml
- template.json
Recently we changed several fields which contain the initial original value to .original. `href` now follows the same example.
There is an issue with original in the description as it is text by default and we have .raw. What is our recommended approach here?
> Rename url.href to url.original

- README.md
- fields.yml
- schema.csv
- schemas/network.yml
- template.json
This is to help delineate between `network.protocol` like `tcp` and an
`network.application.protocol` such as `http`.
> Revises network.* to cover more use cases

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/network.yml
- Make the capitalization of `IPv` consistent
- Missing changelog
- Tweak the wording of the examples
This is a quick follow-up to #81
> Follow-up to #81 on network layers

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/implementing.md
- fields.yml
- schema.csv
- schemas/ecs.yml
- schemas/event.yml
- template.json
- This opens up the possibility for data sources to use event.version for the version of their event source.
- This opens up the possibility of tracking more ECS-specific meta-data in the ECS field set in the future
cc @MikePaquette
cc @ruflin (as discussed)
> Rename `event.version` to `ecs.version`.

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/destination.yml
- schemas/source.yml
- schemas/url.yml
- template.json
`domain` is now the place to store the host address under `source`, `destination` and `url`.
Also in this PR:
- Remove ambiguous mention in `url` description talking about reuse. Since we
haven't officially made `url` reuseable yet, I took it out for now. People
are free to reuse everything everywhere, as it's just them defining new fields
around the official ECS fields. But the spec making this statement about it
in a different manner than the official reuseable objects is needlessly confusing.
- Tweak the url example a bit.
- Bring `source` description in line with `destination`'s
Closes #166, and addresses part of #84.
> Remove src/dst.hostname, rename url.hostname to url.domain.

- README.md
- docs/about.md
- scripts/use-cases.py
- use-cases/apm.md
- use-cases/auditbeat.md
- use-cases/beats.md
- use-cases/filebeat-apache-access.md
- use-cases/kubernetes.md
- use-cases/logging.md
- use-cases/metricbeat.md
- use-cases/tls.md
- use-cases/web-logs.md
This is important for Beta1, as people visiting elastic/ecs will soon be directed
to past versions (e.g. `v1.0.0-beta1`), if they're looking for official ECS
releases.
This fix ensures that navigating the links from the Readme to the use cases and
the links from use cases back to the readme keeps the person in the same branch
or tag. Prior to this, they would get sent back to the latest version of ECS.
In this PR:
- Make links to use cases relative
- Make links to field defs (from use cases) relative
- Fix last two instances of documentation links pointing to a specific version.
They now link to the "current" stack version.
This addresses one element of #167.
> Make Markdown links relative, so browsing a git ref stays in the same git ref

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/process.yml
- template.json
Note that nesting the ID under `thread.` leaves the door open to eventually
tracking interesting things about threads. Name, priority.
> Add field process.thread.id

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/user.yml
- template.json
> Add user.groups

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/group.yml
- template.json
We may want more fields under `group.` eventually, but I figured we could start with the two most obvious fields.
Note that we're already starting to use them in the Beats transition to ECS. E.g. https://github.com/elastic/beats/pull/9138
> Add minimal field set to represent groups.

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/url.yml
- template.json
`url.original` is meant to record the unmodified URL, as it was observed.
It's typically only a path in access logs, whereas it may be a full URL in
network monitoring or APM use cases.
This PR introduces a field that should always be populated with a full URL,
whether it's populated at the source or reconstructed after the fact.
> Introduce url.full

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/process.yml
- template.json
Note that in this PR, I also take the opportunity to move the more important
fields to the top. You may want to review one commit at a time.
> Introduce process.executable.

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/process.yml
- template.json
> Add `process.working_directory` and `process.start`.

- CHANGELOG.md
- README.md
- fields.yml
- schemas/file.yml
Updated file definition at the start of the file section
> Update file definition

- CHANGELOG.md
- README.md
- fields.yml
- schemas/event.yml
Improve the definition of the event fields at the start of the event section.  Also mention that metrics details are to be included in the event fields.
> Clarify event definition - add metrics

- CHANGELOG.md
- README.md
- fields.yml
- schemas/network.yml
Added detail about network fields, specifically that these fields can be populated for both network and host-based events.
> Clarify network definition

- CHANGELOG.md
- README.md
- fields.yml
- schemas/host.yml
Updated the definition of host at the start of the host section.
> Clarify host definition

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/http.yml
- template.json
- use-cases/filebeat-apache-access.md
- use-cases/web-logs.md
The goal of this PR is strictly to re-introduce the \`http\` field set as it was, not to work on enhancements to the field set. Those enhancements belong into separate PRs.
We've decided to leave http at the top level for the inaugural release of ECS.  We are still considering nesting all protocol breakdowns eventually, but this will come at a later date.
This reverts #171
> Re-introduce `http` precisely as it was, as of #d8cece6

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/user.yml
- template.json
To be populated when a full name is available.
> Add user.full_name

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/network.yml
- template.json
I'm introducing this with a dot before the ID, rather than an underscore. The
standard is defined such as there can be new versions in the future, and when
that happens, we may want to introduce additional fields under `community.`,
to help make sense of this.
Let me know if that sounds reasonable.
[Community ID spec](https://github.com/corelight/community-id-spec)
> Introduce network.community_id

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/destination.yml
- schemas/network.yml
- schemas/source.yml
- template.json
Prior to this PR, the network metrics are defined like this:
- `network.inbound.bytes`
- `network.inbound.packets`
- `network.outbound.bytes`
- `network.outbound.packets`
- `network.total.bytes`
- `network.total.packets`
Discussions around ambiguity of inbound/outbound naming have come up multiple times,
more or less directly in #2, #51, #63, and at various other times internally.
The issues with inbound/outbound metrics:
- Inbound/outbound can mean relative to the host, or to the organization's network.
- From a host POV, mapping of source => destination to either "inbound" or "outbound"
has to change, depending on whether the host is receiving the connection inbound,
or initiating a connection outbound.
- From the POV of a network device, inbound/outbound to the organization's network …
> Proposal for more straightforward network metrics fields.

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/client.yml
- schemas/geo.yml
- schemas/related.yml
- schemas/server.yml
- schemas/user.yml
- template.json
This PR closes https://github.com/elastic/ecs/issues/63 by adding the `client.*` and `server.*` top level objects to contain fields used in connection/session level events.
Many thanks to those who expended time, energy, and passion in issue #63 along the way!
> Add Top Level Client and Server Objects

- README.md
- fields.yml
- schemas/destination.yml
- schemas/source.yml
Just like client and server (#236).
I actually think the phrasing for these pairs should be more forceful. I would replace "usually populated in conjunction" with "must be populated in conjunction".
We'll already have to manage two pairs of endpoint names instead of one. A lot of content will be affected by this. The last thing I would want is to actually have to deal with even more of them: source-server, client-destination, server-destination ;-)
> State that source and destination are also a pair.

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/geo.yml
- template.json
This is useful for representing location manually, in some situations.
This idea originated in https://github.com/elastic/beats/pull/9392
> Add `geo.name` as the field for ad hoc location names.

- README.md
- fields.yml
- schema.csv
- schemas/url.yml
Currently examples do not allow multiple lines. This is a quick fix, we must find something nicer in the future.
> Fix url.original example

- README.md
- fields.yml
- schemas/destination.yml
- schemas/source.yml
Not sure how this one went through, on Travis' `make check`.
> Fix a typo in the word conjunction.

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/user_agent.yml
- template.json
- use-cases/filebeat-apache-access.md
- use-cases/web-logs.md
After discussions on PR #240, me and @ruflin synced up and agreed that indexing the `user_agent.original` would actually be useful (as opposed to `event.original` and `log.original`).
> Index `user_agent.original`, after all.

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/client.yml
- schemas/destination.yml
- schemas/server.yml
- schemas/source.yml
- template.json
As discussed earlier today, let's see if we can introduce this in Beta 2.
This would be very useful, as the field that's always guaranteed to have the endpoint address, no matter if it's an IP, a hostname or a unix socket.
> Introduce `source.address` and `destination.address`.

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/http.yml
- template.json
- use-cases/web-logs.md
- use-cases/web-logs.yml
This PR introduces the concept of metrics for HTTP events. It currently adds only the metrics for body and total (which includes headers). It's missing the obvious third wheel, header sizes. I wouldn't mind adding them if people feel strongly about it, but I haven't seen it come up in the few web server logging directives I've reviewed.
Speaking of which, here are some equivalencies:
- `http.request.bytes.total`: Apache httpd's `%I`, NGINX `$request_length`
- `http.request.bytes.body`: content-length header, NGINX `$content_length`, Traefik `RequestContentSize`
- `http.response.bytes.total`: Apache httpd's `%O`, NGINX `$bytes_sent`
- `http.response.bytes.body`: Apache httpd's `%B`, NGINX `$body_bytes_sent`, Traefik `DownstreamContentSize` (I think)
I do think logging both makes sense, for …
> Introduce size metrics for HTTP.

- CHANGELOG.md
- README.md
- fields.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/server.yml
- schemas/source.yml
This ensures that the most broadly applicable pair is always populated, and
can therefore always be queried.
Closes #246
> Require that source/destination are always populated

- CHANGELOG.md
- README.md
- fields.yml
- schema.csv
- schemas/os.yml
- template.json
I think having a field with the full OS name (including version) is a useful concept, in addition to the broken up `name` + `version` fields. It makes some types of analysis much simpler.
I was inspired to add this when I realized that our user agent parser gives us such a string, and ECS doesn't have a home for it.
> Add `os.full`, to allow capturing full OS name string, including version

- docs/contributing.asciidoc
- docs/conventions.asciidoc
- docs/fields-gen.asciidoc
- docs/fields.asciidoc
- docs/glossary.asciidoc
- docs/guidelines.asciidoc
- docs/index.asciidoc
- docs/use-cases-header.md
- docs/use-cases.asciidoc
Convert ECS readme.md file to asciidoc to be published at https://www.elastic.co/guide/index.html.
https://ecs-simple.firebaseapp.com/
Issue #276 opened to track additional steps
> Convert ECS doc from MD to asciidoc guide: initial setup

- .gitignore
- .travis.yml
- Makefile
This adds an almost empty `index.asciidoc` file to generate the initial asciidoc version of the docs. With this `make docs` can be used to generate and preview the docs.
This allows us to also validate the docs build in CI.
> Add automation around docs generation

- .travis.yml
- NOTICE.txt
- template.json
The goal of this backport is mainly about the copyright attribution (#285).
This also backports #277 and #282 to the 1.0 branch.
> Backport #277, #282 and #285 to branch 1.0

- Makefile
- schema.json
- scripts/schemas.py
Adds a script that generates a JSON representation of the ECS schema in the following format:
* The root-level keys are ECS namespace `name`s
* Every root-level value is an object containing the properties of a namespace
* Every namespace object contains a `fields` object, where each key is the `name` of the field, and the value is an object containing the properties of the field
Formatted output as screenshots:
- root-level (collapsed):
- an expanded root-level object:
A sample root-level object for the `agent` namespace:
```
{
"description": "The agent fields contain the data about the software entity, if any, that collects, detects, or observes events on a host, or takes measurements on a host. Examples include Beats. Agents may also run on observers. ECS agent.* fields shall be …
```
> Adds a script that generates a JSON representation of the ECS schema

- code/go/ecs/process.go
- scripts/cmd/gocodegen/gocodegen.go
Add special handling for the process.args field to ensure that it's generated as a []string.
> Generate process.args as []string in Go code

- CHANGELOG.md
- README.md
- code/go/ecs/user.go
- fields.yml
- schema.csv
- schema.json
- schemas/group.yml
- schemas/user.yml
- template.json
An error slipped in, and instead of nesting the `group` field set at `user.group`, we originally made this a `keyword` field.
This PR introduces a breaking change, but we are aiming to introduce this fix in ECS 1.0.0 GA.
The initial implementation went against our principle of not reusing top level object names elsewhere in the hierarchy, using different semantics.
This PR closes #304.
> Make `user.group` a nesting of the `group` field set

- CHANGELOG.md
- README.md
- code/go/ecs/host.go
- fields.yml
- schema.json
- schemas/host.yml
_**WAS:**_ "ECS host.* fields should be populated with details about the host on which the event happened, or **on** which the measurement was taken."
**_NOW:_** "ECS host.* fields should be populated with details about the host on which the event happened, or **from** which the measurement was taken."
> clarify host definition wording

- CHANGELOG.md
- README.md
- code/go/ecs/geo.go
- fields.yml
- schema.json
- schemas/geo.yml
Make it clearer that it's not necessarily based on GeoIP.
> Clarify `geo` field set description.

- README.md
- fields.yml
- generated/csv/fields.csv
- generated/ecs/fields_flat.yml
- generated/ecs/fields_nested.yml
- generated/legacy/schema.csv
- schema.json
- schemas/cloud.yml
PR #330 only fixed the text in the description :-)
> Fix the actual cloud.provider example.

- README.md
- docs/intro.md
- fields.yml
- schema.csv
- schemas/ecs.yml
- scripts/template.go
- template.json
As is customary for each release, this is making '1.0.0' the example value for `ecs.version`. This PR is meant for the `1.0` branch only.
Notes:
- template.json was already being generated with version 1.0.0
- libbeat's template.New had to be adjusted to include the `migration` param. Not sure why, but this isn't a problem on master.
> Ecs version 1.0.0

- README.md
- docs/implementing.md
Backports the following commits to 1.0:
- Add a 'how to populate ECS fields' section to readme  (#345)
> [1.0] Add a 'how to populate ECS fields' section to readme (#345)

- CHANGELOG.md
- README.md
- code/go/ecs/url.go
- fields.yml
- generated/csv/fields.csv
- generated/ecs/fields_flat.yml
- generated/ecs/fields_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/schema.csv
- schema.json
- schemas/url.yml
This discrepancy was noticed when I replaced the Go template generator with a
new one, in #336. Looks like the Beats generator was making the field `long`
even if the definition said `integer`.
> Change url.port datatype to long

- README.md
- docs/index.asciidoc
- docs/intro.md
This PR contains a few changes:
- Adjusting the wording of the maturity warning in the Markdown and Asciidoc files
- Removal of the asciidoc beta label
- Replace the warning mention at the top of the readme to be less maintenance to maintain
> Adjust the maturity warning for ECS to be aligned with GA / SemVer

- CHANGELOG.md
- README.md
- fields.yml
- schema.json
- schemas/geo.yml
Backport of PR #333 to 1.0 branch. Original message:
Loosened up the definition of `geo` fieldset. Not necessarily geo-ip based.
> Backport #333 to 1.0: Clarify `geo` field set description. (#333)

- README.md
- docs/implementing.md
Backports the following commits to 1.0:
- Clarify guidelines on ID fields.  (#349)
> [1.0] Clarify guidelines on ID fields. (#349)

- docs/contributing.asciidoc
- docs/conventions.asciidoc
- docs/fields-gen.asciidoc
- docs/fields.asciidoc
- docs/glossary.asciidoc
- docs/guidelines.asciidoc
- docs/index.asciidoc
- docs/use-cases.asciidoc
Backport of PR #266 to 1.0 branch. Original message:
* ECS doc conversion from md to asciidoc
* Add back uc-header file
* New asciidoc files
> Backport #266 to 1.0: Convert ECS doc from MD to asciidoc guide: initial setup (#266)

- docs/conventions.asciidoc
- docs/convert.asciidoc
- docs/faq.asciidoc
- docs/fields-gen.asciidoc
- docs/fields.asciidoc
- docs/glossary.asciidoc
- docs/guidelines.asciidoc
- docs/index.asciidoc
- docs/use-cases.asciidoc
Backport of PR #334 to 1.0 branch. Original message:
More work toward the move to asciidoc:
* Added new files and content.
* Played with the content of Base Fields to demonstrate a three-column format.
* Watch for possible terminology change from "core and extended" to "core and custom" for fields.
Want to see this rendered? https://ecs-docs.firebaseapp.com/ecs2/
> Backport #334 to 1.0: Phase 2 in conversion to asciidoc (#334)

- README.md
- docs/index.asciidoc
- docs/intro.md
- generated/csv/fields.csv
- generated/ecs/fields_flat.yml
- generated/ecs/fields_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
Backport of PR #344 to 1.0 branch.
> Backport #344 to 1.0: Adjust the maturity warning for ECS to be aligned with GA / SemVer (#344)

- .gitignore
- .travis.yml
- Makefile
Backport of PR #275 to 1.0 branch. Original message:
This adds an almost empty `index.asciidoc` file to generate the initial asciidoc version of the docs. With this `make docs` can be used to generate and preview the docs.
> Backport #275 to 1.0: Add automation around docs generation (#275)

- code/go/ecs/process.go
- scripts/cmd/gocodegen/gocodegen.go
Backport of PR #296 to 1.0 branch. Original message:
Add special handling for the process.args field to ensure that it's
generated as a []string.
> Backport #296 to 1.0: Generate process.args as []string in Go code (#296)

- CHANGELOG.next.md
- fields.yml
- generated/beats/fields.ecs.yml
- generated/ecs/fields_flat.yml
- generated/ecs/fields_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/event.yml
- schemas/http.yml
- schemas/network.yml
- schemas/server.yml
- schemas/source.yml
- scripts/generators/beats.py
The 1.0.0 field definitions generated by ECS (https://github.com/elastic/beats/pull/11150)
removed a few field formats that had previously been defined on the Beats side,
but were not yet part of ECS.
This adds all of the missing these fields formats to ECS, and generates a Beats
field definition file that includes them all.
> Define field formats that were defined in Beats but not yet in ECS.

- docs/field-details.asciidoc
- scripts/generators/asciidoc_fields.py
They didn't use asciidoc link helpers, so incorrectly pointed to to localhost:8000.
> Fix links to reused fields at the bottom of field set detail pages.

- docs/fields.asciidoc
- scripts/generators/asciidoc_fields.py
Asciidoctor is a bit pickier about start and end delimiter and complains
about this table because the start line has more `=`s than the end line.
This removes `=`s from the start until it lines up with the end.
> Docs: Fix a table start to align with the stop

- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- scripts/generators/beats.py
We fixed it Beats in https://github.com/elastic/beats/pull/11675. This brings
back the change in ECS, so the next version of ECS doesn't overwrite the fix.
Static ms output format isn't great, it's just the least bad option :-\
> Specify static output format for event.duration

- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- scripts/generators/beats.py
Backport of PR #425 to 1.0 branch. Original message:
Static ms output format isn't great, it's just the least bad option
> Backport #425 to 1.0: Specify static output format for event.duration

- docs/fields.asciidoc
- scripts/generators/asciidoc_fields.py
Backport of PR #430 to 1.0 branch. Original message:
Asciidoctor is a bit pickier about start and end delimiter and complains
about this table because the start line has more `=`s than the end line.
This removes `=`s from the table start, so it lines up with the table end.
> Backport #430 to 1.0: Docs: Fix a table start to align with the stop (#430)

- CHANGELOG.next.md
- code/go/ecs/event.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schemas/event.yml
- use-cases/auditbeat.md
This PR addresses/improves a few things in the the "event" field set.
If any of these turns out controversial / complicated, I'll be happy to extract them to a separate PR. The goal here is to get the simple things in.
- Added `event.code` (See https://github.com/elastic/beats/pull/10333)
- Added `event.sequence` (See https://github.com/elastic/ecs/issues/129, https://github.com/elastic/beats/pull/10760)
- Added `event.provider` (See https://github.com/elastic/ecs/issues/321)
- Note: Beats modules currently put the Syslog "programname" in `process.name` which is sometimes accurate, sometimes not (e.g. "kernel"). event.provider would be a better field for this.
- Explain event.module and event.dataset without mentioning Beats
Closes #321
Addresses part of #129
> Additions to event

- CHANGELOG.next.md
- code/go/ecs/file.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schemas/file.yml
This is take 2 of something started in #441. We're departing from the internal
consistency of the 4 Linux file timestamp names (atime, ctime, crtime, mtime),
and going for clear and readable names.
Right now this is only introducing the 2 missing fields, `created` and `accessed`.
I think it would make sense to rename the other two eventually. But since this would be a breaking
change, we'd have to deprecate them for a while & document how to handle deprecations in ECS, and so on. This can be done as a separate PR.
Adding these 2 fields unapologetically should be straightforward, though :-)
Closes #422
> Add 2 missing timestamps to `file`

- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
This closes #461, which was submitted by @codebrain, who use Windows --
ECS tooling doesn't currently run on Windows. Thanks Stuart!
> Fix exmple typo in process.yml

- schemas/log.yml
Accidentally merged #459 to 1.0, so forward-porting to master. Original message:
YAML file is missing the `group` parameter as defined as required by the documentation, default value set to 2.
> Forward port #459 to master: Update log.yml

- CHANGELOG.next.md
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/event.yml
- schemas/http.yml
- schemas/process.yml
- schemas/server.yml
- schemas/source.yml
- schemas/url.yml
Backport of PR #454 to 1.0 branch. Original message:
Changes the display format of things like port numbers and PIDs to string where appropriate. Changed fields are:
client.port
destination.port
event.severity
event.sequence (backport note: not in 1.0)
http.response.status_code
process.pid
process.ppid
process.pgid (backport note: not in 1.0)
process.thread.id
server.port
source.port
url.port
> Backport #454 to 1.0: Format port numbers and numeric IDs as strings

- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
Backport of PR #464 to 1.0 branch. Original message:
This closes #461, which was submitted by @codebrain, who use Windows --
ECS tooling doesn't currently run on Windows. Thanks Stuart!
> Backport #464 to 1.0: Fix exmple typo in process.yml

- code/go/ecs/process.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
Backport of PR #470 to 1.0 branch. Original message:
* Fix the example for `process.pid`
* Add example for ppid as well, and tweak its description a bit.
> Backport #470 to 1.0: Fix/add examples for the pid fields

- docs/using-guidelines.asciidoc
Follow-up to https://github.com/elastic/ecs/pull/480#issuecomment-498998734
> [ecs-metrics] docs: add guideline regarding units in names

- CHANGELOG.next.md
- code/go/ecs/host.go
- code/go/ecs/process.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schemas/host.yml
- schemas/process.yml
Closes #475
This PR adds fields for `process.uptime` and `server.uptime`. As suggested by @webmat, the uptime field will be measured in **seconds**.
> (#475) Add support for server and process uptime fields

- CHANGELOG.next.md
- code/go/ecs/client.go
- code/go/ecs/destination.go
- code/go/ecs/server.go
- code/go/ecs/source.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schemas/client.yml
- schemas/destination.yml
- schemas/server.yml
- schemas/source.yml
To better support Port/Address translation in flow/fw type network events added source.nat.ip, source.nat.port, destination.nat.ip, destination.nat.port.
If, in the case of e.g. 1:1 nat, the observer doesn't report nat ports, the original port should be copied to the nat.port field for ease of searching all fields of the connection (e.g. searching nat ips/ports for threat hunting etc)
To - do: 
If there is telemetry provided across devices implementing NAT (e.g. internally load balanced source nat sessions being reported across multiple devices before and after S/NAT) we may want to also include:
- nat.session_id
- copy native session id at NAT gateway to stitch together pre/post NAT sessions
> added nat.ip and nat.port to source and destination fields

- Makefile
- scripts/generator.py
- scripts/generators/ecs_helpers.py
- scripts/schema_reader.py
- scripts/tests/test_ecs_helpers.py
- scripts/tests/test_ecs_spec.py
- scripts/tests/test_schema_reader.py
This adds the ability to pass a path to `make` (which is used by the `generator` target) to a directory where users might have their own schemas defined. 
The use case this is solving for is when a user has custom schemas that are required due to being unable to map fields directly to ECS Core/Extended fields. This change allows them to run the following to have their schemas included in the output of `make` or `make generate`:
```
$> make INCLUDE=/path/to/dir/of/yml/files
or 
$> make generator INCLUDE=/path/to/dir/of/yml/files
```
If `INCLUDE` does not exist, everything works as per usual. If `INCLUDE` does not contain any yml files everything works as per usual. If `INCLUDE` contains yml files the keys/values are merged with those found in the `schemas` directory and the output is for …
> Add ability to include external directory of schemas when running generator

- code/go/ecs/service.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schema.json
- schemas/service.yml
This removes an example that went contrary to the purpose of a `service.id`.
If someone needs to focus on the events emitted by one host of a
service, they should filter on `host.id` or `host.name`.
`service.id` is meant to identify a service as a whole.
> Clarify `service.id` description.

- code/go/ecs/service.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/service.yml
Backport of PR #502 to 1.0 branch. Original message:
This removes an example that went contrary to the purpose of a `service.id`.
If someone needs to focus on the events emitted by one host of a
service, they should filter on `host.id` or `host.name`.
`service.id` is meant to identify a service as a whole.
> Backport #502 to 1.0: Clarify `service.id` description.

- CHANGELOG.md
- CHANGELOG.next.md
This is a forward port of the 1.1.0 changelog, from the 1.1 branch.
Original PR is #527.
> Forward port: Cut 1.1.0 changelog, add contributor guidelines to changelog.next

- .travis.yml
With the recent addition of the more authoritative 'elasticsearch-ci/docs' CI job, the TravisCI job for docs is redundant.
> Remove the 'docs' task from TravisCI.

- docs/index.asciidoc
This file has moved. It *is* interesting to think about *which* include
file we should use. There are lots of different "versions" of the stack
that we might we use here, but this uses the same version that we used
in the file that has moved.
> Docs: Update an include file

- .gitignore
- CHANGELOG.md
- CHANGELOG.next.md
- code/go/ecs/service.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schema.json
- schemas/service.yml
> Adding service.node.name

- code/go/ecs/log.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schema.json
- schemas/log.yml
> Clarify documentation for log.origin.file.*

- CHANGELOG.next.md
- code/go/ecs/group.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schema.json
- schemas/group.yml
Added group.domain field in the group schema.
I've been working with Window's Security Groups Events and the group domain needs to be mapped into ECS in order to be able to correlate with others events
(Example events 4731,4732,4733,... where the SubjectDomainName is the domain of the group created/modified/deteled, etc)
Another use case I found to justified the existence of the group,domain was several Fortigate Logs where group="DOMAIN\GROUP" appears as field (for example log_id=0315093008)
> Add domain field to Group Schema

- CHANGELOG.next.md
- code/go/ecs/event.go
- code/go/ecs/log.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schema.json
- schemas/event.yml
- schemas/log.yml
This PR is meant to replace and close #301.
Unfortunately #301 is too old to be brought up to date with the current state
of the ECS repo.
While bringing the discussion we had in the original PR to present day ECS,
I'm proposing a few changes to what we had there. Comments welcome, if you
agree/disagree.
In this PR:
- Modify description of `log.level` and associate it with Syslog's severity label.
- Modify description of `event.severity` and associate it with Syslog's severity numeric code.
- Add field `log.facility` as the text-based representation.
- Add field `log.facility_code` as the numeric representation.
- Add field `log.priority` (numeric only: 8 * facility + severity)
Differences with #301:
- I'm nesting under `log.*` instead of `event.*`, because I feel like these very …
> A new take on adding missing Syslog fields to ECS.

- code/go/ecs/log.go
- docs/field-details.asciidoc
- docs/fields.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schema.json
- schemas/log.yml
This is meant to help clarify the difference between `log` and `event`.
Relates to #525 and address some concerns voiced in #516.
> Beef up the description of the `log` field set.

- CHANGELOG.next.md
- code/go/ecs/client.go
- code/go/ecs/destination.go
- code/go/ecs/dns.go
- code/go/ecs/server.go
- code/go/ecs/source.go
- code/go/ecs/url.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schema.json
- schemas/client.yml
- schemas/destination.yml
- schemas/dns.yml
- schemas/server.yml
- schemas/source.yml
- schemas/url.yml
This PR is meant to finalize the work on #542 by applying the feedback in time
for ECS 1.2.0. Thanks for getting this started, @mbudge!
Closes #542
> Added top_level_domain

- code/go/ecs/url.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schema.json
- schemas/url.yml
Added a url extension field as using the file.extension field to store this could confuse security analysts. It should be easier for security analysts to associate extension and url if it's in the url object. We want to avoid them thinking the file exists on the computer straight away.
Proxy logs provide the file extension in a uri extension field, along with 
uri schema
uri domain
uri query
uri path etc..
Security analysts will want to look for file types like exe, js, swf, hda, vb, vbs, jar, bat coming from suspicious sites/locations.
> Added url.extension field

- CHANGELOG.next.md
- code/go/ecs/host.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schema.json
- schemas/host.yml
I'm working with windows events 4741,4742 and 4743.
When mapping into ECS I realize that I need a field host.domain 
I found also that host.domain is necessary when mapping certain Fortigate Logs
> Add host.domain field

- CHANGELOG.next.md
- code/go/ecs/process.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schema.json
- schemas/process.yml
Doing this via normal field reuse is pretty tricky at this time. This is the
first time a field set gets reused under a different name ("process" nested as "parent").
So for now I suggest simply duplicating all fields.
In order to avoid issues with this duplication:
- I call this out and explain it at length in a comment at the top of the `process.yml` file.
- Each duplicate entry is directly below the entry it copies in this file
(e.g. `process.pid` is directly followed by `process.parent.pid`)
- Note that the generated docs are sorted by the flattened key name. So all `parent.*`
fields will actually be grouped in the generated files.
Closes #597.
> Add process.parent by duplicating all fields explicitly

- docs/products-solutions.asciidoc
Backport of PR #592 to 1.2 branch. Original message:
Pointing users to log formatters that support ECS out of the box.
> Backport #592 to 1.2: Add link to ecs-logging project

- docs/products-solutions.asciidoc
Backport of PR #592 to 1.1 branch. Original message:
Pointing users to log formatters that support ECS out of the box.
> Backport #592 to 1.1: Add link to ecs-logging project (#592)

- docs/products-solutions.asciidoc
Backport of PR #592 to 1.0 branch. Original message:
Pointing users to log formatters that support ECS out of the box.
> Backport #592 to 1.0: Add link to ecs-logging project

- CHANGELOG.next.md
This will let us differentiate between schema (normative) changes and changes
to the tooling and artifacts around the schema.
> Split changelog in two sections

- CHANGELOG.next.md
- generated/csv/fields.csv
- scripts/generators/csv_generator.py
In this PR:
- Add the field set column
- Add the short description
- Add whether the field should be indexed
- Reorder the columns a bit, so the stable length values are first
Preview GitHub's rendering of [generated/csv/fields.csv](https://github.com/webmat/ecs/blob/flesh-out-csv/generated/csv/fields.csv) (scroll right for definitions)
> Flesh out the csv a little

- CHANGELOG.next.md
Backport of PR #633 to 1.3 branch.
> Backport #633 to 1.3: Split changelog in two sections

- Makefile
- schemas/process.yml
This used to be covered by running spell-checker on the readme. But the schema's no longer there.
> Run misspell on the schema definitions too

- CHANGELOG.next.md
- generated/csv/fields.csv
- scripts/generators/csv_generator.py
Backport of PR #621 and #638 to 1.3 branch. Original message:
In this PR:
* Add the field set column
* Add the short description
* Add whether the field should be indexed
* Reorder the columns a bit, so the stable length values are first
Preview GitHub's rendering of [generated/csv/fields.csv](https://github.com/webmat/ecs/blob/backport_622_1.3/generated/csv/fields.csv) (scroll right for definitions)
> Backport #621 to 1.3: Flesh out the csv a little

- Makefile
- schemas/process.yml
Backport of PR #631 to 1.3 branch.
> Backport #631 to 1.3: Run misspell on the schema definitions

- CHANGELOG.next.md
- code/go/ecs/tls.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/tls.yml
Unlike the client, the server doesn't provide a list of supported ciphers in its hello message.
> Remove tls.server.supported_ciphers field

- CHANGELOG.next.md
- code/go/ecs/tls.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/tls.yml
Unlike the client, the server doesn't provide a list of supported ciphers in its hello message.
> Remove tls.server.supported_ciphers field (#662)

- CHANGELOG.next.md
- code/go/ecs/threat.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/as.yml
- schemas/error.yml
- schemas/file.yml
- schemas/http.yml
- schemas/organization.yml
- schemas/os.yml
- schemas/process.yml
- schemas/threat.yml
- schemas/url.yml
- schemas/user.yml
- schemas/vulnerability.yml
- scripts/generators/asciidoc_fields.py
- scripts/schema_reader.py
This implements many fields mentioned in https://github.com/elastic/ecs/issues/570.
Note: I'm not adding `host.name`, mentioned in 570 because the default analyzer doesn't split on `-`. So I'm not sure it's worth adding. Please let me know if I'm missing something.
In going over the fields, I've identified a few more that I think may be interesting to add to this PR. Please voice your opinions. I'm happy to hold off or add now:
* dns.question.name
* threat.technique.name
* vulnerability.description
* tls.client.issuer, tls.client.subject, tls.server.issuer, tls.server.subject
@neu5ron @randomuserid @rw-access @MikePaquette @peasead
> Add the default text analyzer to some fields

- generated/beats/fields.ecs.yml
- scripts/generators/beats.py
- scripts/generators/beats_default_fields_whitelist.yml
The generator was not adding `default_field: false` to `multi_fields`. This again causes Beats to exceed the number of fields in the default list due to the recent addition of some multi_fields.
This will add the tag to multifields that are not in the whitelist and whose parent field is in the whitelist. If the parent field is not in the whitelist, the tag is already inherited.
> Beats: Set default_field=false in multi_fields

- docs/using-custom-fields.asciidoc
`message` was incorrectly nested inside `event`
> Fix a mistake in the custom fields doc page.

- CHANGELOG.next.md
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- scripts/schema_reader.py
- scripts/tests/test_schema_reader.py
This PR improves the ECS ability to nest reusable fields inside other reusable field sets. Currently there is at least one example of multiple reuse: "group" fields are reused in "user", and "user" is then reused by "client", "destination", "host", "server", and "source". However, the implementation in master depends on the "group" fields being copied to "user" before all of the "user" fields are copied to the final locations. This works because the "group" key comes before the "user" key when iterating over the keys in the schema dictionary, but this will not be the case for other places we might want to use multi-level nesting.
This PR adds an intermediate data structure representing the schema which contains references to reused field sets rather than immediately copying them. Using …
> Refactor schema reader to use intermediate schema structure

- CHANGELOG.next.md
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/hash.yml
- scripts/schema_reader.py
- scripts/tests/test_schema_reader.py
Same idea as #698 redone to integrate with intermediate data format changes.
Recently process.parent fields that are identical to the process fields were added to ECS, but the hash fields that are nested under "process" did not get added to process.parent. This PR adds "process.parent" to the list of nestings in "hash" and also support for nesting fields at levels other than the top level of the destination schema using the '.' notation (e.g. process.parent). Previously nested fields could only be inserted at the top level.
> Add missing hash fields to process.parent: attempt 2

- CHANGELOG.next.md
- scripts/generator.py
- scripts/generators/ecs_helpers.py
- scripts/schema_reader.py
- scripts/tests/test_ecs_helpers.py
- scripts/tests/test_ecs_spec.py
- scripts/tests/test_schema_reader.py
This PR extends prior work on the intermediate data format introduced in https://github.com/elastic/ecs/pull/722 and provides a way to specify a subset of the full set of ECS fields plus any fields defined by a custom schema and render only that subset to the generated files.  This would be particularly useful when multiple types of documents will be stored in the same index: one monolithic set of fields can be defined using the official ECS fields in addition to a custom schema that encompass every possible field for the documents, and the --subset parameter can be used to define which fields exist in each type of document.
An example subset document is
```---
host: "*"
base:
"@timestamp": "*"
agent:
id: "*"
name: "*"
event: "*"
```
This subset includes every field in `host`, …
> Allow generation of a subset of ECS and custom schema fields

- CHANGELOG.next.md
- Makefile
- scripts/generator.py
- scripts/generators/asciidoc_fields.py
- scripts/generators/beats.py
- scripts/generators/csv_generator.py
- scripts/generators/ecs_helpers.py
- scripts/generators/es_template.py
- scripts/generators/intermediate_files.py
- scripts/schema_reader.py
This PR adds the `--out` switch to specify where the generated files and docs are to be written. If the directory does not exist it will be created.
> Adding --out flag

- CHANGELOG.next.md
- code/go/ecs/process.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/process.yml
This implements the unique process identification field discussed in https://github.com/elastic/ecs/issues/672. We settled on allowing ECS users to use their own implementation-specific values in this field in order to support multiple types of data shippers that may have different requirements around the identifier generation. That said, there's still room for future discussion on some sort of standard generation algorithm that would allow us to correlate processes across multiple sources.
The name corresponds to what beats are already filling in for their unique identifier.
> Add entity_id for process and process.parent

- CHANGELOG.next.md
- code/go/ecs/event.go
- docs/field-details.asciidoc
- docs/field-values.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
Since publishing ECS 1.4, where the ECS categorization fields were introduced, the `event.outcome` field has generated the most questions about its definition, use, and consistency.
This PR significantly expands the definitions and example usage of event.outcome based on the feedback from the community.
No field names or allowed values are changed with this PR.
> Enhance description of event.outcome field

- CHANGELOG.next.md
- docs/field-details.asciidoc
- docs/field-values.asciidoc
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
This new value of `event.category` is being added to properly categorize Identity and access management events relating to users, groups, and admin.
It is expected that this category would be used to visualize and analyze iam-related logs and data from sources such as active directory, LDAP, Okta, Duo, and other IAM systems.
There are three new values of `event.type` associated with this new addition.
> Categorization: Add new "iam" category and associated types "admin", "group", "user"

- CHANGELOG.next.md
- code/go/ecs/event.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/event.yml
ECS already has a `rule.reference` field to contain a reference URL to additional information about a rule used to generate an event/alert. The URL can point to the vendor’s documentation about the rule, or if that’s not available, it can also be a link to a more general page describing this type of alert.
However some systems provide not only a reference to the rule that created the event, but also to the specific instance of the event or alert itself.
This URL can link to another system where additional or in-depth investigation the specific occurrence of this event can take place.  Alert events, indicated by `event.kind:alert`, are a common use case for this field.
example: https://mysystem.mydomain.com/alert/5271dedb-f5b0-4218-87f0-4ac4870a38fe
This new field `event.reference` is for …
> Add event.reference field

- docs/field-details.asciidoc
- scripts/generators/asciidoc_fields.py
The _Field Reuse_ section of docs was not documenting nested fields correctly.
For example, if interface can be nested under `observer.ingress` and `observer.egress`, the docs would display `observer.interface.*`, instead of `observer.ingress.interface.*` and `observer.egress.interface.*`.
This patch improves the docs by adding the full nesting path.
Before:
After:
> Improve nested fields documentation

- docs/field-details.asciidoc
- scripts/generators/asciidoc_fields.py
Backport of PR #784 to 1.5 branch. Original message:
The Field Reuse section of docs was not documenting nested fields correctly.
For example, if interface can be nested under `observer.ingress` and `observer.egress`, the docs would display `observer.interface.*`, instead of `observer.ingress.interface.*` and `observer.egress.interface.*`.
This patch improves the docs by adding the full nesting path.
> Backport #784 to 1.5: Fix nested fields documentation

- CHANGELOG.next.md
- docs/field-details.asciidoc
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/registry.yml
Fixes #776
Please re-run generator before approving, thanks!
> registry.data.strings field missing array definition.

- CHANGELOG.next.md
- code/go/ecs/log.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/log.yml
A few points to note about this PR:
* This is not nesting all of `file.*` at `log.file.*`, this is adding a single field only: `log.file.path`. If I remember correctly, it's the first time we do this.
* If there's a need for more `file.*` fields we could add them, but so far that need has not arisen.
* This approach also made it possible to tailor the field description to this specific use case.
* Where `file.path` has a `text` multi-field which may be useful for threat hunting in arbitrary file paths, `log.file.path` does not. The thinking is that these log files are controlled by operators and aren't "user data" in which we're likely to do threat hunting. This is something we can add later if needed.
* This PR also adjusts the field description for `log.origin.file.name` to …
> Add `log.file.path` to capture the log file path, following Filebeat convention.

- CHANGELOG.next.md
- code/go/ecs/user.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/user.yml
> Clarify the `user.id` definition, the field should contain a single ID.

- CHANGELOG.next.md
- code/go/ecs/client.go
- code/go/ecs/destination.go
- code/go/ecs/server.go
- code/go/ecs/source.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/server.yml
- schemas/source.yml
These fields are meant to be a single IP, not "one or more" IP addresses.
Closes #786
> Remove misleading wording about multiple IPs in src/dst or cli/srv

- CHANGELOG.next.md
Backport of PR #798 to 1.5 branch.
> Backport #798 to 1.5: Missing changelog for #784

- CHANGELOG.next.md
- docs/field-details.asciidoc
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- scripts/generator.py
- scripts/generators/asciidoc_fields.py
- scripts/generators/ecs_helpers.py
- scripts/schema_reader.py
- scripts/tests/test_ecs_helpers.py
- scripts/tests/test_schema_reader.py
Closes #796 
A few related fixes in this PR:
- `nestings` array now contains the full path to reused fields within a fieldset, rather than just containing the name of the reused fieldset.  This better identifies places where a fieldset is reused multiple times within another set.
- Moved the `original_fieldset` logic from into the function where reused fields are converted from references to copies.  This makes the ecs_flat and ecs_nested files more consistent - `original_fieldset` was showing up in reusable fields even at the top level in ecs_flat.  However, it was supposed to be identifying places where a field was actually being reused.
- Refactor ascii doc generation to use intermediate field data structure instead of both the flat and nested structures.  This makes the logic easier …
> Handle nestings better and refactor asciidoc generation

- CHANGELOG.next.md
- scripts/generator.py
- scripts/generators/ecs_helpers.py
- scripts/tests/test_ecs_helpers.py
This PR makes the subset notation less cumbersome by including all subfields if the `fields` key is missing.  Instead of writing 
```
field1:
fields: *
```
every time you want to include all subfields, you can instead write 
```
field1: {}
```
This still leaves the ability to specify other options for the field in the dictionary later on without breaking changes.
> Shorthand subset notation

- CHANGELOG.next.md
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- scripts/generator.py
- scripts/schema_reader.py
Most reusable field sets in ECS are **not** expected at the root of the documents. As of ECS 1.5.0:
| reusable field set | expected at root |
| --- | --- |
| `as` | no |
| `code_signature` | no |
| `geo` | no |
| `group` | yes |
| `hash` | no |
| `interface` | no |
| `os` | no |
| `pe` | no |
| `user` | yes |
| `vlan` | no |
Unfortunately, ever since the introduction of reusable fields, these field sets remained defined at the root nonetheless, for some of the generated artifacts.
The official documentation correctly mentions which field sets were expected at the root and which weren't. This issue however affected the following artifacts:
* 'ecs_flat.yml'
* the csv
* the Elasticsearch sample templates
* Beats field definition file
This PR does not affect the Beats field definitions for …
> Fix bug #495

- CHANGELOG.next.md
- scripts/generator.py
The beats output files are used to create the `fields.yml` mapping file for the endpoint package's mapping located here: https://github.com/elastic/package-registry/tree/master/dev/packages/example/endpoint-1.0.0/dataset/events/fields
The endpoint team needs the ability to generate the beats output while using the `--include` and `--subset` flags because we specify custom fields for our alerts and also leverage the subset functionality to limit the fields from ecs core.
The typical command I use to generate the `fields.yml` file is:
`python scripts/generator.py --out ../gen --include ../endpoint-app-team/custom_schemas --subset ../endpoint-app-team/custom_subsets/elastic_endpoint/events/* ../endpoint-app-team/custom_subsets/*.yml`
> Allowing beats output files to be generated with --include and --subset

- .travis.yml
- Makefile
Removing `virtualenv` requirement.  Python3 is already a requirement in contributing.
> switch to python3 venv module

- CHANGELOG.next.md
- code/go/ecs/cloud.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/cloud.yml
Adds:
* account.name
* project.id
* project.name
> Standardize additional cloud metadata

- docs/faq.asciidoc
Removes an incorrect definition of the [`nested` field datatype][0].
An [`object` datatype][1], which is used by the Elastic Common Schema,
can also contain an array of objects as a value.
The primary difference between the `object` and `nested` datatypes is
that objects in a `nested `datatype can be queried independently.
However, that distinction isn't needed or relevant here.
Closes #826
[0]: https://www.elastic.co/guide/en/elasticsearch/reference/master/nested.html
[1]: https://www.elastic.co/guide/en/elasticsearch/reference/master/object.html
> [DOCS] Removes incorrect `nested` datatype definition

- docs/faq.asciidoc
Backport of PR #827 to 1.5 branch. Original message:
Removes an incorrect definition of the [`nested` field datatype][0].
An [`object` datatype][1], which is used by the Elastic Common Schema,
can also contain an array of objects as a value.
The primary difference between the `object` and `nested` datatypes is
that objects in a `nested `datatype can be queried independently.
However, that distinction isn't needed or relevant here.
[0]: https://www.elastic.co/guide/en/elasticsearch/reference/master/nested.html
[1]: https://www.elastic.co/guide/en/elasticsearch/reference/master/object.html
> Backport #827 to 1.5: [DOCS] Removes incorrect `nested` datatype definition (#827)

- CHANGELOG.next.md
- code/go/ecs/http.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/http.yml
Remove guidance to lowercase http.request.method
Closes #838
> Remove guidance to lowercase http.request.method

- .travis.yml
- CHANGELOG.next.md
- Makefile
- scripts/generator.py
- scripts/generators/ecs_helpers.py
- scripts/requirements.txt
- scripts/schema_reader.py
- scripts/tests/test_ecs_helpers.py
- scripts/tests/test_ecs_spec.py
- scripts/tests/test_schema_reader.py
Closes https://github.com/elastic/ecs/issues/837
This provides an easy way to use the upgraded tooling in master to build any version of the ECS schemas.  The new `build-version` command line option accepts both tags, such as `v1.5.0`, and commit hashes, such as `1454f8b`. This makes it easy to use new tooling features related to custom schemas with a stable released version of the official schema.
> Add build-version option for building specific versions of ECS

- docs/additional.asciidoc
Improve `additional.asciidoc` appearance by adding a list of links to its subpages.
> Add a list of links to subpages

- CHANGELOG.next.md
- scripts/generator.py
- scripts/generators/es_template.py
Little quality of life improvement that lets users override the default template and mapping settings for the generated ES templates. This PR adds 2 new options, `template-settings` and `mapping-settings` that take in filenames and use those json files to populate the template and mapping settings of the generated ES template.
Example usage, run in the ECS directory:
`python scripts/generator.py --mapping-settings custom_mapping.json --template-settings custom_template.json`
This replaces the mapping and template settings with whatever is in custom_mapping.json and custom_template.json, respectively.
> Add option for custom template and mapping settings

- .github/ISSUE_TEMPLATE/schema-changes-additions.md
Missing hyphen is causing Github to omit this issue template as a selection.
> add missing required hyphen

- CHANGELOG.next.md
- code/go/ecs/threat.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/threat.yml
I saw some verbiage for `threat.*` that mentioned the MITRE ATT&CK® framework but needed to be adjusted.
Some of the changes
- Added ®. We were supposed to have ™ before, but early in 2020 they were granted ®.
- Correctly spelled MITRE with all capital letters
- Removed some confusing verbiage like "You can use the Mitre ATT&CK Matrix Tactic categorization." The words "Tactic categorization" are a little confusing and not part of the framework. Instead I went with "You can use a MITRE ATT&CK Matrix® tactic, for example." Also, it's possible to mention tactics without concrete techniques and vice versa, so I removed any language that coupled them together.
> Fix some ATT&CK verbiage and trademark

- CHANGELOG.next.md
- code/go/ecs/process.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/code_signature.yml
- schemas/hash.yml
- schemas/process.yml
The `process.parent` fields had initially been defined by duplicating each field explicitly, since the field reuse mechanism didn't support field reuse within the same field set at the time.
Introducing `process.parent.*` by duplicating fields has predictably led to a few small mistakes, despite us squinting very hard and trying to avoid this :-)
* At least one process field was modified without having the same modification applied to its `process.parent` twin.
* Also, the field set `pe` was only reused under `process`, but not `process.parent`. This was not intentional.
This PR removes the field duplication by using the improved reuse mechanism. This means both problems described above are also resolved by this PR.
> Define process.parent via the new field reuse mechanism

- rfcs/README.md
It was currently only referenced from PROCESS.md. Mentioning it in the RFC readme will make it more discoverable.
> Add a mention of the stages table right in rfcs/README.md

- CHANGELOG.next.md
- code/go/ecs/tracing.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/tracing.yml
Add `span.id` to the tracing fields. This field may be useful for correlating logs with more specific operations, or where `transaction.id` is unavailable.
The `transaction.id` field is not always available for trace data received from other tracing systems, such as Jaeger and OpenTelemetry. We are guaranteed to have `trace.id` and `span.id`, but not necessarily `transaction.id`. Correlating logs with an entire trace (via `trace.id`) may result in too broad a set of results, compared to correlating with `span.id`.
> schemas/tracing.yml: add span.id

- .github/ISSUE_TEMPLATE/schema-changes-additions.md
- .github/PULL_REQUEST_TEMPLATE.md
Two GitHub template updates:
1. Add a link in the PR template to the RFC README.
2. Indicate the `schema-changes-additions` issue type is intended for smaller, less substantial schema changes.
> Update templates to reference RFC process

- README.md
- USAGE.md
Adds `USAGE.md` covering the getting started experience and usage of the ECS tooling. The current `generator.py` arguments are documented along with example usage.
The aim is to simplify the experience for users generating their own artifacts (based off the published or custom schema definitions).
`USAGE.md` is linked from `README.md`
**Caveats**
* Once the changes from #873 are merged, the `--subset` usage will need to be updated to reflect the modified `subset` file format and improvements
Addresses #746
> Usage improvements

- docs/products-solutions.asciidoc
Two very minor changes to this page:
* Include a reference the [SIEM field reference guide](https://www.elastic.co/guide/en/siem/guide/current/siem-field-reference.html)
* This is a great reference resource and definitely should be linked to 😎 
* However, I'm not sure this should be the long-term place, but I think it works for now
* Ensure the Logs app link points at `current`.
* replace the static link with a generated one
> Update solutions reference section

- rfcs/0001-rfc-environment.md
- rfcs/0002-rfc-environment.md
Proposal to adopt the `service.environment` attribute to qualify the environment from which an event is emitted (e.g. `production`, `staging`, `qa`, `dev`).
> [RFC] `service.environment` field

- rfcs/0000-rfc-template.md
- rfcs/text/0001-wildcard-data-type.md
- rfcs/text/0002-rfc-environment.md
- rfcs/text/0003-object-field.md
This PR:
* clarifies instructions around the ID and the date at the top of an RFC
* adds a "References" section at the very end of the RFC template. This section is meant to collect all links relevant to the RFC. It also contains a subsection for RFCs to link to each of their stage PRs.
* adjusts the 3 merged RFCs to link to their stage 0 PR.
> Improvements for the RFC template, and adjustments to existing RFCs.

- CONTRIBUTING.md
Two minor doc updates:
1. Update link for the ECS-tagged Discuss page
2. Update ECS Slack channel
> updating slack and discuss

- CHANGELOG.next.md
- code/go/ecs/event.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/event.yml
**Summary**
Adds a new field under `event.*`, `event.reason`, which provides a location to capture the reason _why_ an event occurred.
**Example usage**
* A web proxy event shows a denied connection request. `event.action:"request-denied"` describes the action captured and why the action took place is captured in `event.reason:"Blocked site: example.com"`
* An endpoint agent terminates a process on a host system. `event.action:"process-terminated" with reason describing why as `event.reason:"Terminated an unexpected process"` 
**Discussion Points**
Two items I wanted to call to attention: 
1. `event.reason` is currently defined as `type: extended`. This felt most appropriate starting off.
2. A `text` multi-field is included. `event.reason` could possibly hold a longer string (e.g. `File …
> Add event.reason field

- docs/using-getting-started.asciidoc
In reviewing #908 and #911 I noticed some missing shortcuts in the docs. They're not
related to the product rename so I'm addressing separately here. 
I also caught a small typo on "geopip" :-)
> Replace a few direct links in the docs with shortcuts

- CHANGELOG.next.md
- code/go/ecs/client.go
- code/go/ecs/destination.go
- code/go/ecs/dns.go
- code/go/ecs/event.go
- code/go/ecs/server.go
- code/go/ecs/source.go
- code/go/ecs/url.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/dns.yml
- schemas/event.yml
- schemas/server.yml
- schemas/source.yml
- schemas/tls.yml
- schemas/url.yml
- schemas/x509.yml
**Summary**
Two minor documentation changes for the `event.*` field set:
* ~Removed the "live" URL links by adding quotes to the string.~ This is actually incorrect. Our documentation generator is handling this by always wrapping example strings with backticks (`). As long as we ensure the examples don't use potentially valid domains, I don't think we need to worry about being "defensive" for other doc locations which may render a hyperlink for the URLs (e.g. [Beats](https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-ecs.html)).
* Switched example URLs to use the IANA reserved `*.example.com`
> Use appropriate reserved domain for example URLs

- code/go/ecs/user.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/user.yml
This array field is meant to capture a list of role names that apply to the user, in an audit log or other RBAC event.
Closes #915
> Add field `user.roles`

- CHANGELOG.next.md
- code/go/ecs/related.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/related.yml
**Summary**
Add a ~`related.host`~ `related.hosts` field. Same intention as the existing `related.*` fields: populate with all hostnames and other host identifiers from the event.
Closes #863
> add related.hosts

- docs/using-getting-started.asciidoc
Backport of PR #916 to 1.5 branch. Original message:
In reviewing #908 and #911 I noticed some missing shortcuts in the docs. They're not
related to the product rename so I'm addressing separately here.
I also caught a small typo on "geopip" :-)
> Backport #916 to 1.5: Replace a few direct links in the docs with shortcuts

- docs/products-solutions.asciidoc
- docs/using-getting-started.asciidoc
Related to https://github.com/elastic/docs/pull/1932
This PR addresses the following links that will be broken when "current" shifts to the 7.9 documentation branch:
````
13:54:52 INFO:build_docs:Bad cross-document links:
13:54:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/ecs/1.3/ecs-products-solutions.html:
13:54:52 INFO:build_docs:   - en/siem/guide/7.9/siem-overview.html
13:54:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/ecs/1.4/ecs-products-solutions.html:
13:54:52 INFO:build_docs:   - en/siem/guide/7.9/siem-overview.html
13:54:52 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/ecs/1.5/ecs-products-solutions.html:
13:54:52 INFO:build_docs:   - en/siem/guide/7.9/siem-overview.html
13:54:52 INFO:build_docs: …
```
> [DOCS] Fixes SIEM links

- docs/products-solutions.asciidoc
- docs/using-getting-started.asciidoc
This is a backport of #908 to the 1.x branch.
> [1.x][DOCS] Fixes SIEM links

- CHANGELOG.next.md
- code/go/ecs/http.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/http.yml
**Discussion points**
Closes #749
> Add http.[request|response].mime_type

- CHANGELOG.next.md
- code/go/ecs/http.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/http.yml
* Add http.[request|response].mime_type (#944)
> [1.x] Add http.[request|response].mime_type (#944)

- CHANGELOG.md
- CHANGELOG.next.md
Forward-ports the following commits to `master`:
* Move changelog entries to more appropriate subsections #933
* Cut CHANGELOG for 1.6.0 release (#923)
Additionally, 40065ee re-adds the two `CHANGELOG.next` entries added since #923
> [master] Move changelog entries to more appropriate subsections (#933)

- CHANGELOG.md
- CHANGELOG.next.md
- [master] Move changelog entries to more appropriate subsections (#933) (#952)
> [1.x] Cut 1.6 Changelog (#933) (#952)

- CHANGELOG.next.md
- code/go/ecs/threat.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/threat.yml
Closes #867
For more context on why it makes sense to nest this at `threat.technique.subtechnique`, see #867 and the related Kibana issue.
I also updated the example information, since it was before ATT&CK added subtechniques, and I wanted to make sure everything was fully consistent with one example. PowerShell is one of my gotos (formerly T1086, now T1059.001).
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?  ✔️ 
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/master/CONTRIBUTING.md)?  ✔️ 
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/master/rfcs/README.md)? N/A
- If submitting code/script changes, have you …
> Add threat.technique.subtechnique

- CHANGELOG.next.md
- Makefile
- USAGE.md
- scripts/generator.py
- scripts/generators/ecs_helpers.py
- scripts/schema/cleaner.py
- scripts/tests/unit/test_schema_cleaner.py
Adding a `--strict` option to the ECS generator script that performs more strict schema validation during the schema cleaning phase.
Initially, `--strict` will only enforce one validation: short descriptions be less than 120 characters and on a single line.
Example usage:
`$ python scripts/generator.py --strict`
Closes #892
> Introduce `--strict` flag

- CHANGELOG.next.md
- code/go/ecs/threat.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/threat.yml
- Add threat.technique.subtechnique (#951)
> [1.x] Add threat.technique.subtechnique (#951)

- CHANGELOG.next.md
- scripts/schema/finalizer.py
- scripts/tests/unit/test_schema_finalizer.py
In `schema.finalizer.perform_reuse`, the foreign reuse phase wasn't applying the `as` value to the destination reuse object if supplied by the user. This PR addresses this using the same logic as the self-nesting phase.
Additional unit tests to capture this particular case are also included.
Closes #959
> Nest as for foreign reuse

- rfcs/text/0000-host-identifiers.md
- rfcs/text/0006-host-identifiers.md
This RFC PR is seeking stage 0 acceptance. The strawperson document proposes establishing better conventions around host identifiers in ECS. 
[Preview of the RFC](https://github.com/ebeahan/ecs/blob/host-identifiers-stage-0/rfcs/text/0000-host-identifiers.md)
> [RFC] Host Identifiers

- CHANGELOG.next.md
- docs/field-values.asciidoc
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
As an `allowed_value` under `event.type`, `protocol` shouldn't have the `expected_event_types` section defined.
This change will remove from the schema as well as in the ECS documentation.
> Remove `expected_event_types` from protocol

- CHANGELOG.next.md
- docs/field-values.asciidoc
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- Remove `expected_event_types` from protocol (#964)
> [1.x] Remove `expected_event_types` from protocol (#964)

- rfcs/text/0001-wildcard-data-type.md
Revisions to the stage 0 wildcard adoption for consideration to be accepted as a stage 1 proposal.
[Markdown preview of this RFC](https://github.com/ebeahan/ecs/blob/wildcard-rfc-stage-1/rfcs/text/0001-wildcard-data-type.md)
> [RFC] Wildcard - stage 1 proposal

- CHANGELOG.next.md
- code/go/ecs/destination.go
- code/go/ecs/source.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/destination.yml
- schemas/source.yml
Update the descriptions for both `source.*` and `destination.*` field sets:
* Explicitly state that `source.*` and `destination.*` are considered the ECS baseline for capturing the details of an event's network source & destination. These field sets should _always_ be populated first.
* The `client.*` and `server.*` field sets should be _also_ be populated for added context if the event identifies those roles in the exchange.
> Expand definitions of source and destination field sets

- CHANGELOG.next.md
- code/go/ecs/destination.go
- code/go/ecs/source.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/destination.yml
- schemas/source.yml
- Expand definitions of source and destination field sets (#967)
> [1.x] Expand definitions of source and destination field sets (#967)

- CHANGELOG.next.md
- USAGE.md
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/README.md
- schemas/dns.yml
- schemas/process.yml
- schemas/rule.yml
- schemas/tls.yml
- scripts/schema/cleaner.py
- scripts/tests/unit/test_schema_cleaner.py
Adding a strict mode (`--strict`) check that requires array or object in `example` fields be enclosed with quotes (making strings). If these composite values are not handled as strings, YAML could incorrectly interpret them in generated artifacts or other downstream uses.
* Introduce new function, `schema.cleaner.check_example_value()`, to perform the type checking.
* Add supporting unit tests
* Update both `schemas/README.md` and `USAGE.md` documenting.
* Identified and fixed violating field examples in the schemas.
Closes #781
> Add example value composite type checking

- CHANGELOG.next.md
- Makefile
- USAGE.md
- scripts/generator.py
- scripts/generators/ecs_helpers.py
- scripts/schema/cleaner.py
- scripts/tests/unit/test_schema_cleaner.py
- Introduce `--strict` flag (#937)
> [1.x] Introduce `--strict` flag (#937)

- CHANGELOG.next.md
- USAGE.md
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/README.md
- schemas/dns.yml
- schemas/process.yml
- schemas/rule.yml
- schemas/tls.yml
- scripts/schema/cleaner.py
- scripts/tests/unit/test_schema_cleaner.py
- Add example value composite type checking (#966)
> [1.x] Add example value composite type checking (#966)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- docs/field-values.asciidoc
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
Add a new event category allowed value, `configuration`. The category is aimed at classifying configuration events from applications, processes, or systems.
* Any feedback on the description for `configuration`?
* I have added these allowed `event.types` as a starting point. Feedback welcome on additions or subtractions here:
```
- access
- change
- creation
- deletion
- info
```
Closes #799
> Add event category configuration

- CHANGELOG.next.md
- scripts/generators/beats.py
- scripts/generators/es_template.py
This PR adds the capability for custom schemas to define a `normalizer` for a specific `multi_field`.
Related: https://github.com/elastic/endpoint-package/pull/79
> Add normalizer multi-field capability

- CHANGELOG.next.md
- scripts/generators/beats.py
- scripts/generators/es_template.py
- Add normalizer multi-field capability (#971)
> [1.x] Add normalizer multi-field capability (#971)

- CHANGELOG.next.md
- docs/additional.asciidoc
- docs/using-mapping-network-events.asciidoc
- docs/using.asciidoc
- Add mapping network event guidance doc (#969)
> [1.x] Add mapping network event guidance doc (#969)

- docs/additional.asciidoc
Missed removing this asciidoc link on the `Additional Information` page for `ecs-mapping-network-events` when moving section underneath `Using ECS` in #969
> Removing unneeded link under `Additional Information`

- docs/additional.asciidoc
- Removing unneeded link under `Additional Information` (#984)
> [1.x] Removing unneeded link under `Additional Information` (#984)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- scripts/templates/field_details.j2
Add the `[discrete]` attribute to section headers in the `scripts/templates/field_details.j2` template file.
Adding `[discrete]` to the appropriate section headers in `docs/field-details.asciidoc` will keep the expected sections on the same pages once the asciidoctor chunking level is increased to support #988.
Relates to #943
> Add discrete attribute to field details page headers

- CHANGELOG.next.md
- docs/field-details.asciidoc
- scripts/templates/field_details.j2
- Add discrete attribute to field details page headers (#989)
> [1.x] Add discrete attribute to field details page headers (#989)

- CHANGELOG.next.md
- USAGE.md
- scripts/generator.py
- scripts/schema/oss.py
- scripts/tests/unit/test_schema_oss.py
ECS will soon start using basic data types. This flag will enable users to fall back to OSS types when possible, if they want to use ECS on purely OSS clusters.
> Add --oss flag to the ECS generator script

- CHANGELOG.next.md
- code/go/ecs/client.go
- code/go/ecs/destination.go
- code/go/ecs/server.go
- code/go/ecs/source.go
- code/go/ecs/url.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/client.yml
- schemas/destination.yml
- schemas/server.yml
- schemas/source.yml
- schemas/url.yml
- Uniformity across domain name breakdown fields (#981)
> [1.x] Uniformity across domain name breakdown fields (#981)

- rfcs/text/0001-wildcard-data-type.md
- rfcs/text/0001/agent.yml
- rfcs/text/0001/as.yml
- rfcs/text/0001/client.yml
- rfcs/text/0001/destination.yml
- rfcs/text/0001/dns.yml
- rfcs/text/0001/error.yml
- rfcs/text/0001/event.yml
- rfcs/text/0001/file.yml
- rfcs/text/0001/geo.yml
- rfcs/text/0001/host.yml
- rfcs/text/0001/http.yml
- rfcs/text/0001/log.yml
- rfcs/text/0001/organization.yml
- rfcs/text/0001/os.yml
- rfcs/text/0001/pe.yml
- rfcs/text/0001/process.yml
- rfcs/text/0001/registry.yml
- rfcs/text/0001/server.yml
- rfcs/text/0001/source.yml
- rfcs/text/0001/tls.yml
- rfcs/text/0001/url.yml
- rfcs/text/0001/user.yml
- rfcs/text/0001/user_agent.yml
- rfcs/text/0001/x509.yml
Revisions to the stage 1 wildcard adoption for consideration to be accepted as a stage 2 proposal.
The most significant addition is the list of fields which are the current candidates for `wildcard`. Discussion on any fields that should be added or removed is welcomed.
[Markdown preview of this RFC](https://github.com/ebeahan/ecs/blob/wildcard-rfc-stage-2/rfcs/text/0001-wildcard-data-type.md)
> [RFC] Wildcard - stage 2 proposal

- CHANGELOG.next.md
- USAGE.md
- scripts/generator.py
- scripts/schema/oss.py
- scripts/tests/unit/test_schema_oss.py
* Add --oss flag to the ECS generator script (#991)
> [1.x] Add --oss flag to the ECS generator script (#991)

- CHANGELOG.next.md
- code/go/ecs/network.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/network.yml
Adding these two values based on the discussion in #791.
I've only lightly modified the description to associate which values to use for host based, and which ones should be associated to perimeter based. Feedback welcome, if folks would like more adjustments to the description.
I think we should discuss whether this should be considered a breaking change. My opinion is that for folks that have dutifully been populating inbound/outbound, this will feel like a breaking change. On the other hand based on feedback so far, the usefulness of the field was hampered by the difficulty of using the same pair of values "depending on context". So I would lean towards getting this into ECS in the 1.x line, and not waiting for 2.0.
Closes #791
> Add network directions ingress and egress

- CHANGELOG.next.md
- code/go/ecs/network.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/network.yml
* Add network directions ingress and egress (#945)
> [1.x] Add network directions ingress and egress (#945)

- docs/converting.asciidoc
> Mention ECS Mapper in the main documentation

- docs/field-details.asciidoc
> [1.0][DOCS] Add discrete markers

- CHANGELOG.md
- CHANGELOG.next.md
> [1.x] Cut 1.7 changelog (#1010)

- CHANGELOG.md
- code/go/ecs/file.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/file.yml
It was only implicit via the example.
> Clarify that file extension should exclude the dot.

- CHANGELOG.md
- code/go/ecs/file.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/file.yml
* Clarify that file extension should exclude the dot. (#1016)
> [1.x] Clarify that file extension should exclude the dot. (#1016)

- CHANGELOG.md
- code/go/ecs/file.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/file.yml
* Clarify that file extension should exclude the dot. (#1016)
> [1.7] Clarify that file extension should exclude the dot. (#1016)

- CHANGELOG.md
- code/go/ecs/file.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/file.yml
* Clarify that file extension should exclude the dot. (#1016)
> [1.6] Clarify that file extension should exclude the dot. (#1016)

- CHANGELOG.next.md
- Makefile
- docs/usage/README.md
- scripts/generators/asciidoc_fields.py
- scripts/generators/ecs_helpers.py
- scripts/templates/field_details.j2
- scripts/tests/test_asciidoc_fields.py
Adds a free-text section to the ECS field reference docs for each fieldset, called `usage`. The `usage` directory will allow for any current ECS fieldset to have a paired usage document which will appear as a subsection in the ECS docs table of contents.
The ECS documentation book will add an additional level of chunking:
This additional, nested documentation page will only be added when a usage document is created for that particular field set.
* A new directory named `docs/usage` is being added and includes a `README.md` describing the intent and how-to for the usage asciidoc files.
* The `asciidoc_fields` generator will check the contents of `docs/usage` and create the necessary `include` statements in `docs/field-details.asciidoc`.
* No usage documentation is included; this PR focuses …
> Add usage docs section

- CHANGELOG.md
- Makefile
- docs/usage/README.md
- scripts/generators/asciidoc_fields.py
- scripts/generators/ecs_helpers.py
- scripts/templates/field_details.j2
- scripts/tests/test_asciidoc_fields.py
- Add usage docs section (#988)
> [1.x] Add usage docs section (#988)

- CHANGELOG.md
- Makefile
- docs/usage/README.md
- scripts/generators/asciidoc_fields.py
- scripts/generators/ecs_helpers.py
- scripts/templates/field_details.j2
- scripts/tests/test_asciidoc_fields.py
- Add usage docs section (#988)
> [1.7] Add usage docs section (#988)

- rfcs/text/0005-host-metric-fields.md
This PR is simply meant to set the merge date for this stage 1 document.
I forgot to do this when merging https://github.com/elastic/ecs/pull/950, a few days ago.
> Set the correct merge date for RFC 0005 stage 1

- CHANGELOG.next.md
- schemas/README.md
- scripts/generators/beats.py
- scripts/generators/es_template.py
- scripts/schema/cleaner.py
- scripts/tests/test_es_template.py
- scripts/tests/unit/test_schema_cleaner.py
This fixes #876 
Done quickly via GitHub web, but let me know if there are any additional changes required (e.g. tests or changelog).
> feat: include alias path when generating template

- CHANGELOG.next.md
- schemas/README.md
- scripts/generators/beats.py
- scripts/generators/es_template.py
- scripts/schema/cleaner.py
- scripts/tests/test_es_template.py
- scripts/tests/unit/test_schema_cleaner.py
- feat: include alias path when generating template (#877)
> [1.x] feat: include alias path when generating template (#877)

- CONTRIBUTING.md
Updates the `field_details.j2` link in the contributing doc to point to the correct location.
Location changed following the refactoring in #897.
> Update Jinja2 section to reflect template refactoring

- Makefile
This PR is also changing the order of the 'generate' task: it now starts with the new generator, then runs the legacy scripts.
After this, by default just running `make` will build all artifacts.
During active development, if a faster build is needed, `make generator` builds only the main artifacts.
> New default make task that generates main and experimental artifacts.

- CHANGELOG.next.md
- scripts/generators/beats.py
- scripts/generators/es_template.py
- scripts/schema/cleaner.py
- scripts/tests/test_es_template.py
- scripts/tests/unit/test_schema_cleaner.py
> Add support for `scaling_factor` in the generator

- USAGE.md
- experimental/README.md
Additional, documentation was added to `USAGE.md` demonstrating using `--include` with multiple target directories.
> Correct experimental usage example

- CHANGELOG.next.md
- docs/field-details.asciidoc
- docs/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
This PR adds the allowed value "registry" to `event.category`. It was brought up recently that Endpoint was already using this value.
This value was in previous discussions of categorization. It wasn't included in the initial release of categorization simply because we didn't have data sources that would use it at the time.
[Doc preview](https://ecs_1040.docs-preview.app.elstc.co/diff)
Closes #1019
> Add event.category registry

- CHANGELOG.next.md
- scripts/generators/beats.py
- scripts/generators/es_template.py
- scripts/schema/cleaner.py
- scripts/tests/test_es_template.py
- scripts/tests/unit/test_schema_cleaner.py
- Add support for `scaling_factor` in the generator (#1042)
> [1.x] Add support for `scaling_factor` in the generator (#1042)

- CHANGELOG.next.md
- scripts/schema/oss.py
- scripts/tests/unit/test_schema_oss.py
- Add fallback for constant_keyword (#1046)
> [1.x] Add fallback for constant_keyword (#1046)

- CHANGELOG.next.md
- scripts/cmd/gocodegen/gocodegen.go
- Add wildcard type support to go code generator (#1050)
> [1.x] Add wildcard type support to go code generator (#1050)

- CHANGELOG.md
- experimental/generated/elasticsearch/7/template.json
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/README.md
- scripts/generators/es_template.py
Logstash with ECS support creates a template that targets the index pattern `ecs-logstash-*`.
A user experimenting with our sample template (which previously targeted `ecs-*`) and using Logstash in ECS mode on the same cluster would likely have issues. Indeed, both templates would match their index name `ecs-logstash-*`.
I'm changing our sample template's pattern to `try-ecs-*`, which will avoid the above issue. It will also reinforce that when used as is, this template is appropriate for experimentation, more than production use.
I've added a bit of text in these instructions to better explain how to use this template, and where to go if users want to customize that template.
> Change the index pattern in the sample template.

- docs/products-solutions.asciidoc
This PR fixes a documentation link that will break when 7.10 becomes the `current` stack version. It conditionally changes the link location of the Log Monitoring page based on the stack version defined in github.com/elastic/docs ([here](https://github.com/elastic/docs/blob/master/shared/versions/stack/current.asciidoc)).
```asciidoc
ifeval::["{branch}"=="7.9"]
{logs-guide}/logs-app-overview.html[Log Monitoring]
endif::[]
ifeval::["{branch}"!="7.9"]
{observability-guide}/monitor-logs.html[Log Monitoring]
endif::[]
```
This ensures the link continues to work for users who click it before and after the 7.10 release.
Tested by building locally with `:branch:` overridden to `7.9`, `7.10`, and `master`.
This PR will need to be backported to `1.7`, `1.6`, `1.5`, `1.4`, `1.3`, and `1.x`. …
> Docs: Add ifeval to products page

- docs/using-getting-started.asciidoc
This PR fixes a documentation link that will break when 7.10 becomes the `current` stack version. It conditionally changes the link location of the Logs Monitoring Field Reference page based on the stack version defined in github.com/elastic/docs ([here](https://github.com/elastic/docs/blob/master/shared/versions/stack/current.asciidoc)).
```asciidoc
ifeval::["{branch}"=="7.9"]
{logs-guide}/logs-fields-reference.html[Log Monitoring Field Reference]
endif::[]
ifeval::["{branch}"!="7.9"]
{observability-guide}/logs-app-fields.html[Log Monitoring Field Reference]
endif::[]
```
This ensures the link continues to work for users who click it before and after the 7.10 release.
Tested by building locally with `:branch:` overridden to `7.9`, `7.10`, and `master`.
This PR will need to be backported …
> Docs: Add ifeval for 7.10 release

- docs/using-getting-started.asciidoc
* Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)
> [1.x] Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)

- docs/using-getting-started.asciidoc
* Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)
> [1.7] Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)

- docs/using-getting-started.asciidoc
* Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)
> [1.6] Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)

- docs/products-solutions.asciidoc
> [1.x] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)

- docs/products-solutions.asciidoc
> [1.7] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)

- docs/products-solutions.asciidoc
> [1.6] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)

- scripts/generators/asciidoc_fields.py
I made these changes locally but failed to include them in https://github.com/elastic/ecs/pull/1003.
These changes ensure any subsequent changes to the documentations will also include the `[discrete]` markers in the field details documentation section.
> [1.5] Add [discrete] headers to Asciidoc generator

- docs/field-values.asciidoc
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- Remove `expected_event_types` from protocol (#964)
> [1.6] Remove `expected_event_types` from protocol (#964)

- docs/using-getting-started.asciidoc
Backports the following commits to 1.5:
* Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)
> [1.5] Prepare link to Logs docs changing with the 7.10 release in "getting-started" (#1073)

- docs/products-solutions.asciidoc
Backports the following commits to 1.5:
> [1.5] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- docs/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- Add event.category session. (#1049)
> [1.x] Add event.category session. (#1049)

- docs/products-solutions.asciidoc
Backports the following commits to 1.4:
> [1.4] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)

- docs/products-solutions.asciidoc
Backports the following commits to 1.3:
> [1.3] Prepare link to Logs docs changing with the 7.10 release in "products-solutions" page (#1074)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- docs/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- Add event.category registry (#1040)
> [1.x] Add event.category registry (#1040)

- rfcs/text/0008-threat-intel.md
> [RFC] Cyber Threat Intelligence Fields Stage 1

- CHANGELOG.md
- USAGE.md
- scripts/generator.py
- scripts/generators/ecs_helpers.py
- scripts/schema/loader.py
- scripts/tests/test_ecs_helpers.py
- scripts/tests/unit/test_schema_loader.py
When `--ref` argument is set and the `experimental/schemas` directory is loaded with `--include`, these changes ensure the experimental field definitions are pulling from the target git ref and not the local file system.
`--ref` is restricted to loading the field definitions from the `schemas` directory. Custom field definition can be supplied but will always load from the local file system. This works well for users managing independent custom definitions outside of the ECS field definitions.
The `experimental/schemas` directory was introduced to hold ECS field definition changes considered experimental, but not beta or GA. Users can use `--include experimental/schemas` if they wish to generate artifacts using these experimental fields.
A problem is introduced if a user wishes to …
> Add --ref support for experimental artifacts

- CHANGELOG.md
- USAGE.md
- scripts/generator.py
- scripts/generators/ecs_helpers.py
- scripts/schema/loader.py
- scripts/tests/test_ecs_helpers.py
- scripts/tests/unit/test_schema_loader.py
- Add --ref support for experimental artifacts (#1063)
> [1.x] Add --ref support for experimental artifacts (#1063)

- CHANGELOG.md
- USAGE.md
- scripts/generator.py
- scripts/generators/ecs_helpers.py
- scripts/schema/loader.py
- scripts/tests/test_ecs_helpers.py
- scripts/tests/unit/test_schema_loader.py
- Add --ref support for experimental artifacts (#1063)
> [1.7] Add --ref support for experimental artifacts (#1063)

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/schemas/event.yml
- rfcs/text/0001/event.yml
While testing the experimental build artifacts, I discovered the generated experimental ES index templates will not install.
Elasticsearch returns a HTTP 400 error when attempting to install the generated ES index template:
```
curl -XPUT -H "Content-Type: application/json" http://localhost:9200/_template/test -d @experimental/generated/elasticsearch/7/template.json 
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"The field [original] cannot have index = false"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: The field [original] cannot have index = false","caused_by":{"type":"mapper_parsing_exception","reason":"The field [original] cannot have index = false"}},"status":400}
```
~Set `index: true` in the experimental schema for …
> Remove experimental event.original definition

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/schemas/event.yml
- Remove experimental event.original definition (#1053)
> [1.x] Remove experimental event.original definition (#1053)

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/schemas/event.yml
- Remove experimental event.original definition (#1053)
> [1.7] Remove experimental event.original definition (#1053)

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/schemas/process.yml
Addresses issue noted originally in https://github.com/elastic/ecs/pull/1098#issuecomment-724783960.
> Add missing `process.thread.name` to experimental definitions

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/schemas/process.yml
- Add missing `process.thread.name` to experimental definitions (#1103)
> [1.x] Add missing `process.thread.name` to experimental definitions (#1103)

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/schemas/process.yml
- Add missing `process.thread.name` to experimental definitions (#1103)
> [1.7] Add missing `process.thread.name` to experimental definitions (#1103)

- rfcs/text/0007-multiple-users.md
Stage 3 criteria:
- Completed field definitions
- This was done in the stage 2 PR, with the help of many contributors ❤️ 
- Please let us know if you think an important usage example is missing
Additional TODOs
[Preview of the RFC](https://github.com/webmat/ecs/blob/rfc/0007/stage-3/rfcs/text/0007-multiple-users.md)
> [RFC] Multiple users in an event, stage 3 PR

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- schemas/README.md
- scripts/schema/cleaner.py
- scripts/tests/unit/test_schema_cleaner.py
Elasticsearch will reject an index template that contains a wildcard field with the `index` parameter. This change removes the `index` parameter entirely from any `wildcard` field.
Wildcard requires that the field be indexed. If the `index` parameter is present at all, even `index: true`, Elasticsearch will reject the template as of Elasticsearch 7.10.0.
Closes #1113
> Remove index parameter for wildcard fields

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- schemas/README.md
- scripts/schema/cleaner.py
- scripts/tests/unit/test_schema_cleaner.py
- Remove index parameter for wildcard fields (#1115)
> [1.x] Remove index parameter for wildcard fields (#1115)

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- schemas/README.md
- scripts/schema/cleaner.py
- scripts/tests/unit/test_schema_cleaner.py
- Remove index parameter for wildcard fields (#1115)
> [1.7] Remove index parameter for wildcard fields (#1115)

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/schemas/dns.yml
Implements the workaround identified in #1116, which prevents the `dns.answer` object from being omitted when merging the experimental field definitions.
> Add dns.answer object into experimental schema

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/schemas/dns.yml
- Add dns.answer object into experimental schema (#1118)
> [1.x] Add dns.answer object into experimental schema (#1118)

- CHANGELOG.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/schemas/dns.yml
- Add dns.answer object into experimental schema (#1118)
> [1.7] Add dns.answer object into experimental schema (#1118)

- CHANGELOG.md
- code/go/ecs/x509.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/x509.yml
> Clarify x509 definition guidance for network events with only one cert

- CHANGELOG.md
- code/go/ecs/x509.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/x509.yml
* Clarify x509 definition guidance for network events with only one cert (#1114)
> [1.x] Clarify x509 definition guidance for network events with only one cert (#1114)

- CHANGELOG.md
- code/go/ecs/x509.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/x509.yml
* Clarify x509 definition guidance for network events with only one cert (#1114)
> [1.7] Clarify x509 definition guidance for network events with only one cert (#1114)

- CHANGELOG.next.md
- code/go/ecs/os.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/os.yml
* Add os.type field, with list of allowed values (#1111)
> [1.x] Add os.type field, with list of allowed values (#1111)

- CHANGELOG.next.md
- scripts/generators/es_template.py
- scripts/tests/test_es_template.py
This PR adds support for setting the `value` parameter for `constant_keyword` fields.
The PR right now only lets the parameter through to the ES templates, but not the Beats field definitions. This is intentional, as ECS cannot logically set the type of some fields to `constant_keyword` on the behalf of Beats. This would have to be an override on the Beats side, according to the relevant indexing strategy.
Closes #1052
> Add support for constant_keyword's 'value' parameter

- CHANGELOG.next.md
- scripts/generators/es_template.py
- scripts/tests/test_es_template.py
* Add support for constant_keyword's 'value' parameter (#1112)
> [1.x] Add support for constant_keyword's 'value' parameter (#1112)

- CHANGELOG.next.md
- schemas/README.md
- scripts/generators/asciidoc_fields.py
- scripts/generators/ecs_helpers.py
- scripts/schema/cleaner.py
- scripts/schema/finalizer.py
- scripts/templates/field_details.j2
- scripts/tests/unit/test_schema_finalizer.py
Introduces a new key, `beta`, which when set to `True` designates a field as being in `beta` support in the ECS field reference documentation.
Fields introduced in RFCs which have advanced to [stage three](https://elastic.github.io/ecs/stages.html) are to be committed to the schema as beta. The "beta" label should appear in the ECS docs next to any fields which are in beta.
The ECS field definitions need an option to specify if a field is currently considered `beta`. Once an RFC advances to stage four, the beta label will be removed by removing the beta option from the field's definition.
A field can be marked as beta by specifying the `beta` option:
```yaml
- name: executable
level: extended
type: keyword
beta: True
description: >
Absolute path to the process executable.
example: …
```
> Beta label support

- CHANGELOG.next.md
- schemas/README.md
- scripts/generators/asciidoc_fields.py
- scripts/generators/ecs_helpers.py
- scripts/schema/cleaner.py
- scripts/schema/finalizer.py
- scripts/templates/field_details.j2
- scripts/tests/unit/test_schema_finalizer.py
> [1.x] Beta label support (#1051)

- docs/using-getting-started.asciidoc
This PR is a follow-up to https://github.com/elastic/ecs/pull/1073 and:
- removes the `ifeval` that fixed potential broken links when 7.10 became the `current` stack version.
- adds an additional link to the [Metrics Monitoring Field Reference](https://www.elastic.co/guide/en/observability/current/metrics-app-fields.html) in the Observability Guide.
This PR will need to be backported to `1.7`, `1.6`, `1.5`, and `1.x`.
> Docs: Remove ifeval from getting-starting

- docs/products-solutions.asciidoc
This PR is a follow-up to https://github.com/elastic/ecs/pull/1074 and: 
- removes the `ifeval` that fixed potential broken links when 7.10 became the `current` stack version.
- adds an additional link to [Metrics Monitoring](https://www.elastic.co/guide/en/observability/current/analyze-metrics.html) in the Observability Guide.
This PR will need to be backported to `1.7`, `1.6`, `1.5`, `1.4`, `1.3`, and `1.x`.
> Docs: Remove ifeval from products page

- docs/products-solutions.asciidoc
- docs/using-getting-started.asciidoc
* Remove temporary ifeval in "getting started" page, add link to Metrics docs (#1134)
> [1.x] Backport #1134 and #1135

- docs/products-solutions.asciidoc
- docs/using-getting-started.asciidoc
* Remove temporary ifeval in "getting started" page, add link to Metrics docs (#1134)
> [1.7] Backport #1134 and #1135

- docs/products-solutions.asciidoc
- docs/using-getting-started.asciidoc
* Remove temporary ifeval in "getting started" page, add link to Metrics docs (#1134)
> [1.6] Backport #1134 and #1135

- docs/products-solutions.asciidoc
- docs/using-getting-started.asciidoc
* Remove temporary ifeval in "getting started" page, add link to Metrics docs (#1134)
> [1.5] Backport #1134 and #1135

- docs/products-solutions.asciidoc
Backports the following commits to 1.4:
> [1.4] Remove temporary ifeval from products page, add link to Metrics (#1135)

- docs/products-solutions.asciidoc
Backports the following commits to 1.3:
> [1.3] Remove temporary ifeval from products page, add link to Metrics (#1135)

- .github/ISSUE_TEMPLATE/schema-changes-additions.md
- .github/ISSUE_TEMPLATE/schema-issue.md
The goal of this PR is for the wording of the two issue types to better guide contributors to the normal suggestions/issues vs reporting problems.
The previous wording had most folks click "Schema Issue" which sounds innocuous, but would be labelled "bug" :-)
> Adjust issue templates

- docs/converting.asciidoc
Closes #1129
[Doc Preview](https://ecs_1146.docs-preview.app.elstc.co/guide/en/ecs/master/ecs-converting.html)
> Remove an incorrect `event.type` from the 'converting' guide

- docs/products-solutions.asciidoc
The ECS compatibility mode was introduced in 7.9.
[Doc Preview](https://ecs_1147.docs-preview.app.elstc.co/guide/en/ecs/master/ecs-products-solutions.html)
> Mention Logstash support for ECS in the 'products' page

- docs/converting.asciidoc
- docs/products-solutions.asciidoc
* Remove an incorrect `event.type` from the 'converting' page (#1146)
* Mention Logstash support for ECS in the 'products' page (#1147)
> Two small documentation backports

- code/go/ecs/url.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/url.yml
This adjustment is meant to match the improved guidance on `file.extension` we introduced in #1016.
I think we should backport this to 1.7 for it to be reflected in current docs. This guidance was already present in the description for `url.extension`, just not as obvious. It was in the long description, but not in the short description.
> Reinforce the exclusion of the leading dot from url.extension

- code/go/ecs/url.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/url.yml
* Reinforce the exclusion of the leading dot from url.extension (#1151)
> [1.x] Reinforce the exclusion of the leading dot from url.extension (#1151)

- code/go/ecs/url.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/url.yml
* Reinforce the exclusion of the leading dot from url.extension (#1151)
> [1.7] Reinforce the exclusion of the leading dot from url.extension (#1151)

- rfcs/text/0008-email.md
> [RFC] E-Mail

- CHANGELOG.next.md
- code/go/ecs/tracing.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/tracing.yml
This understandable misunderstanding comes up every so often, so let's get that notice in :-)
[Doc preview of the change](https://ecs_1162.docs-preview.app.elstc.co/guide/en/ecs/master/ecs-tracing.html)
> Add notice to the tracing field set, about not nesting field names.

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- generated/beats/fields.ecs.yml
- scripts/generators/beats.py
The `fields.ecs.yml` artifact was erroneously adding the [tracing](https://www.elastic.co/guide/en/ecs/current/ecs-tracing.html) fields into a `tracing` object.
Like `base` fields, the `tracing` fields should exist at the top-level and require special handling when generating the template.
Closes #1163
> Tracing fields should be at top level in Beats artifact

- CHANGELOG.next.md
- code/go/ecs/tracing.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/tracing.yml
- scripts/generators/beats.py
* Add notice to the tracing field set, about not nesting field names. (#1162)
* Tracing fields should be at top level in Beats artifact (#1164)
> [1.x] Tracing fields should be at the root

- CHANGELOG.next.md
- code/go/ecs/tracing.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/tracing.yml
- scripts/generators/beats.py
* Add notice to the tracing field set, about not nesting field names. (#1162)
* Tracing fields should be at top level in Beats artifact (#1164)
> [1.7] Tracing fields should be at the root

- CHANGELOG.next.md
- code/go/ecs/url.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/url.yml
Detail that the `[` and `]` characters may enclose a literal IPv6 address populating `url.domain`.
The current `url.domain` field description doesn't have guidance for this case (e.g. https://github.com/elastic/elasticsearch/pull/65150#discussion_r525635429). The format is defined in [RFC 2732](https://www.ietf.org/rfc/rfc2732.txt) and has been adopted by the major web browsers.
Example:
* Literal IPv6 address: `FEDC:BA98:7654:3210:FEDC:BA98:7654:3210`
* Formatted in a URL: `http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]/index.html`
> Usage of brackets for a URL containing IPv6 address

- CHANGELOG.next.md
- code/go/ecs/url.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/url.yml
- Usage of brackets for a URL containing IPv6 address (#1131)
> [1.x] Usage of brackets for a URL containing IPv6 address (#1131)

- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/schemas/host.yml
This PR adds the host metric fields from [RFC 0005](https://github.com/elastic/ecs/blob/master/rfcs/text/0005-host-metric-fields.md) (#1028) to the experimental artifacts.
> Stage 2 changes for RFC 0005 (host metrics)

- CHANGELOG.next.md
- scripts/generators/es_template.py
- scripts/tests/test_es_template.py
Adds logic when generating the 6.x index template artifact to fallback on a compatible type if one exists. Soon, ECS fields will begin using data types introduced in Elasticsearch 7.x, and this change will ensure the ES 6 template will only use types available in 6.x.
The first considered approach was reusing the `--oss` fallback mechanism to generate a second, 6.x-compatible copy of the `fields` object. However, the OSS-fallback takes place much earlier in the chain and would have required a copy of the `fields` objects to go through the identical chain of steps as the original `fields` object.
Next, I looked at incorporating a function to pass along to `visitor.visit_fields` from `generators.es_template`, but `es_template` uses the `flat` representation incompatible with …
> 6.x index template data type fallback

- CHANGELOG.next.md
- scripts/generators/es_template.py
- scripts/tests/test_es_template.py
- 6.x index template data type fallback (#1171)
> [1.x] 6.x index template data type fallback (#1171)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- docs/usage/user.asciidoc
- experimental/generated/ecs/ecs_nested.yml
- experimental/schemas/user.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/user.yml
* Apply RFC 0007 stage 3 changes - multi-user (#1066)
Conflict: deleted file `rfcs/text/0007-multiple-users.md` as RFCs are not backported to version branches.
> [1.x] Apply RFC 0007 stage 3 changes - multi-user (#1066)

- CHANGELOG.next.md
- scripts/generators/es_template.py
`error.stack_trace` needs special handling to re-add `index: false` and `doc_values: false` after the type fallback when the Elasticsearch 6.x legacy index template is generated.
Adding the logic to `generate_template_version` simplified the implementation, but to unit test would require investing additional time into mocking the file write at the end of the function. I opted not to invest that time now, but it is something I'd like to revisit.
> Handle `error.stack_trace` case for ES 6.x template

- CHANGELOG.next.md
- scripts/generators/es_template.py
- Handle `error.stack_trace` case for ES 6.x template (#1176)
> [1.x] Handle `error.stack_trace` case for ES 6.x template (#1176)

- CHANGELOG.next.md
- experimental/generated/elasticsearch/7/template.json
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/agent.json
- generated/elasticsearch/component/client.json
- generated/elasticsearch/component/destination.json
- generated/elasticsearch/component/dll.json
- generated/elasticsearch/component/dns.json
- generated/elasticsearch/component/error.json
- generated/elasticsearch/component/file.json
- generated/elasticsearch/component/host.json
- generated/elasticsearch/component/http.json
- generated/elasticsearch/component/log.json
- generated/elasticsearch/component/observer.json
- generated/elasticsearch/component/organization.json
- generated/elasticsearch/component/process.json
- generated/elasticsearch/component/registry.json
- generated/elasticsearch/component/server.json
- generated/elasticsearch/component/source.json
- generated/elasticsearch/component/tls.json
- generated/elasticsearch/component/url.json
- generated/elasticsearch/component/user.json
- generated/elasticsearch/component/user_agent.json
- scripts/generators/es_template.py
This fixes an issue introduced by #1156, discovered in #1180. Composable templates support `_meta` at the template's root, but legacy templates don't. So we're just putting it back inside the mappings for legacy templates.
This also fixes missing updates to the component template, after the introduction of wildcard in #1098.
> Move _meta section back inside mappings, in legacy templates.

- CHANGELOG.next.md
- experimental/generated/elasticsearch/7/template.json
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- scripts/generators/es_template.py
* Move _meta section back inside mappings, in legacy templates. (#1186)
> [1.x] Move _meta section back inside mappings, in legacy templates. (#1186)

- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/host.json
- experimental/schemas/host.yml
- Apply the RFC 0005 stage 2 (host metrics) changes in the experimental artifacts (#1159)
> [1.x] Apply the RFC 0005 stage 2 (host metrics) changes in the experimental artifacts (#1159)

- scripts/generators/es_template.py
Address two bugs in `es_template.template_settings`:
* `error.stack_trace` handling from #1176 caused a `KeyError` exception when `properties.error.properties.stack_trace` wasn't present in the loaded mappings.
* `_meta` handling from #1186 caused a `KeyError` exception when a user-supplied template settings file doesn't include `_meta`. 
Closes #1190
> Conditional handling in es_template.template_settings

- scripts/generators/es_template.py
- Conditional handling in es_template.template_settings (#1191)
> [1.x] Conditional handling in es_template.template_settings (#1191)

- scripts/generators/es_template.py
* Conditional handling in es_template.template_settings (#1191)
> [1.7] Conditional handling in es_template.template_settings (#1191)

- CHANGELOG.next.md
- docs/additional.asciidoc
- docs/artifacts.asciidoc
- docs/index.asciidoc
- docs/using-conventions.asciidoc
Add a docs page that describes and links to the experimental artifacts maintained on GitHub. 
Describes the artifacts in general versus solely the index templates artifacts. Open to discussion if we should adjust.
[Docs preview link](https://ecs_1189.docs-preview.app.elstc.co/diff)
Closes #1030
> Artifacts docs page

- CHANGELOG.next.md
- docs/field-values.asciidoc
- scripts/templates/field_values.j2
As part of bringing the ECS categorization fields to GA (#942), remove the `beta` warning label from the categorization fields documentation.
[Docs Preview](https://ecs_1067.docs-preview.app.elstc.co/diff)
> Remove beta warning label from categorization fields docs

- CHANGELOG.next.md
- docs/field-values.asciidoc
- scripts/templates/field_values.j2
- Remove beta warning label from categorization fields docs (#1067)
> [1.x] Remove beta warning label from categorization fields docs (#1067)

- CHANGELOG.next.md
- code/go/ecs/event.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
Minor typo spotted while reviewing the field definition.
Open to input if my adjustment doesn't best capture the intent.
> Correct wording of `event.reference` description

- CHANGELOG.next.md
- code/go/ecs/event.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- Correct wording of `event.reference` description (#1181)
> [1.x] Correct wording of `event.reference` description (#1181)

- CHANGELOG.next.md
* Cut 1.8 FF changelog.next.md #1199
> [1.x] Cut 1.8 FF changelog.next.md #1199

- CHANGELOG.next.md
* Cut 1.8 FF changelog.next.md #1199
> [master] Cut 1.8 FF changelog.next.md (#1199)

- rfcs/text/0009-data_stream-fields.md
- rfcs/text/0009/data_stream.yml
Moving this to stage 2
[Preview the RFC](https://github.com/roncohen/ecs/blob/data_streams_stage_2/rfcs/text/0009-data_stream-fields.md)
> [RFC] wip: data_stream - stage 2

- CHANGELOG.next.md
- code/go/ecs/http.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/http.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/http.json
- schemas/http.yml
It is very common for web servers to generate a unique id for all incoming requests.  For example, [heroku](https://devcenter.heroku.com/articles/http-request-id) standardizes this in `X-Request-ID`.  Elastic APM Server itself has assigned unique request ids since v6.2.
This information is useful for analyzing per-request logs.
> add http.request.id

- CHANGELOG.next.md
- scripts/schema/loader.py
- scripts/tests/unit/test_schema_loader.py
* Merge custom and core multi_fields arrays (#982)
> [1.x] Merge custom and core multi_fields arrays (#982)

- CHANGELOG.next.md
- scripts/schema/loader.py
- scripts/tests/unit/test_schema_loader.py
Backports the following commits to 1.8:
* Merge custom and core multi_fields arrays (#982)
> [1.8] Merge custom and core multi_fields arrays (#982)

- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/data_stream.json
- experimental/generated/elasticsearch/template.json
- experimental/schemas/data_stream.yml
Adding the `data_stream` fields from [RFC 0009](https://github.com/elastic/ecs/blob/master/rfcs/text/0009-data_stream-fields.md) (#1145) to the experimental artifacts.
> Stage 2 changes for RFC 0009 - data_stream fields

- CHANGELOG.next.md
- code/go/ecs/cloud.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/cloud.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/cloud.json
- schemas/cloud.yml
~`cloud.platform`~ `cloud.service.name` is intended to distinguish services running on different platforms within a provider.  For example, it is important to know if an application is running on EC2 or under Lambda though both are within AWS so that contextual information about cold starts can be displayed.  This isn't limited to serverless, for example Azure VM vs App Service vs Function enables greater insight into deployed infrastructure inventory.
> add cloud.service.name

- CHANGELOG.next.md
- code/go/ecs/http.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/http.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/http.json
- schemas/http.yml
> [1.x] add http.request.id (#1208)

- CHANGELOG.next.md
- code/go/ecs/hash.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/dll.json
- experimental/generated/elasticsearch/component/file.json
- experimental/generated/elasticsearch/component/process.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/dll.json
- generated/elasticsearch/component/file.json
- generated/elasticsearch/component/process.json
- schemas/hash.yml
> [1.x] Add ssdeep hash (#1169)

- USAGE.md
Updates to `USAGE.md` to indicate the `--oss` flag is now deprecated.
> Mark --oss as deprecated

- rfcs/text/0001-wildcard-data-type.md
Due to performance concerns, the wildcard RFC is being rolled back to stage one.
We'll continue to iterate on the proposal with a focus on performance implications to ensure we can move forward with this important change with the schema as soon as is practical.
> [RFC] Roll back wildcard migration to stage one

- CHANGELOG.next.md
- scripts/cmd/gocodegen/gocodegen.go
When a field uses `type: scaled_float` in the field definitions, `make` fails due to `scaled_float` not being a defined data type in `go` generator:
```
$ make
build/ve/bin/python scripts/generator.py --strict --include ""
Loading schemas from local files
Running generator. ECS version 2.0.0-dev
build/ve/bin/python scripts/use-cases.py --stdout=true >> /dev/null
find code/go/ecs -name '*.go' -not -name 'doc.go' | xargs rm
cd scripts \
&& GO111MODULE=on go run cmd/gocodegen/gocodegen.go \
-version=2.0.0-dev \
-schema=../schemas \
-out=../code/go/ecs
no translation for scaled_float (field cpu.usage)
exit status 1
make: *** [gocodegen] Error 1
```
This fix adds a type mapping for `scaled_float`.
I'll plan on backporting to 1.8 as well.
> Add scaled_float type to go generator

- CHANGELOG.next.md
- scripts/cmd/gocodegen/gocodegen.go
- Add scaled_float type to go generator (#1250)
> [1.x] Add scaled_float type to go generator (#1250)

- CHANGELOG.next.md
- scripts/cmd/gocodegen/gocodegen.go
Backports the following commits to 1.8:
- Add scaled_float type to go generator (#1250)
> [1.8] Add scaled_float type to go generator (#1250)

- docs/field-values-usage.asciidoc
- docs/field-values.asciidoc
- rfcs/text/0012-orchestrator-field-set.md
- scripts/templates/field_values.j2
Adds a new documentation section, `Using the Categorization Fields`, that contains guidance for using the four ECS categorization fields together to classify real-world example events.
Help those implementing ECS to use the event categorization fields more consistently.
While originally considered adding fields into the field definitions to provide examples, the approach felt too restrictive to capture more subtle or nuanced context. I instead opted for a new page, `docs/field-values-usage.asciidoc`, with an `include` directive to add the new content to the existing `ECS Categorization Fields` section.
After the section introduction, I captured some of the categorization usage principles from the public [ECS categorization doc](https://docs.google.com/document/d/1TxpruDWAfd_5JavWyjpPEia4nM …
> Add categorization fields usage docs

- CHANGELOG.next.md
- code/go/ecs/geo.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/client.json
- experimental/generated/elasticsearch/component/destination.json
- experimental/generated/elasticsearch/component/host.json
- experimental/generated/elasticsearch/component/observer.json
- experimental/generated/elasticsearch/component/server.json
- experimental/generated/elasticsearch/component/source.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/client.json
- generated/elasticsearch/component/destination.json
- generated/elasticsearch/component/host.json
- generated/elasticsearch/component/observer.json
- generated/elasticsearch/component/server.json
- generated/elasticsearch/component/source.json
- schemas/geo.yml
Add three new fields to the ECS `geo.*` fieldset:
* `geo.timezone`
* `geo.postal_code`
* `geo.continent_code`
These fields will allow for additional geolocation context on events. Like the other `geo.*` fields, these values can be populated by automatically by GeoIP enrichment or manually by the user.
* I originally chose `time_zone` over `timezone`. However, reviewing existing geoip implementations ([[0](https://www.elastic.co/guide/en/elasticsearch/reference/master/geoip-processor.html)], [[1](https://github.com/logstash-plugins/logstash-filter-geoip/blob/master/src/main/java/org/logstash/filters/Fields.java)]), opted for `timezone`.
* Considered explicitly listing the seven two-letter continent codes in the description as used by other sources. However, despite other sources …
> add time_zone, postal_code, and continent_code

- CHANGELOG.next.md
- code/go/ecs/geo.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/client.json
- experimental/generated/elasticsearch/component/destination.json
- experimental/generated/elasticsearch/component/host.json
- experimental/generated/elasticsearch/component/observer.json
- experimental/generated/elasticsearch/component/server.json
- experimental/generated/elasticsearch/component/source.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/client.json
- generated/elasticsearch/component/destination.json
- generated/elasticsearch/component/host.json
- generated/elasticsearch/component/observer.json
- generated/elasticsearch/component/server.json
- generated/elasticsearch/component/source.json
- schemas/geo.yml
- add time_zone, postal_code, and continent_code (#1229)
> [1.x] add time_zone, postal_code, and continent_code (#1229)

- CHANGELOG.next.md
- code/go/ecs/client.go
- code/go/ecs/destination.go
- code/go/ecs/host.go
- code/go/ecs/observer.go
- code/go/ecs/server.go
- code/go/ecs/source.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/host.yml
- schemas/observer.yml
- schemas/server.yml
- schemas/source.yml
Reasons for choosing this format:
* IEEE 802 uses this format: https://en.wikipedia.org/wiki/MAC_address#Notational_conventions
* IETF uses this format: https://tools.ietf.org/html/rfc7042
It is not yet clear if we should prefer upper or lowercase. I just went with uppercase for now because that is what the references above use.
Reason for choosing 00-00-5E-00-53-23:
It is in the range of unicast MAC addresses reserved for documentation as specified by: https://tools.ietf.org/html/rfc7042#section-2.1.2
Note that I did not update generated files because my development machine is not fully setup. Maybe you can update them real quick before merging? Thanks.
> Specify MAC address format like this example 00-00-5E-00-53-23

- CHANGELOG.next.md
- code/go/ecs/client.go
- code/go/ecs/destination.go
- code/go/ecs/host.go
- code/go/ecs/observer.go
- code/go/ecs/server.go
- code/go/ecs/source.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/host.yml
- schemas/observer.yml
- schemas/server.yml
- schemas/source.yml
- Specify MAC address format (#456)
> [1.x] Specify MAC address format (#456)

- CHANGELOG.md
- CHANGELOG.next.md
> [1.x] Cut 1.8 changelog #1262

- CHANGELOG.md
- CHANGELOG.next.md
> [master] Cut 1.8 changelog #1262

- rfcs/text/0007-multiple-users.md
Update the multiple users RFC proposal's stage to align with new RFC [proposal stages](https://elastic.github.io/ecs/stages.html).
> [RFC] Multiple Users - Update to align with new proposal stages

- CHANGELOG.next.md
- code/go/ecs/code_signature.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/dll.json
- experimental/generated/elasticsearch/component/file.json
- experimental/generated/elasticsearch/component/process.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/dll.json
- generated/elasticsearch/component/file.json
- generated/elasticsearch/component/process.json
- schemas/code_signature.yml
- Add 2 fields to code_signature (#1269)
> [1.x] Add 2 fields to code_signature (#1269)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_nested.yml
- schemas/user.yml
Remove the `beta` attribute in the schema and the ECS docs for the multiple users reuses from [RFC 0007](https://github.com/elastic/ecs/blob/master/rfcs/text/0007-multiple-users.md):
* `user.effective.*`
* `user.changes.*`
* `user.target.*`
The RFC has advanced to stage 3 (https://github.com/elastic/ecs/pull/1239) as is considered finished. By removing `beta`, these fields will be GA.
> Stage 3 changes for RFC 0007 - remove beta attribute

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_nested.yml
- schemas/user.yml
- Stage 3 changes for RFC 0007 - remove beta attribute (#1271)
> [1.x] Stage 3 changes for RFC 0007 - remove beta attribute (#1271)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/file.json
- experimental/generated/elasticsearch/component/process.json
- experimental/schemas/elf.yml
Adding `elf.*` fieldset from [RFC 0015](https://github.com/elastic/ecs/blob/master/rfcs/text/0015-create-file-elf.md) (https://github.com/elastic/ecs/pull/1077) to the experimental schema and artifacts.
For reviewers, the bulk of the changes are located in `experimental/schemas/elf.yml`. Most files are generated automatically based on files in `experimental/schemas`.
> Stage 1 changes for RFC 0015 - add elf fieldset

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/file.json
- experimental/generated/elasticsearch/component/process.json
- experimental/schemas/elf.yml
- Stage 1 changes for RFC 0015 - add elf fieldset (#1261)
> [1.x] Stage 1 changes for RFC 0015 - add elf fieldset (#1261)

- CHANGELOG.next.md
* Cut 1.9 FF CHANGELOG.next.md #1277
> [1.x] Cut 1.9 FF CHANGELOG.next.md (#1277)

- .github/workflows/test.yml
Current Github action config allows `go` version to update the minor, which was causing [unexpected errors](https://github.com/elastic/ecs/pull/1230#issuecomment-787019042) when CI runs `make check`.
This change will lock the `go-version` at `1.15`.
> Set go version to 1.15.x in tests 

- .github/workflows/test.yml
- lock go version in actions (#1283)
> [1.x] lock go version in actions (#1283)

- .github/workflows/test.yml
Backports the following commits to 1.9:
- lock go version in actions (#1283)
> [1.9] lock go version in actions (#1283)

- rfcs/text/0012-orchestrator-field-set.md
- rfcs/text/0012/orchestrator.yml
Moving the orchestrator RFC from stage 0 into stage 1
[Preview of markdown proposal](https://github.com/ferozsalam/ecs/blob/stage-1-orchestrator-rfc/rfcs/text/0012-orchestrator-field-set.md)
> Stage 1 Orchestrator RFC

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/orchestrator.json
- experimental/generated/elasticsearch/template.json
- experimental/schemas/orchestrator.yml
Adds `orchestrator.*` fieldset from [RFC 0012](https://github.com/elastic/ecs/blob/master/rfcs/text/0012-orchestrator-field-set.md) (https://github.com/elastic/ecs/pull/1230) to the experimental schema and artifacts.
> Stage 1 experimental changes for RFC 0012 - orchestrator fieldset

- rfcs/text/0000-target-process.md
- rfcs/text/0016-target-process.md
Related to #678 
Started an RFC to model target processes as `process.target.*`
> Add RFC for source/target process modeling

- rfcs/text/0009-data_stream-fields.md
- rfcs/text/0009/data_stream.yml
Criteria for consideration for this stage:
> Data Stream fields: Move to stage 3

- rfcs/text/0009-data_stream-fields.md
In addition to correcting the advancement date:
* Added the stage 3 PR link
* Added an additional reference to the Elasticsearch data stream naming docs.
> Correct advancement date for RFC 0009 Stage 3

- CHANGELOG.next.md
- scripts/cmd/gocodegen/gocodegen.go
Separating implementation of `flattened` type into the go code generator from #1254. I believe `flattened` should be a more straight-forward change.
Opted to use `string` since `flattened` fields do not support defining sub-fields like other object types, such as `object` or `nested`.
> Add flattened type support to Go code generator

- CHANGELOG.next.md
- scripts/cmd/gocodegen/gocodegen.go
- Add flattened type support to Go code generator (#1302)
> [1.x] Add flattened type support to Go code generator (#1302)

- CHANGELOG.next.md
- scripts/requirements.txt
Backports the following commits to 1.9:
- Bump jinja2 from 2.11.2 to 2.11.3 in /scripts (#1310)
> [1.9] Bump jinja2 from 2.11.2 to 2.11.3 in /scripts (#1310)

- CHANGELOG.next.md
- scripts/requirements.txt
- Bump jinja2 from 2.11.2 to 2.11.3 in /scripts (#1310)
> [1.x] Bump jinja2 from 2.11.2 to 2.11.3 in /scripts (#1310)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/host.yml
This PR advances the host metric fields from [RFC 0005](https://github.com/elastic/ecs/blob/master/rfcs/text/0005-host-metric-fields.md) (#1316) from beta to GA in the ECS documentation.
> Stage 3 changes for RFC 0005 (host metrics)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/host.yml
- Stage 3 changes for RFC 0005 (host metrics) (#1319)
> [1.x] Stage 3 changes for RFC 0005 (host metrics) (#1319)

- CHANGELOG.next.md
- scripts/requirements.txt
- Bump pyyaml from 5.3b1 to 5.4 in /scripts (#1318)
> [1.x] Bump pyyaml from 5.3b1 to 5.4 in /scripts (#1318)

- CHANGELOG.next.md
- scripts/requirements.txt
Backports the following commits to 1.9:
- Bump pyyaml from 5.3b1 to 5.4 in /scripts (#1318)
> [1.9] Bump pyyaml from 5.3b1 to 5.4 in /scripts (#1318)

- rfcs/text/0012-orchestrator-field-set.md
Progress the Orchestrator RFC to Stage 2.
I have made an attempt to identify anything that will need updating if when the RFC process for this is complete, but I expect those with more familiarity with the entire Elastic stack will have a better idea!
Any additional concerns around the fieldset are also welcome.
> Stage 2 Orchestrator RFC

- CHANGELOG.md
- CHANGELOG.next.md
> [master] Cut 1.9 changelog (#1328)

- CHANGELOG.next.md
- generated/elasticsearch/README.md
- scripts/generators/es_template.py
- scripts/tests/test_es_template.py
- lowercasing component names for es template (#1323)
> [1.x] lowercasing component names for es template (#1323)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- experimental/schemas/threat.yml
Extends `threat.*` fieldset with proposed changes from [RFC 0018](https://github.com/elastic/ecs/blob/master/rfcs/text/0018-extend-threat-group-software.md) (https://github.com/elastic/ecs/pull/1335) in the experimental schema and artifacts.
> Stage 1 experimental changes for RFC 0018 - extend threat fieldset

- CHANGELOG.next.md
- scripts/cmd/gocodegen/gocodegen.go
- Add nested type support to go code generator (#1254)
> [1.x] Add nested type support to go code generator (#1254)

- CHANGELOG.next.md
- scripts/cmd/gocodegen/gocodegen.go
Changes introduced in #1254 added an extraneous newline character to each `.go` file generated by `make gocodegen`.
This change removes the extra newline and fixes the test failures due to the modified, uncommitted changes in `code/go/ecs`.
> Remove extra newline from Go code generator

- CHANGELOG.next.md
- scripts/cmd/gocodegen/gocodegen.go
- Remove extra newline from Go code generator (#1350)
> [1.x] Remove extra newline from Go code generator (#1350)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- scripts/templates/field_details.j2
- Adjustments to the field set "usage" docs (#1345)
> [1.x] Adjustments to the field set "usage" docs (#1345)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- experimental/schemas/threat.yml
This PR fixes an incorrect `type` setting introduced into the experimental schema in #1344 
`type: url` is invalid and has been replaced with `type: keyword`.
> Correct data type for `group.ref` and `software.ref` experimental fields

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- experimental/schemas/threat.yml
- Correct data type for `group.ref` and `software.ref` experimental fields (#1351)
> [1.x] Correct data type for `group.ref` and `software.ref` experimental fields (#1351)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- docs/usage/README.md
- docs/usage/user.asciidoc
- scripts/templates/field_details.j2
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/master/rfcs/README.md)? n/a
- If submitting code/script changes, have you verified all tests pass locally using `make test`? Y
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? Y
- Is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. Y …
> Adjust field set usage docs sidebar links

- rfcs/text/0009-data_stream-fields.md
Rolling back `data_stream` fields RFC to stage 2 (candidate) based on the decision to introduce fields as `beta` for now in [#1307](https://github.com/elastic/ecs/pull/1307#issuecomment-819672236).
> [RFC] Rollback `data_stream` proposal to stage 2

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_nested.yml
- schemas/README.md
- schemas/process.yml
- scripts/schema/cleaner.py
- scripts/schema/finalizer.py
- scripts/templates/field_details.j2
- scripts/tests/unit/test_schema_cleaner.py
- scripts/tests/unit/test_schema_finalizer.py
- Allow custom descriptions for self-nesting reuses (#1366)
> [1.x] Allow custom descriptions for self-nesting reuses (#1366)

- CHANGELOG.next.md
> [1.x] Cut 1.10 changelog (#1371)

- rfcs/text/0000-version-type-field-migration.md
- rfcs/text/0020-version-type-field-migration.md
Stage 0 proposal for adopting the `version` type for fields containing software version values.
[`version`](https://www.elastic.co/guide/en/elasticsearch/reference/current/version.html) is specialized to support precedence rules based on [Semantic Versioning](semver.org).
Stage 0 (Strawperson) Criteria:
[Preview of markdown proposal](https://github.com/ebeahan/ecs/blob/rfc/0000/adopt-version-field-type/rfcs/text/0000-version-type-field-migration.md)
> [RFC] Version Type Field Migration - Stage 0

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_nested.yml
- schemas/user.yml
Using the `short_override` field, update the field reuse descriptions for these three `users.*` reuses:
* `user.changes.*`
* `user.effective.*`
* `user.target.*`
These updated descriptions will better describe the use of each.
> Provide updated descriptions for `user.*` field reuses

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_nested.yml
- schemas/user.yml
- Provide updated descriptions for `user.*` field reuses (#1382)
> [1.x] Provide updated descriptions for `user.*` field reuses (#1382)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_nested.yml
- schemas/user.yml
Backports the following commits to 1.10:
- Provide updated descriptions for `user.*` field reuses (#1382)
> [1.10] Provide updated descriptions for `user.*` field reuses (#1382)

- CHANGELOG.next.md
- code/go/ecs/process.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/process.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/process.json
- schemas/process.yml
Add `user` to process schema to capture the user that a processing is running as.
For issue: https://github.com/elastic/ecs/issues/1380
Test passed. Committed auto-generated changes.
> Add `user` to process schema

- rfcs/text/0000-threat-enrichment.md
- rfcs/text/0021-threat-enrichment.md
As [documented](https://github.com/elastic/ecs/pull/1293#issuecomment-825212880) in the [existing threat intel RFC](https://github.com/elastic/ecs/pull/1293), this proposal aims to solve the threat intel enrichment use case by reusing the `threat.indicator` fieldset under a new name and as an array of objects, where each object represents an indicator that matched the (now enriched) event, and the `matched.*` fields on each object provide context for that particular indicator match.
Moving this list of indicators to a new field allows us to:
* reuse the existing `threat.indicator` fieldset
* sidestep the documentation/mapping complexities around when `threat.indicator` is an object (indicator) vs. when it's an array of objects (enrichment)
[Preview of markdown …
> [RFC] Stage 0 - Threat Enrichment

- .gitignore
- CHANGELOG.next.md
- scripts/generator.py
- scripts/generators/asciidoc_fields.py
- scripts/templates/fields.j2
- scripts/templates/index.j2
- Fix ecs GitHub repo link source branch (#1393)
> [1.x] Fix ecs GitHub repo link source branch (#1393)

- docs/using-mapping-network-events.asciidoc
The client port is wrongly documented as 64734 instead of 54162. …
> Client port is wrongly documented

- docs/using-mapping-network-events.asciidoc
Forward ports the following commits to `1.x`:
* Client port is wrongly documented (#1402)
> [1.x] Client port is wrongly documented (#1402)

- rfcs/text/0000-match_only_text-data-type.md
- rfcs/text/0023-match_only_text-data-type.md
Stage 0 proposal for migrating `text` type fields, including the `message` base field, to use the `match_only_text` data type being introduced in Elasticsearch 7.14.
Stage 0 (Strawperson) Criteria:
[Preview of markdown proposal](https://github.com/ebeahan/ecs/blob/rfc/match_only_text-migrate/rfcs/text/0000-match_only_text-data-type.md)
> [RFC] `match_only_text` type migration - Stage 0

- CHANGELOG.next.md
- CONTRIBUTING.md
Consolidate all breaking changes into the `Breaking changes` section under `Unreleased` in `CHANGELOG.next.md`.
Unreleased, non-breaking changes can continue going under `Unreleased` underneath the `Schema Changes` and `Tooling and Artifact Changes` headers, but `Breaking changes` will remain underneath `Unreleased` for the remaining `1.x` minors as we introduce breaking changes into the `master` branch.
Additionally, I updated `CONTRIBUTING.md` with more details around the ECS repo's branching strategy and changelog conventions.
> Consolidate `Breaking changes` sections in `CHANGELOG.next`

- rfcs/text/0015-create-file-elf.md
The date wasn't updated when merging #1294
> Set the merge date on RFC 0015 stage 2

- CHANGELOG.next.md
- consolidate breaking changes section: https://github.com/elastic/ecs/pull/1408/commits/0b82cb9fc8966acb45d4155545c4094c9bccdf00
> [1.x] Consolidate `Breaking changes` sections in `CHANGELOG.next` (#1408)

- CHANGELOG.next.md
Backports the following commits to 1.10:
- consolidate breaking changes section: https://github.com/elastic/ecs/pull/1408/commits/0b82cb9fc8966acb45d4155545c4094c9bccdf00
> [1.10] Consolidate `Breaking changes` sections in `CHANGELOG.next`

- CHANGELOG.next.md
- scripts/cmd/gocodegen/gocodegen.go
- Support `match_only_text` in Go code generator (#1418)
> [1.x] Support `match_only_text` in Go code generator (#1418)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_nested.yml
- schemas/orchestrator.yml
Apply changes from stage 3 `orchestrator` header RFC ([0012](https://github.com/elastic/ecs/blob/master/rfcs/text/0012-orchestrator-field-set.md)): #1343
> Stage 3 changes for RFC 0012 - `orchestrator` field set

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_nested.yml
- schemas/orchestrator.yml
- Stage 3 changes for RFC 0012 - `orchestrator` field set (#1417)
> [1.x] Stage 3 changes for RFC 0012 - `orchestrator` field set (#1417)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_nested.yml
- schemas/user.yml
- Add `host.user.*` deprecation notice in field reuse description (#1422)
> [1.x] Add `host.user.*` deprecation notice in field reuse description (#1422)

- CHANGELOG.next.md
- code/go/ecs/related.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/related.yml
- Explicitly include user identifiers in `related.user` field description (#1420)
> [1.x] Explicitly include user identifiers in `related.user` field description (#1420)

- CHANGELOG.md
- CHANGELOG.next.md
> Cut changelog for 1.10.0

- CHANGELOG.next.md
- code/go/ecs/http.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/http.yml
In addition to removing the deprecation note, I included [new guidance](https://github.com/elastic/ecs/pull/1443/files#diff-535c241aff61a02effef7c3af2446d787e3c4641139ca0f9e53b507ed7225086R4238) about retaining the casing from the original event.
I also limited the `Example` attribute to a single value since this field is not expected to be an array. 
Closes #1363
> Remove guidance to lowercase `http.request.method`.

- CHANGELOG.next.md
- code/go/ecs/cloud.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/cloud.yml
Expand the field definitions for `cloud.region` and `cloud.availability_zone` to include services or resources. The current definition implies these fields are limited to hosts/VMs running in an IaaS service like EC2 or GCE.
Closes #1287
> Improve cloud region and AZ field descriptions

- CHANGELOG.next.md
- Makefile
- code/go/ecs/event.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/event.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/event.json
- schemas/event.yml
This adds a field that can be used to reflect the status of the agent.id verification performed by the receiving system or data pipeline. If the receiving system checks that the sender is authorized for a given agent.id value then the outcome can be added to this field.
For example you might implement mTLS for authenticating agents sending data to Logstash. You could add the agent's ID to the agent's client cert subject and then validate incoming events in your Logstash pipeline to ensure the data has the agent ID.
Or with Elasticsearch you could provide each of your agents with an API key that has the agent.id associated to the API key metadata. Then using an Ingest Node pipeline you can validate the agent.id against the client's API key metadata.
> Add field event.agent_id_status

- CHANGELOG.next.md
- Makefile
- code/go/ecs/event.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/event.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/event.json
- schemas/event.yml
- Add field event.agent_id_status (#1454)
> [1.x] Add field event.agent_id_status (#1454)

- CHANGELOG.next.md
- scripts/schema/finalizer.py
- scripts/tests/unit/test_schema_finalizer.py
- Add support for multi-level self-nestings (#1459)
> [1.x] Add support for multi-level self-nestings (#1459)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/process.json
- experimental/schemas/process.yml
Apply stage 1 experimental changes proposed in the `process.target` [RFC 0016](https://github.com/elastic/ecs/blob/master/rfcs/text/0016-target-process.md): #1297
> Stage 1 changes for RFC 0016 - `process.target` field reuse

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/process.json
- experimental/schemas/process.yml
- Stage 1 changes for RFC 0016 - `process.target` field reuse (#1467)
> [1.x] Stage 1 changes for RFC 0016 - `process.target` field reuse (#1467)

- rfcs/text/0017-remove-log-original.md
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Y 
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/master/CONTRIBUTING.md)? Y 
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/master/rfcs/README.md)? Y 
- Is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. Y …
> [RFC] 0017 Deprecation of log.original Stage 3 Proposal

- CHANGELOG.next.md
- docs/field-details.asciidoc
- scripts/templates/field_details.j2
Swap positions of the `Field Set` and `Location` columns in the `Field Reuse` sections of the ECS Field Reference docs.
After adding a link to the original field set, long location names were being wrapped when generated on the docs site:
Swapping the location of the `Field Set` and `Location` columns is a quick solution to render the `Location` as a single line:
This does place the field set link in the middle of the table versus on the left-hand side, but I don't think that will be an issue for users. 
[Docs Preview](https://ecs_1472.docs-preview.app.elstc.co/diff)
> [DOCS] Swap columns in field reuse table

- CHANGELOG.next.md
- docs/field-details.asciidoc
- scripts/templates/field_details.j2
- [DOCS] Swap columns in field reuse table (#1472)
> [1.x] [DOCS] Swap columns in field reuse table (#1472)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- scripts/templates/field_details.j2
With #1472 implemented, the table column headers also need updated.
Follow-up fix for the change introduced in #1472.
> [DOCS] Swap `Field Reuse` column headers

- CHANGELOG.next.md
- docs/field-details.asciidoc
- scripts/templates/field_details.j2
- [DOCS] Swap `Field Reuse` column headers (#1476)
> [1.x] [DOCS] Swap `Field Reuse` column headers (#1476)

- CHANGELOG.next.md
- code/go/ecs/event.go
- code/go/ecs/log.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- schemas/log.yml
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/master/CONTRIBUTING.md)? Y 
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/master/rfcs/README.md)? Y 
- If submitting code/script changes, have you verified all tests pass locally using `make test`? Y 
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? Y 
- Is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. Y …
> Implement Deprecation Notice relating to RFC 0017: Remove log.original

- CHANGELOG.next.md
- docs/field-details.asciidoc
- scripts/templates/field_details.j2
Change the flat, comma-separated list of expected field reuse locations into a bulleted list. As the number of included reuses has grown for some field sets, I think the bulleted list is easier to consume.
[Docs preview](https://ecs_1473.docs-preview.app.elstc.co/diff)
> [DOCS] Bulleted list of expected nesting locations

- CHANGELOG.next.md
- docs/field-details.asciidoc
- scripts/templates/field_details.j2
- [DOCS] Bulleted list of expected nesting locations (#1473)
> [1.x] [DOCS] Bulleted list of expected nesting locations (#1473)

- CHANGELOG.next.md
- code/go/ecs/event.go
- code/go/ecs/log.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- schemas/log.yml
- Implement Deprecation Notice relating to RFC 0017: Remove log.original (#1469)
> [1.x] Implement Deprecation Notice relating to RFC 0017: Remove log.original (#1469)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/event.json
- experimental/generated/elasticsearch/component/log.json
- experimental/generated/elasticsearch/component/threat.json
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/error.json
- generated/elasticsearch/component/event.json
- generated/elasticsearch/component/log.json
- generated/elasticsearch/component/threat.json
- scripts/schema/cleaner.py
- scripts/tests/unit/test_schema_cleaner.py
- Remove `ignore_above` parameter when indexing is disabled on field (#1483)
> [1.x] Remove `ignore_above` parameter when indexing is disabled on field (#1483)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- generated/beats/fields.ecs.yml
- scripts/generators/beats.py
- scripts/tests/unit/test_beats_generator.py
- Ensure `doc_values` parameter is passed into Beats field defintions (#1488)
> [1.11] Ensure `doc_values` parameter is passed into Beats field defintions (#1488)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- generated/beats/fields.ecs.yml
- scripts/generators/beats.py
- scripts/tests/unit/test_beats_generator.py
- Ensure `doc_values` parameter is passed into Beats field defintions (#1488)
> [1.x] Ensure `doc_values` parameter is passed into Beats field defintions (#1488)

- rfcs/text/0008-threat-intel.md
- rfcs/text/0008/as.yml
- rfcs/text/0008/file.yml
- rfcs/text/0008/geo.yml
- rfcs/text/0008/hash.yml
- rfcs/text/0008/pe.yml
- rfcs/text/0008/registry.yml
- rfcs/text/0008/threat.yml
- rfcs/text/0008/url.yml
- rfcs/text/0008/x509.yml
- rfcs/text/0021-threat-enrichment.md
- rfcs/text/0021/as.yml
- rfcs/text/0021/event.yml
- rfcs/text/0021/file.yml
- rfcs/text/0021/geo.yml
- rfcs/text/0021/hash.yml
- rfcs/text/0021/pe.yml
- rfcs/text/0021/registry.yml
- rfcs/text/0021/threat.yml
- rfcs/text/0021/url.yml
- rfcs/text/0021/x509.yml
@ebeahan I think this is ready for review, just a few questions:
1. How/where should the RFC docs be updated to reflect these changes (for posterity, not the definitions themselves)
2. A critical omission from the enrichments RFC is that the `indicator` fields are not present under `threat.enrichments`! How do I go about defining `threat.enrichments.indicator.*` as coming from `threat.indicator.*` ?
> CTI 1.11 Addendum

- CHANGELOG.next.md
- code/go/ecs/threat.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/threat.yml
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process] (https://github.com/elastic/ecs/blob/master/rfcs/README.md)? Y 
- If submitting code/script changes, have you verified all tests pass locally using `make test`?  Y 
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? Y
- Is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. Y  …
> add one word to threat.yml

- CHANGELOG.next.md
- schemas/README.md
- scripts/templates/field_values.j2
- scripts/tests/test_asciidoc_fields.py
- Present `beta` tooltip for categorization values (#1511)
> [1.x] Present `beta` tooltip for categorization values (#1511)

- CHANGELOG.next.md
- schemas/README.md
- scripts/templates/field_values.j2
- scripts/tests/test_asciidoc_fields.py
- Present `beta` tooltip for categorization values (#1511)
> [1.11] Present `beta` tooltip for categorization values (#1511)

- experimental/README.md
The `experimental` README has not been updated since ECS RFC stage 4 was [removed](https://github.com/elastic/ecs/pull/1194).
The ECS experimental schema should contain RFC changes that have made it to stage 1.
> Correct RFC stages in the `experimental` README

- rfcs/text/0023-match_only_text-data-type.md
Continuing onto Stage 2 with this proposal for migrating `text` type fields to use the `match_only_text` data type.
`match_only_text` is being introduced in Elasticsearch 7.14.
Stage 2 (Candidate) Criteria:
[Preview of markdown proposal](https://github.com/ebeahan/ecs/blob/rfc/0023/stage-2/rfcs/text/0023-match_only_text-data-type.md)
> [RFC] `text` to `match_only_text` field type migration - Stage 2

- CHANGELOG.next.md
- scripts/generators/es_template.py
- scripts/schema/oss.py
- scripts/tests/test_es_template.py
- Support multi-field type fallback (#1528)
> [1.x] Support multi-field type fallback (#1528)

- CHANGELOG.next.md
- code/go/ecs/log.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/log.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/log.json
- schemas/log.yml
Migrate `log.origin.file.line` from an `integer` type to a `long` type.
This is considered a breaking change in ECS, but may not affect many users. The index templates generated by Beats and Agent already use `long` for `log.origin.file.line`.
> Update `log.origin.file.line` from `integer` to `long`

- rfcs/text/0002-rfc-environment.md
[Preview of the proposal doc](https://github.com/elastic/ecs/blob/service-environment-rfc-stage2/rfcs/text/0002-rfc-environment.md)
> Progressing service.environment RFC to stage 2

- CHANGELOG.next.md
- code/go/ecs/service.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/service.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/service.json
- schemas/service.yml
Adding `service.environment` field as beta to the schema: [RFC 0002](https://github.com/elastic/ecs/blob/master/rfcs/text/0002-rfc-environment.md).
[Docs preview](https://ecs_1541.docs-preview.app.elstc.co/guide/en/ecs/master/ecs-service.html#field-service-environment)
> Stage 2 changes for RFC 0002 - `service.environment`

- CHANGELOG.next.md
- code/go/ecs/service.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/service.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/service.json
- schemas/service.yml
- Stage 2 changes for RFC 0002 - `service.environment` (#1541)
> [1.x] Stage 2 changes for RFC 0002 - `service.environment` (#1541)

- rfcs/text/0025-container-metric-fields.md
We are working on defining a set of fields for container inventory schema and during this process, we see some metrics that are currently not included in the container ECS fields. This RFC is to add these container metric fields into ECS so all users can leverage these fields when monitoring container performance such as CPU, memory, disk IO, and network.
> [RFC] Add container metric fields - Stage 1

- CHANGELOG.next.md
- code/go/ecs/threat.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/threat.json
- schemas/threat.yml
Advance fields proposed in [RFC 0018](https://github.com/elastic/ecs/blob/master/rfcs/text/0018-extend-threat-group-software.md) from beta to GA.
Adding `threat.software.alias` was also part of the stage 3 changes.
> Stage 3 changes for RFC 0018 - extend `threat.*` field set

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/container.json
- experimental/schemas/container.yml
Introduce additional `container.*` metric fields proposed in [RFC 0025](https://github.com/elastic/ecs/blob/master/rfcs/text/0025-container-metric-fields.md) (#1529) to the `experimental` schema.
> Stage 1 changes for RFC 0025 - container metric fields

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/container.json
- experimental/schemas/container.yml
- Stage 1 changes for RFC 0025 - container metric fields (#1546)
> [1.x] Stage 1 changes for RFC 0025 - container metric fields (#1546)

- CHANGELOG.next.md
- docs/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
We have received questions from community members about when to use `event.kind:alert` vs. `event.kind:signal`
These allowed values can cause confusion, since documents that contain `event.kind:signal` are often referred to as "alerts."
As background, the overloading of the term "alerts" is a longstanding issue in security information and event management, where there was frequently confusion between external alerts generated by some external system and alerts generated by the SIEM itself.  Any usage of the unmodified "alerts" was thus ambiguous.
The proposed language attempts to provide clear guidance:
- If the alert is created by a system external to the Elastic Stack,  use `event.kind:alert`
- If the alert is created _*by*_ the Elastic Stack/solution, use `event.kind:signal`
> Update event.kind allowed value descriptions to clarify usage of "alert" and "signal"

- CHANGELOG.next.md
- docs/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- Update event.kind allowed value descriptions to clarify usage of "alert" and "signal" (#1548)
> [1.11] Update event.kind allowed value descriptions to clarify usage of "alert" and "signal" (#1548)

- CHANGELOG.next.md
- docs/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- Update event.kind allowed value descriptions to clarify usage of "alert" and "signal" (#1548)
> [1.x] Update event.kind allowed value descriptions to clarify usage of "alert" and "signal" (#1548)

- docs/field-details.asciidoc
- docs/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- New event categorization values to support threat intel use cases (#1510)
> [1.11] New event categorization values to support threat intel use cases (#1510)

- code/go/ecs/code_signature.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/dll.json
- experimental/generated/elasticsearch/component/file.json
- experimental/generated/elasticsearch/component/process.json
- experimental/generated/elasticsearch/component/threat.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/dll.json
- generated/elasticsearch/component/file.json
- generated/elasticsearch/component/process.json
- generated/elasticsearch/component/threat.json
- schemas/code_signature.yml
Introduces two new fields to the `code_signature.*` field set:
* `code_signature.digest_algorithm` - Hashing algorithm used to sign the process.
* `code_signature.timestamp` - When the signature was generated and signed.:w
Closes #1524
> Add `code_signature.digest_algorithm` and `code_signature.timestamp` fields

- code/go/ecs/code_signature.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/dll.json
- experimental/generated/elasticsearch/component/file.json
- experimental/generated/elasticsearch/component/process.json
- experimental/generated/elasticsearch/component/threat.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/dll.json
- generated/elasticsearch/component/file.json
- generated/elasticsearch/component/process.json
- generated/elasticsearch/component/threat.json
- schemas/code_signature.yml
- Add `code_signature.digest_algorithm` and `code_signature.timestamp` fields (#1557)
> [1.x] Add `code_signature.digest_algorithm` and `code_signature.timestamp` fields (#1557)

- rfcs/text/0022-remove-process-ppid.md
Changes to advance RFC 0022 - remove `process.ppid` to stage 2.
[Preview of proposal](https://github.com/ebeahan/ecs/blob/rfc/0022/stage-2/rfcs/text/0022-remove-process-ppid.md)
Stage 2 Criteria
> RFC 0022 stage 2 - Remove `process.ppid` field 

- CHANGELOG.md
- CHANGELOG.next.md
Move upcoming 1.11 changelog notes from CHANGELOG.next to CHANGELOG.
> Cut 1.11 CHANGELOG

- CHANGELOG.md
- CHANGELOG.next.md
* Cut 1.11 CHANGELOG: https://github.com/elastic/ecs/pull/1558
> [master] Cut 1.11 changelog (#1558)

- CHANGELOG.md
- CHANGELOG.next.md
* Cut 1.11 CHANGELOG: https://github.com/elastic/ecs/pull/1558
> [1.x] Cut 1.11 changelog (#1558)

- rfcs/text/0023-match_only_text-data-type.md
Advancing proposal for migrating text type fields to use the match_only_text data type to stage 3.
match_only_text was introduced in Elasticsearch 7.14.
[Preview of proposal](https://github.com/ebeahan/ecs/blob/rfc/0023/stage-3/rfcs/text/0023-match_only_text-data-type.md)
> [RFC] `text` to `match_only_text` field type migration - Stage 3

- rfcs/text/0010-email.md
- rfcs/text/0010/email.yml
- rfcs/text/0010/event.yml
Moving the Email RFC to Stage 1
[Preview of the RFC proposal](https://github.com/P1llus/ecs/blob/master/rfcs/text/0010-email.md)
Criteria for Stage 1
> [RFC] Email - Stage 1 Proposal

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/email.json
- experimental/generated/elasticsearch/template.json
- experimental/schemas/email.yml
Add changes that have advanced to stage 1 from [RFC 0010](https://github.com/elastic/ecs/blob/master/rfcs/text/0010-email.md) (#1219) into the experimental schema.
> RFC 0010 Stage 1 - Add `email.*` fields to experimental schema

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/email.json
- experimental/generated/elasticsearch/template.json
- experimental/schemas/email.yml
- RFC 0010 Stage 1 - Add `email.*` fields to experimental schema (#1569)
> [1.x] RFC 0010 Stage 1 - Add `email.*` fields to experimental schema (#1569)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/http.json
- experimental/generated/elasticsearch/component/organization.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/http.json
- generated/elasticsearch/component/organization.json
- schemas/http.yml
- schemas/organization.yml
While auditing changes implemented in #1532, discovered several `http.*` and `organization.*` fields were missed in the original PR.
Also migrating these multi-fields to `match_only_text`:
* `http.request.body.content.text`
* `http.response.body.content.text`
* `organization.name.text`
> [RFC] `match_only_text` stage 2 - additional changes

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/http.json
- experimental/generated/elasticsearch/component/organization.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/http.json
- generated/elasticsearch/component/organization.json
- schemas/http.yml
- schemas/organization.yml
- [RFC] `match_only_text` stage 2 - additional changes (#1571)
> [1.x] [RFC] `match_only_text` stage 2 - additional changes (#1571)

- CHANGELOG.next.md
* Cut 1.12 FF changelog.next section: https://github.com/elastic/ecs/pull/1573
> [master] Cut 1.12 FF changelog.next section (#1573)

- CHANGELOG.next.md
* Cut 1.12 FF changelog.next section: https://github.com/elastic/ecs/pull/1573
> [1.x] Cut 1.12 FF changelog.next section (#1573)

- CHANGELOG.next.md
Correct the breaking changes entries in CHANGELOG.next carried forward from past releases.
> Adjust breaking changes entires in CHANGELOG.next

- CHANGELOG.next.md
- fix breaking changes and their sections now that CHANGELOG.next is pointing to 8.0 (#1577)
> [1.x] fix breaking changes and their sections now that CHANGELOG.next is pointing to 8.0 (#1577)

- CHANGELOG.next.md
- fix breaking changes and their sections now that CHANGELOG.next is pointing to 8.0 (#1577)
> [1.12] fix breaking changes and their sections now that CHANGELOG.next is pointing to 8.0 (#1577)

- CHANGELOG.next.md
- code/go/ecs/log.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/log.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/log.json
- schemas/log.yml
Remove the `log.original` field as finalized in [RFC 0017](https://github.com/elastic/ecs/blob/master/rfcs/text/0017-remove-log-original.md) (https://github.com/elastic/ecs/pull/1465).
> RFC 0017 - remove `log.original` field

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/error.yml
- schemas/http.yml
- schemas/process.yml
- schemas/registry.yml
- schemas/url.yml
Remove the `beta` attribute to promote these uses of `type: wildcard` as GA changes.
Proposal: [RFC 0001](https://github.com/elastic/ecs/blob/master/rfcs/text/0001-wildcard-data-type.md)
Stage 3 PR: https://github.com/elastic/ecs/pull/1530
> RFC 0001 `wildcard` type field migration - stage 3 changes

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/as.yml
- schemas/base.yml
- schemas/error.yml
- schemas/file.yml
- schemas/http.yml
- schemas/organization.yml
- schemas/os.yml
- schemas/process.yml
- schemas/threat.yml
- schemas/url.yml
- schemas/user.yml
- schemas/user_agent.yml
- schemas/vulnerability.yml
Remove the `beta` attribute to promote these uses of `type: match_only-text` as GA changes.
Proposal: [RFC 0023](https://github.com/elastic/ecs/blob/master/rfcs/text/0023-match_only_text-data-type.md)
Stage 3 PR: https://github.com/elastic/ecs/pull/1560
> RFC 0023 `match_only_text` type field migration - stage 3 changes

- .github/workflows/test.yml
- CHANGELOG.next.md
- Makefile
This PR removes the remaining golang dependencies in the project `Makefile`.
Remove `check-license-header` rule from `Makefile` since `check-license-header` only works with `.go` source files.
* Install the `misspell` binary instead of `go get`
* Add `-error` flag to throw a non-zero exit code for CI
* Include `docs/*` and `experimental/schema/*` directives in the `misspell` check.
Remove the `setup-go` step since golang is no longer a required dependency for testing. 
Closes #630
> Remove remaining golang dependencies

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/as.yml
- schemas/file.yml
- schemas/geo.yml
- schemas/hash.yml
- schemas/pe.yml
- schemas/registry.yml
- schemas/threat.yml
- schemas/url.yml
- schemas/x509.yml
Removing the `beta` attributes now that [RFC 0008](https://github.com/elastic/ecs/blob/master/rfcs/text/0008-threat-intel.md) has advanced to stage 3.
Also, adjusting the `threat.indicator.confidence` field's description.
> RFC 0008 threat indicator fields - stage 3 changes

- schemas/README.md
Correct `schemas/README.md` documentation to use `allowed_values` instead of `accepted_values`.
When the schema was changed in 91aec05, the change didn't also make it into the documentation.
Closes #1589
> Correct attribute to `allowed_values`

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/process.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/process.json
- schemas/process.yml
Remove the `process.ppid` field as proposed in [RFC 0022](https://github.com/elastic/ecs/blob/master/rfcs/text/0022-remove-process-ppid.md) (#1592).
This change will also remove `parent.process.ppid`.
> Remove `process.ppid` field

- USAGE.md
> [1.12] Fix typo (#1598)

- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/threat.json
- schemas/hash.yml
> [1.12] Hash ordering fix (#1603)

- CHANGELOG.md
- CHANGELOG.next.md
Move upcoming 1.12 changelog notes from CHANGELOG.next to CHANGELOG.
> Cut 1.12 Changelog

- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/network.yml
- Improve descriptions for `network.*` fields (#1645)
> [8.0] Improve descriptions for `network.*` fields (#1645)

- CHANGELOG.next.md
- generated/elasticsearch/6/template.json
- scripts/schema/oss.py
- [Bugfix] Add `flattened` fallback to `object` see issue #1649 (#1653)
> [1.12] [Bugfix] Add `flattened` fallback to `object` see issue #1649 (#1653)

- CHANGELOG.next.md
- generated/elasticsearch/6/template.json
- scripts/schema/oss.py
- [Bugfix] Add `flattened` fallback to `object` see issue #1649 (#1653)
> [1.11] [Bugfix] Add `flattened` fallback to `object` see issue #1649 (#1653)

- CHANGELOG.next.md
- CONTRIBUTING.md
- README.md
- USAGE.md
- stages.html
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/master/rfcs/README.md)? Y
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? n(a …
> [DOCS] Update refs from master to main in USAGE.md etc

- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/cgroup.json
- experimental/generated/elasticsearch/template.json
- experimental/schemas/cgroup.yml
Add the proposed fields from [RFC 0028](https://github.com/elastic/ecs/blob/main/rfcs/text/0028-cgroups.md) stage 1 to the experimental ECS schema. (#1627 )
> RFC 0028 Stage 1 - Add `cgroup.*` fields to experimental schema

- rfcs/PROCESS.md
The ECS team helps community RFC authors find an Elastic-internal sponsor, but this wasn't stated explicitly in the process docs.
> [RFC] Add ECS team's role in finding a sponsor

- CONTRIBUTING.md
- Makefile
- USAGE.md
- scripts/requirements-dev.txt
- scripts/requirements.txt
Most uses do not need to install the dependencies required for testing and lining, and this change splits `requirements.txt` into `requirements.txt` and `requirements-dev.txt`.
`make ve` has been updated to include the additional file, and I updated the repo docs as well. I thought it prudent to simplify our install instructions in `USAGE.md`, but I'm open to discussion if anyone feels differently.
> Separate packages required for testing/linting

- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/server.yml
- schemas/source.yml
Revisit the description for the `.domain` fields for `source.*`, `destination.*`, `client.*`, and `server.*` field sets.
Also, add `example` and `short` attributes for each field.
Fixes #1663
> Expand `[source|destination|client|server].domain` field descriptions

- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/server.yml
- schemas/source.yml
- Expand `[source|destination|client|server].domain` field descriptions (#1673)
> [8.0] Expand `[source|destination|client|server].domain` field descriptions (#1673)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/dll.json
- experimental/generated/elasticsearch/component/file.json
- experimental/generated/elasticsearch/component/process.json
- experimental/generated/elasticsearch/component/threat.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/dll.json
- generated/elasticsearch/component/file.json
- generated/elasticsearch/component/process.json
- generated/elasticsearch/component/threat.json
- schemas/hash.yml
- schemas/pe.yml
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? yes
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? yes
- If submitting code/script changes, have you verified all tests pass locally using `make test`? no script changes, only schema
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? yes
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. yes
- Have you added an …
> Added new hash fields

- CHANGELOG.next.md
- add missing changelog entry for #1679
> [8.0] Add missing changelog entry for #1679

- CHANGELOG.next.md
- generated/elasticsearch/component/email.json
Missed including an `email.*` component template in https://github.com/elastic/ecs/pull/1688
> add component template for email.* field set

- CHANGELOG.next.md
- generated/elasticsearch/component/email.json
- add component template for email.* field set (#1705)
> [8.1] add component template for email.* field set (#1705)

- docs/migrating/products-solutions.asciidoc
In 7.16, the APM integration became generally available 🎉. As a part of this change, the APM Server Reference and APM Overview were deprecated and replaced with a new [APM Guide](https://www.elastic.co/guide/en/apm/guide/current/index.html). This PR updates a link in the ECS documentation to point to the new APM guide.
Unfortunately, when 7.17 is released, the old link will fail. To fix this, we need to backport this PR all the way to 1.3 😬 (which I'm happy to do). The broken links can be seen in https://github.com/elastic/docs/pull/2333, but I've also included a summary below.
```
4:17:47 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/ecs/1.10/ecs-products-solutions.html contains broken links to:
14:17:47 INFO:build_docs:   - en/apm/get-started/7.17/overview.html
14:17:47 …
```
> docs: fix link to APM Overview

- CHANGELOG.next.md
- experimental/generated/elasticsearch/composable/template.json
- generated/elasticsearch/composable/template.json
- scripts/generators/es_template.py
Addresses https://github.com/elastic/ecs/issues/1339
The built-in index templates settings in Elasticsearch (logs-settings, metrics-settings, synthetics-settings) enable a higher compression ratio (DEFLATE vs LZ4) as the default now with the new indexing strategy: `index.codec: best_compression`
> Higher default compression for composable templates

- docs/migrating/products-solutions.asciidoc
> [8.1] docs: fix link to APM Overview (#1710)

- docs/migrating/products-solutions.asciidoc
> [8.0] docs: fix link to APM Overview (#1710)

- docs/products-solutions.asciidoc
> [1.12] docs: fix link to APM Overview (#1710)

- docs/products-solutions.asciidoc
> [1.11] docs: fix link to APM Overview (#1710)

- docs/products-solutions.asciidoc
Backports the following commits to 1.10:
> [1.10] docs: fix link to APM Overview (#1710)

- docs/products-solutions.asciidoc
Backports the following commits to 1.9:
> [1.9] docs: fix link to APM Overview (#1710)

- docs/products-solutions.asciidoc
Backports the following commits to 1.8:
> [1.8] docs: fix link to APM Overview (#1710)

- docs/products-solutions.asciidoc
> [1.7] docs: fix link to APM Overview (#1710)

- docs/products-solutions.asciidoc
> [1.6] docs: fix link to APM Overview (#1710)

- docs/products-solutions.asciidoc
Backports the following commits to 1.5:
> [1.5] docs: fix link to APM Overview (#1710)

- docs/products-solutions.asciidoc
Backports the following commits to 1.4:
> [1.4] docs: fix link to APM Overview (#1710)

- docs/products-solutions.asciidoc
Backports the following commits to 1.3:
> [1.3] docs: fix link to APM Overview (#1710)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- generated/beats/fields.ecs.yml
- scripts/generators/beats.py
- scripts/generators/ecs_helpers.py
- scripts/tests/unit/test_beats_generator.py
The generator was adding the `default_field` setting to non-root fieldsets, causing top-level fields (like `message`) to be excluded from the `default_field` index template configuration.
Relates https://github.com/elastic/beats/issues/29633
> Beats: fix default_field setting for root fields

- USAGE.md
Putting the markdown characters for the end of a script block at the end of a line does not terminate the block. The 3 backticks are rendered as part of the script block. This change puts the 3 backticks on a dedicated line to end the script block.
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? Y
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? Y
- If submitting code/script changes, have you verified all tests pass locally using `make test`? Not relevant
- If submitting schema/fields updates, have you generated new …
> fix improper script block end

- rfcs/PROCESS.md
Fixes the first link (`rfcs/`) [here](https://github.com/elastic/ecs/blob/main/rfcs/PROCESS.md) see [fix](https://github.com/kgeller/ecs/blob/broken-link-fix/rfcs/PROCESS.md)
> broken link fix

- docs/fields/field-details.asciidoc
- docs/fields/usage/threat.asciidoc
Add a [usage doc](https://github.com/elastic/ecs/blob/master/docs/usage/README.md) for the `threat.*` field set.
Details the threat intelligence indicator and enrichment use cases detailed in [RFC 0008](https://github.com/elastic/ecs/blob/master/rfcs/text/0008-threat-intel.md) and [RFC 0021](https://github.com/elastic/ecs/blob/master/rfcs/text/0021-threat-enrichment.md). The goal is to give users complete mapping examples using the `threat.*` fields.
[Usage doc preview](https://ecs_1597.docs-preview.app.elstc.co/guide/en/ecs/master/ecs-threat-usage.html)
> Introduce usage section for `threat.*` field set

- docs/fields/field-details.asciidoc
- docs/fields/usage/threat.asciidoc
- Introduce usage section for `threat.*` field set (#1597)
> [8.1] Introduce usage section for `threat.*` field set (#1597)

- docs/fields/field-details.asciidoc
- docs/fields/usage/threat.asciidoc
- Introduce usage section for `threat.*` field set (#1597)
> [8.0] Introduce usage section for `threat.*` field set (#1597)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/faas.yml
Since the field set is named using an abbreviation, include the abbr in parentheses after the full text.
> Include abbr in `FaaS` field set description

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/faas.yml
- Include abbr in `FaaS` field set description (#1755)
> [8.2] Include abbr in `FaaS` field set description (#1755)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/faas.yml
- Include abbr in `FaaS` field set description (#1755)
> [8.1] Include abbr in `FaaS` field set description (#1755)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_nested.yml
- schemas/faas.yml
- Include abbr in `FaaS` field set description (#1755)
> [8.0] Include abbr in `FaaS` field set description (#1755)

- CHANGELOG.next.md
- USAGE.md
- scripts/generator.py
- scripts/generators/es_template.py
- scripts/tests/test_es_template.py
- usage-example/README.md
- usage-example/fields/template-settings-legacy.json
- usage-example/fields/template-settings.json
- Adding support in for custom analyzers for text and overriding the default template settings for index templates (#1737)
> [8.2] Adding support in for custom analyzers for text and overriding the default template settings for index templates (#1737)

- CHANGELOG.next.md
- USAGE.md
- experimental/generated/elasticsearch/composable/template.json
- generated/elasticsearch/composable/template.json
- scripts/generator.py
- scripts/generators/es_template.py
- scripts/tests/test_es_template.py
- usage-example/README.md
- usage-example/fields/template-settings-legacy.json
- usage-example/fields/template-settings.json
- Adding support in for custom analyzers for text and overriding the default template settings for index templates (#1737)
> [8.1] Adding support in for custom analyzers for text and overriding the default template settings for index templates (#1737)

- CHANGELOG.next.md
- USAGE.md
- scripts/generator.py
- scripts/generators/es_template.py
- scripts/tests/test_es_template.py
- usage-example/README.md
- usage-example/fields/template-settings-legacy.json
- usage-example/fields/template-settings.json
- Adding support in for custom analyzers for text and overriding the default template settings for index templates (#1737)
> [8.0] Adding support in for custom analyzers for text and overriding the default template settings for index templates (#1737)

- CHANGELOG.md
- CHANGELOG.next.md
Move upcoming 8.0.0 changelog notes from CHANGELOG.next to CHANGELOG.
> Cut 8.0.0 changelog

- docs/using-ecs/guidelines/implementation.asciidoc
This PR only fixes json example (indentation and string formatting) in `docs/using-ecs/guidelines/implementation.asciidoc`
See the broken example live: https://www.elastic.co/guide/en/ecs/current/ecs-principles-implementation.html#_lookup
s
> docs/using-ecs/guidelines/implementation: example json formatting fix

- docs/using-ecs/guidelines/implementation.asciidoc
- [docs/using-ecs/guidelines/implementation: example json formatting fix (#1775)](https://github.com/elastic/ecs/pull/1775)
> [8.2] docs/using-ecs/guidelines/implementation: example json formatting fix (#1775)

- docs/using-ecs/guidelines/implementation.asciidoc
This will backport the following commits from `main` to `8.0`:
- [docs/using-ecs/guidelines/implementation: example json formatting fix (#1775)](https://github.com/elastic/ecs/pull/1775)
> [8.0] docs/using-ecs/guidelines/implementation: example json formatting fix (#1775)

- CHANGELOG.next.md
- scripts/requirements-dev.txt
- scripts/requirements.txt
- [Bump dependencies (#1782)](https://github.com/elastic/ecs/pull/1782)
> [8.2] Bump dependencies (#1782)

- CHANGELOG.next.md
- scripts/requirements-dev.txt
- scripts/requirements.txt
This will backport the following commits from `main` to `8.1`:
- [Bump dependencies (#1782)](https://github.com/elastic/ecs/pull/1782)
> [8.1] Bump dependencies (#1782)

- .github/workflows/stale.yml
Adjust the action now that I better understand how it runs:
* action doesn't offer a way only to evaluate PRs except labeling. Settings `days-before-close: -1` so now PRs or issues are inadvertently closed
* ensure issues are never marked `Stale` (for now): `days-before-issue-stale: -1`
* evaluate in ascending order: `ascending: true`
* up the max operations allowed from default (30) to 120: `operations-per-run: 120`
> Tuning stale workflow action

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- docs/fields/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/email.yml
- schemas/event.yml
Implement the schema changes proposed in [RFC 0010](https://github.com/elastic/ecs/blob/main/rfcs/text/0010-email.md) for [stage 3](https://github.com/elastic/ecs/pull/1704).
These changes make these fields GA in ECS by removing the `beta` attribute.
> [RFC] RFC 0010 `email.*` field set - stage 3 changes

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- docs/fields/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/email.yml
- schemas/event.yml
- [[RFC] RFC 0010 `email.*` field set - stage 3 changes (#1794)](https://github.com/elastic/ecs/pull/1794)
> [8.2] [RFC] RFC 0010 `email.*` field set - stage 3 changes (#1794)

- CHANGELOG.next.md
- docs/index.asciidoc
- docs/release-notes/8.0.asciidoc
- docs/release-notes/8.1.asciidoc
- docs/release-notes/8.2.asciidoc
- docs/release-notes/index.asciidoc
- scripts/templates/index.j2
Adds a `Release Notes` doc section. This new section contains the ECS project CHANGELOG entries beginning with ECS 8.0.
The following document attributes were added or modified to simplify creating the PR links in the release note entries:
```asciidoc
:ecs_repo: https://github.com/elastic/ecs/
:ecs_github_repo_link: {ecs_repo}blob/{source_branch}
:ecs_issue: {ecs_repo}issues/
:ecs_pull: {ecs_repo}pull/
```
Changes to the top-level `index.asciidoc` made in the `index.j2` template file.
For this initial PR, `8.2`, `8.1`, and `8.0` will be merged into the `main` and `8.2` branches. `8.2` will be removed for the `8.1` branch, and both `8.2` and `8.1` will be removed for the `8.0` branch.
[Docs Preview](https://ecs_1800.docs-preview.app.elstc.co/guide/en/ecs/master/ecs-release-notes.html) …
> [DOCS] Add release notes section

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/log.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/log.json
- generated/elasticsearch/legacy/template.json
- schemas/log.yml
- Add additional fields for RFC 5424 messages (log.syslog.version,
log.syslog.msgid, log.syslog.data)
- Add log.syslog.hostname, log.syslog.appname, and log.syslog.procid
for hostname, process name, and process ID fields present in syslog
messages, respectively. These fields are added since it is not always
known that user wants these values copied to the more general ECS fields
(host.hostname, process.name, process.pid).
> Add additional log.syslog fields

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/log.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/log.json
- generated/elasticsearch/legacy/template.json
- schemas/log.yml
- Add additional log.syslog fields (#1793)
> [8.2] Add additional log.syslog fields (#1793)

- scripts/requirements.txt
This will backport the following commits from `8.0` to `1.12`:
> [1.12] Pin markupsafe for Jinja2 workaround (#1804)

- scripts/requirements.txt
This will backport the following commits from `8.0` to `1.11`:
> [1.11] Pin markupsafe for Jinja2 workaround (#1804)

- scripts/requirements.txt
This will backport the following commits from `8.0` to `1.10`:
> [1.10] Pin markupsafe for Jinja2 workaround (#1804)

- scripts/requirements.txt
This will backport the following commits from `8.0` to `1.9`:
> [1.9] Pin markupsafe for Jinja2 workaround (#1804)

- scripts/requirements.txt
This will backport the following commits from `8.0` to `1.8`:
> [1.8] Pin markupsafe for Jinja2 workaround (#1804)

- scripts/requirements.txt
This will backport the following commits from `8.0` to `1.7`:
> [1.7] Pin markupsafe for Jinja2 workaround (#1804)

- scripts/requirements.txt
This will backport the following commits from `8.0` to `1.6`:
> [1.6] Pin markupsafe for Jinja2 workaround (#1804)

- CHANGELOG.next.md
- docs/index.asciidoc
- docs/release-notes/8.0.asciidoc
- docs/release-notes/8.1.asciidoc
- docs/release-notes/8.2.asciidoc
- docs/release-notes/index.asciidoc
- scripts/templates/index.j2
- [[DOCS] Add release notes section (#1800)](https://github.com/elastic/ecs/pull/1800)
> [8.2] [DOCS] Add release notes section (#1800)

- CHANGELOG.next.md
- docs/index.asciidoc
- docs/release-notes/8.0.asciidoc
- docs/release-notes/8.1.asciidoc
- docs/release-notes/8.2.asciidoc
- docs/release-notes/index.asciidoc
- scripts/templates/index.j2
This will backport the following commits from `main` to `8.1`:
- [[DOCS] Add release notes section (#1800)](https://github.com/elastic/ecs/pull/1800)
> [8.1] [DOCS] Add release notes section (#1800)

- CHANGELOG.next.md
- docs/index.asciidoc
- docs/release-notes/8.0.asciidoc
- docs/release-notes/8.1.asciidoc
- docs/release-notes/8.2.asciidoc
- docs/release-notes/index.asciidoc
- scripts/templates/index.j2
This will backport the following commits from `main` to `8.0`:
- [[DOCS] Add release notes section (#1800)](https://github.com/elastic/ecs/pull/1800)
> [8.0] [DOCS] Add release notes section (#1800)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/faas.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/faas.json
- generated/elasticsearch/legacy/template.json
- rfcs/text/0027-faas-fields.md
- rfcs/text/0027/faas.yml
- schemas/faas.yml
- Added `id`, `name` and `version` fields for `faas` (#1796)
> [8.2] Added `id`, `name` and `version` fields for `faas` (#1796)

- docs/release-notes/8.0.1.asciidoc
- docs/release-notes/index.asciidoc
This will backport the following commits from `main` to `8.1`:
- [add 8.0.1 release notes (#1818)](https://github.com/elastic/ecs/pull/1818)
> [8.1] add 8.0.1 release notes (#1818)

- docs/release-notes/8.0.1.asciidoc
- docs/release-notes/index.asciidoc
This will backport the following commits from `main` to `8.0`:
- [add 8.0.1 release notes (#1818)](https://github.com/elastic/ecs/pull/1818)
> [8.0] add 8.0.1 release notes (#1818)

- generated/elasticsearch/README.md
The fifth field, not the fourth (since `cut` is indexes from one, not zero), contains the component name. Having `cut` keep the fourth field makes all templates have the name "component".
With `cut -d/ -f4`:
```console
$ ls generated/elasticsearch/composable/component/*.json -1 | cut -d/ -f4 | cut -d. -f1 | tr A-Z a-z
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
component
```
With `cut -d/ -f5`:
```console
$ ls generated/elasticsearch/composable/component/*.json -1 | …
```
> generated/elasticsearch/README.md: Fix cut index

- CHANGELOG.next.md
- scripts/generators/es_template.py
This will backport the following commits from `main` to `8.1`:
- [Only generate documentation link in component template _meta for actual ecs fields (#1728)](https://github.com/elastic/ecs/pull/1728)
> [8.1] Only generate documentation link in component template _meta for actual ecs fields (#1728)

- CHANGELOG.next.md
- schemas/README.md
- scripts/generators/beats.py
- scripts/schema/cleaner.py
- scripts/tests/unit/test_beats_generator.py
- scripts/tests/unit/test_schema_cleaner.py
Introduces a new optional field definition attribute: `pattern`. The pattern attribute holds a regular expression (regex) which expresses the expected constraint on a string field's value.
```
pattern: '[.*]'
```
The ECS tooling checks the regex itself to ensure validity. However, The ECS tooling cannot evaluate the regex against provided field values.
Allow automated testing to use the regex found in the `pattern` fields against values populating ECS fields.
If specified, the regex value from `pattern` goes through a check using `re.compile` if the `--strict` flag is present. The generator will only generate a warning if `--strict` isn't specified.
The `pattern` field appears in the following generated artifacts:
* `generated/beats/fields.ecs.yml`
* `generated/ecs/ecs_flat.yml`
* …
> Add optional `pattern` attribute

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/email.yml
- [Remove brackets from `email.message.id` example (#1841)](https://github.com/elastic/ecs/pull/1841)
> [8.2] Remove brackets from `email.message.id` example (#1841)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/threat.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/threat.json
- generated/elasticsearch/legacy/template.json
- schemas/threat.yml
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? yes
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? yes
- If submitting code/script changes, have you verified all tests pass locally using `make test`? yes
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? yes
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. yes …
> CTI addendum threat.feed.name, threat.feed.dashboard_id

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/threat.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/threat.json
- generated/elasticsearch/legacy/template.json
- schemas/threat.yml
- [CTI addendum threat.feed.name, threat.feed.dashboard_id (#1844)](https://github.com/elastic/ecs/pull/1844)
> [8.2] CTI addendum threat.feed.name, threat.feed.dashboard_id (#1844)

- docs/release-notes/8.3.asciidoc
- docs/release-notes/index.asciidoc
Backports the following commits to 8.3:
- adding entry for 8.3 into release notes (#1858)
> [8.3] adding entry for 8.3 into release notes (#1858)

- CHANGELOG.next.md
- USAGE.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/host.yml
- schemas/observer.yml
- schemas/server.yml
- schemas/source.yml
- scripts/schema/cleaner.py
- scripts/tests/unit/test_schema_cleaner.py
- [Add pattern attribute to `.mac` fields (#1871)](https://github.com/elastic/ecs/pull/1871)
> [8.3] Add pattern attribute to `.mac` fields (#1871)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/orchestrator.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/orchestrator.json
- generated/elasticsearch/legacy/template.json
- schemas/orchestrator.yml
> Adding cluster.id to the orchestrator field set

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/orchestrator.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/orchestrator.json
- generated/elasticsearch/legacy/template.json
- schemas/orchestrator.yml
- [Adding cluster.id to the orchestrator field set (#1875)](https://github.com/elastic/ecs/pull/1875)
> [8.3] Adding cluster.id to the orchestrator field set (#1875)

- rfcs/text/0000-definition-of-ecs-compliance.md
- rfcs/text/0032-definition-of-ecs-compliance.md
This RFC PR proposes the project establishes a definition of an "ECS-compliant" event.
Addresses #1780
> [RFC] Proposal to define ECS-compliance - Stage 1

- CHANGELOG.next.md
- Makefile
- USAGE.md
- docs/fields/field-details.asciidoc
- docs/fields/fields.asciidoc
- docs/index.asciidoc
- scripts/generator.py
Adds a new argument, `--force-docs,` to the generator script. This option forces the ECS docs (`./docs` dir) to be generated even if `--subset,` `--include,` or `--exclude` are also set.
When `--subset` and `--include` flags were originally introduced, the generator would exit before generating the `./docs` files. The ECS docs are purpose-formatted for Elastic's doc framework. Users generating custom artifacts with `--include` and/or `--subset` are unlikely to use `./docs` as-is.
With the change introduced in https://github.com/elastic/ecs/pull/1847, the ECS docs aren't updating running `make.` The `--force-docs` option generates the `./docs` directory even if these custom options are also set.
> Add `--force-docs` option

- CHANGELOG.next.md
- Makefile
- USAGE.md
- docs/fields/field-details.asciidoc
- scripts/generator.py
- [Add `--force-docs` option (#1879)](https://github.com/elastic/ecs/pull/1879)
> [8.2] Add `--force-docs` option (#1879)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/orchestrator.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/orchestrator.json
- generated/elasticsearch/legacy/template.json
- schemas/orchestrator.yml
- [Adding orchestrator.resource.id (#1878)](https://github.com/elastic/ecs/pull/1878)
> [8.3] Adding orchestrator.resource.id (#1878)

- .github/workflows/add-to-ecs-project.yml
Use the API to automatically add opened or reopened issues to the ECS team's planning board. Also, it sets the status of any new items to `Triage.`
Inspiration taken from [GitHub docs](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/using-the-api-to-manage-projects#updating-projects).
> Populate project board with new issues

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
Note `process.env_vars` should not contain nested objects and use `keyword` for all field values.
These conventions are the same as the `label` field.
> [DOCS] Include constraints for `process.env_vars` object field

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
- [[DOCS] Include constraints for `process.env_vars` object field (#1884)](https://github.com/elastic/ecs/pull/1884)
> [8.3] [DOCS] Include constraints for `process.env_vars` object field (#1884)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
- [[DOCS] Include constraints for `process.env_vars` object field (#1884)](https://github.com/elastic/ecs/pull/1884)
> [8.2] [DOCS] Include constraints for `process.env_vars` object field (#1884)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/container.json
- experimental/generated/elasticsearch/composable/component/orchestrator.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/container.json
- generated/elasticsearch/composable/component/orchestrator.json
- generated/elasticsearch/legacy/template.json
- schemas/container.yml
- schemas/orchestrator.yml
- [Add orchestrator (resource.parent.type and resource.ip) and container (image.hash.all) fields (#1889)](https://github.com/elastic/ecs/pull/1889)
> [8.3] Add orchestrator (resource.parent.type and resource.ip) and container (image.hash.all) fields (#1889)

- CHANGELOG.next.md
- scripts/_types/__init__.py
- scripts/_types/schema_fields.py
- scripts/generator.py
- scripts/generators/ecs_helpers.py
- scripts/generators/intermediate_files.py
- scripts/schema/cleaner.py
- scripts/schema/exclude_filter.py
- scripts/schema/loader.py
- scripts/schema/subset_filter.py
- scripts/schema/visitor.py
- [Add type hints to schema modules (#1771)](https://github.com/elastic/ecs/pull/1771)
> [8.3] Add type hints to schema modules (#1771)

- CHANGELOG.next.md
- scripts/_types/__init__.py
- scripts/_types/schema_fields.py
- scripts/generator.py
- scripts/generators/ecs_helpers.py
- scripts/generators/intermediate_files.py
- scripts/schema/cleaner.py
- scripts/schema/exclude_filter.py
- scripts/schema/loader.py
- scripts/schema/subset_filter.py
- scripts/schema/visitor.py
- [Add type hints to schema modules (#1771)](https://github.com/elastic/ecs/pull/1771)
> [8.2] Add type hints to schema modules (#1771)

- CHANGELOG.next.md
- USAGE.md
- scripts/generator.py
- scripts/generators/asciidoc_fields.py
- scripts/schema/subset_filter.py
- scripts/tests/test_asciidoc_fields.py
- scripts/tests/unit/test_schema_subset_filter.py
- [Introduce "docs_only" attribute for subsets (#1909)](https://github.com/elastic/ecs/pull/1909)
> [8.3] Introduce "docs_only" attribute for subsets (#1909)

- CHANGELOG.next.md
- USAGE.md
- scripts/generator.py
- scripts/generators/asciidoc_fields.py
- scripts/schema/subset_filter.py
- scripts/tests/test_asciidoc_fields.py
- scripts/tests/unit/test_schema_subset_filter.py
- [Introduce "docs_only" attribute for subsets (#1909)](https://github.com/elastic/ecs/pull/1909)
> [8.2] Introduce "docs_only" attribute for subsets (#1909)

- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/agent.yml
Removing unnecessary guidance to address concerns discussed in #1915.
> Remove unnecessary guidance from `agent.name` description

- docs/using-ecs/guidelines/implementation.asciidoc
Correct this example usage of `related.ip` to use an array for the value: https://www.elastic.co/guide/en/ecs/current/ecs-principles-implementation.html#_related_fields.
Addresses #1918
> `related.ip` example should be an array

- docs/using-ecs/guidelines/implementation.asciidoc
- [`related.ip` example should be an array (#1922)](https://github.com/elastic/ecs/pull/1922)
> [8.3] `related.ip` example should be an array (#1922)

- docs/using-ecs/guidelines/implementation.asciidoc
- [`related.ip` example should be an array (#1922)](https://github.com/elastic/ecs/pull/1922)
> [8.2] `related.ip` example should be an array (#1922)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
- schemas/subsets/main.yml
- [Re-adding missing process fields (#1906)](https://github.com/elastic/ecs/pull/1906)
> [8.3] Re-adding missing process fields (#1906)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
- schemas/subsets/main.yml
- [Re-adding missing process fields (#1906)](https://github.com/elastic/ecs/pull/1906)
> [8.2] Re-adding missing process fields (#1906)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- rfcs/text/0025-container-metric-fields.md
- schemas/container.yml
Backports the following commits to 8.3:
- Container metrics GA (#1927)
> [8.3] Container metrics GA (#1927)

- docs/release-notes/8.4.asciidoc
- docs/release-notes/index.asciidoc
Backports the following commits to 8.4:
- adding 8.4 release notes section (#1940)
> [8.4] adding 8.4 release notes section (#1940)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/dns.yml
- schemas/faas.yml
- schemas/network.yml
- schemas/os.yml
- schemas/threat.yml
Define the `expected_values` parameter added in #1952.
This set of fields already defined expected or recommended values in the field descriptions.
* `dns.header_flags`
* `faas.trigger.type`
* `network.direction`
* `os.type`
* `threat.enrichments.indicator.type`
* `threat.enrichments.indicator.confidence`
* `threat.enrichments.indicator.marking.tlp`
* `threat.indicator.type`
* `threat.indicator.confidence`
* `threat.indicator.marking.tlp`
* `threat.software.platforms`
* `threat.software.type`
* Correct example from `White` to `WHITE` on `threat.enrichments.indicator.marking.tlp`.
> Define initial set of field `expected_values`

- CHANGELOG.md
- CHANGELOG.next.md
Backports the following commits to 8.4:
- finalizing changelog for 8.3 release (#1966)
> [8.4] finalizing changelog for 8.3 release (#1966)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/service.yml
As per https://github.com/elastic/ecs/issues/1965 , we are deprecating singular `service.node.role` in favor of upcoming plural `service.node.roles`.
> Deprecate service.node.role

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/service.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/service.json
- generated/elasticsearch/legacy/template.json
- schemas/service.yml
Backports the following commits to 8.4:
- Adding service.node.roles (#1981)
> [8.4] Adding service.node.roles (#1981)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/host.json
- experimental/generated/elasticsearch/composable/component/user.json
- experimental/generated/elasticsearch/legacy/template.json
- experimental/schemas/risk.yml
- experimental/schemas/subsets/experimental.yml
- rfcs/text/0031-risk-fields.md
Adding per https://github.com/elastic/ecs/pull/1744
> Adding `risk.*` fields as experimental

- docs/fields/field-details.asciidoc
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/os.yml
Closes #1995 
Adds `ios` and `android` as valid values for the `os.type` field to support mobile use cases (E.g. APM / distributed tracing in mobile devices).
/cc @simitt, @felixbarny
> Added `ios` and `android` as valid values for `os.type`

- CHANGELOG.next.md
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/schemas/risk.yml
- Fixing risk short fields (#2010)
> [8.5] Fixing risk short fields (#2010)

- docs/fields/field-details.asciidoc
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/os.yml
- Added `ios` and `android` as valid values for `os.type` (#1999)
> [8.5] Added `ios` and `android` as valid values for `os.type` (#1999)

- CHANGELOG.next.md
- rectify changelog 1999 (#2012)
> [8.5] rectify changelog 1999 (#2012)

- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- Fixes a typo in the client schema (#2014)
> [8.5] Fixes a typo in the client schema (#2014)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- docs/fields/fields.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/device.json
- experimental/generated/elasticsearch/composable/template.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/device.json
- generated/elasticsearch/composable/template.json
- generated/elasticsearch/legacy/template.json
- rfcs/text/0034-device-fields.md
- schemas/device.yml
- schemas/subsets/main.yml
> Device fields RFC stage 2 and schema change

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/process.yml
Updated the type of process.env_vars to be an array of string keywords
to support shadowed variables, i.e. duplicated names with different
values.
> Changed type of process.env_vars to show shadowing

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/process.yml
- Changed type of process.env_vars to show shadowing (#2038)
> [8.5] Changed type of process.env_vars to show shadowing (#2038)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- rfcs/text/0035-tty-output.md
- rfcs/text/0035/process.yml
- schemas/process.yml
- [RFC Stage-2] Process IO events (#2031)
> [8.5] [RFC Stage-2] Process IO events (#2031)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- docs/fields/fields.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/client.json
- experimental/generated/elasticsearch/composable/component/destination.json
- experimental/generated/elasticsearch/composable/component/server.json
- experimental/generated/elasticsearch/composable/component/source.json
- experimental/generated/elasticsearch/legacy/template.json
- experimental/schemas/subsets/experimental.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/client.json
- generated/elasticsearch/composable/component/destination.json
- generated/elasticsearch/composable/component/host.json
- generated/elasticsearch/composable/component/server.json
- generated/elasticsearch/composable/component/source.json
- generated/elasticsearch/composable/component/user.json
- generated/elasticsearch/legacy/template.json
- schemas/risk.yml
- schemas/subsets/main.yml
- Adding `risk.*` as beta (#2051)
> [8.5] Adding `risk.*` as beta (#2051)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/group.yml
- schemas/subsets/main.yml
- schemas/user.yml
- Add attested user and groups to process (#2050)
> [8.5] Add attested user and groups to process (#2050)

- CHANGELOG.next.md
Forward Port SFF 8.6 `CHANGELOG.next.md` to `main`
> Forward Port cut 8.6 SFF Changelog (#2071)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/threat.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/threat.json
- generated/elasticsearch/legacy/template.json
- schemas/threat.yml
Continuation of https://github.com/elastic/ecs/pull/2034
Addresses https://github.com/elastic/ecs/issues/2073
> Update to TLP

- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/subsets/main.yml
Followup to https://github.com/elastic/ecs/pull/2031 
Adding `io.*` fields to the subset file at top-level process
cc @mitodrummer
> Process io subset fix

- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/subsets/main.yml
- Process io subset fix (#2078)
> [8.6] Process io subset fix (#2078)

- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/subsets/main.yml
- Process io subset fix (#2078)
> [8.5] Process io subset fix (#2078)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/group.yml
- schemas/process.yml
- schemas/source.yml
- schemas/user.yml
- [8.5] Linux event model GA (#2082)
> [8.6] [8.5] Linux event model GA (#2082)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/group.yml
- schemas/process.yml
- schemas/source.yml
- schemas/user.yml
- [8.5] Linux event model GA (#2082)
> [8.5] [8.5] Linux event model GA (#2082)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- docs/fields/fields.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/dll.json
- experimental/generated/elasticsearch/composable/component/file.json
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/composable/component/threat.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/dll.json
- generated/elasticsearch/composable/component/file.json
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/composable/component/threat.json
- generated/elasticsearch/legacy/template.json
- schemas/elf.yml
- schemas/macho.yml
- schemas/pe.yml
- schemas/subsets/main.yml
Fields are added to ELF for malware detection signatures and fields in ELF for this are reflected in PE. A new Mac OS Mach-O field group is added. Not all possible fields are added to Mach-O.
Specific Go executable fields are added because the import structure of Go executables is not described in standard dynamic library imports and Go is a reasonably popular language both generally, and significantly, in malware.
See discussion at https://github.com/elastic/beats/pull/28802#discussion_r990525302.
Optimistically putting in 8.6, but happy to bump to 8.7 if this is too tight. If this needs an RFC will do that.
ELF:
PE:
The following are added to PE as analogous to the existing ELF fields. All bar virtual_size are strictly informative (`virtual_size` is always equal to `physical_size` since …
> Add fields for executable object format metadata for ELF, Mach-O and PE

- CHANGELOG.next.md
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
- scripts/tests/test_ecs_spec.py
This fixes an incorrectly typed `normalize` in `process.io.bytes_skipped` and adds a regression test to prevent this from happening in the future.
Please take a look.
> Fix type of normalize for process.io.bytes_skipped

- CHANGELOG.next.md
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
- scripts/tests/test_ecs_spec.py
- Fix type of normalize for process.io.bytes_skipped (#2094)
> [8.6] Fix type of normalize for process.io.bytes_skipped (#2094)

- CHANGELOG.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/process.yml
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? y
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? y
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. y …
> Fixes invalid 'number' type on 4 process.io subfields.

- CHANGELOG.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/process.yml
- Fixes invalid 'number' type on 4 process.io subfields. (#2105)
> [8.6] Fixes invalid 'number' type on 4 process.io subfields. (#2105)

- CHANGELOG.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/process.yml
- Fixes invalid 'number' type on 4 process.io subfields. (#2105)
> [8.5] Fixes invalid 'number' type on 4 process.io subfields. (#2105)

- docs/release-notes/8.5.2.asciidoc
- docs/release-notes/index.asciidoc
main forward-port of https://github.com/elastic/ecs/pull/2110
> [main] Release notes for 8.5.2 

- CHANGELOG.next.md
Cut the changelog in the HFF branch:
Change the title of the feature frozen release section from "8.x.0 (Soft Feature Freeze)" to indicate that the version is in hard feature freeze. Example: "8.1.0 (Hard Feature Freeze)"
Sort entries by PR ID within their sections.
Remove empty sections
Compare the changelog entries with the commits of the main branch,
to ensure no changelog is missing
Submit a PR with only the HFF changelog, to facilitate forward porting
> [elastic/ecs] Cutting 8.6 changelog for HFF

- CHANGELOG.next.md
This will backport the following commits from `8.6` to `main`:
- [[elastic/ecs] Cutting 8.6 changelog for HFF (#2114)](https://github.com/elastic/ecs/pull/2114)
> [main] [elastic/ecs] Cutting 8.6 changelog for HFF (#2114)

- CHANGELOG.next.md
- schemas/client.yml
> fixes #2219: remove the less documented domain field

- CHANGELOG.next.md
- scripts/requirements.txt
This will backport the following commits from `main` to `8.7`:
- [Bump gitpython from 3.1.27 to 3.1.30 in /scripts (#2139)](https://github.com/elastic/ecs/pull/2139)
> [8.7] Bump gitpython from 3.1.27 to 3.1.30 in /scripts (#2139)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/host.yml
Backports the following commits to 8.7:
- [8.7] Description for host.name updated (FQDN issue) (#2122)
> [8.7] [8.7] Description for host.name updated (FQDN issue) (#2122)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- docs/fields/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
This Pull Request adds a new value for the `event.category` : `api`. Events in this category correspond to API events propagated directly from the Operating System from either the native API function (for instance, OS callbacks from Windows or Linux), system calls, or also managed source of events (such as ETW for instance).
Resolves #2138
> Add the `api` value to `event.category`

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- docs/fields/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
This will backport the following commits from `main` to `8.7`:
- [Add the `api` value to `event.category` (#2147)](https://github.com/elastic/ecs/pull/2147)
> [8.7] Add the `api` value to `event.category` (#2147)

- CHANGELOG.next.md
- docs/fields/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
Currently, events categorized as `event.category: file` do not list `access` as an expected event type.
I believe this is likely an oversight when the ECS categorization fields were originally defined. This PR proposes adding `access` as one of the allowed types for `file`.
> Permit `event.type: access` for `event.category: file` events

- CHANGELOG.next.md
- scripts/generators/es_template.py
- scripts/tests/test_es_template.py
When attempting to create a custom mapping for a `date` (multi-)field, I found that the ECS tooling doesn't currently support providing the `ignore_malformed` and `format` mapping parameters. Even though there is some limited support for certain parameters, these are not consistent between the main field mapping and the multi-field mapping. E.g. the `normalizer` parameter is only available for multi-fields.
Instead of implementing specific parameters for my use case, this PR adds a new property `parameters` to provide any mapping parameter, both for the main field and for multi-fields, along with a minimal test for the multi-field generation code. The existing code can remain as-is, with the minimal sanity checking that is in place, for backwards compatibility.
> Mapping parameters

- .github/workflows/build_ecs_typescript.yml
This PR will add another workflow here, triggered after ECS release is published.
It starts another workflow, here: https://github.com/elastic/ecs-typescript/blob/main/.github/workflows/generate.yml
The goal is to have automated PRs whenever there is a new ECS release, which - after manual review - will be merged.
> Trigger elastic/ecs-typescript workflow after ecs-release is published

- CHANGELOG.md
- CHANGELOG.next.md
Forward port for https://github.com/elastic/ecs/pull/2184
> [8.7 forward port] Move 8.7.0 entries from CHANGELOG.next.md to CHANGELOG.md (#2184)

- rfcs/text/0038-event-kind-asset.md
- rfcs/text/0038/event.yml
This RFC proposes extending `event.kind` with an additional allowed value, `asset`. For the Entity Analytics project, we are looking to identify user, host, and other types of entity assets.
> [RFC] Extend event.kind allowed values with asset

- docs/release-notes/8.8.asciidoc
- docs/release-notes/index.asciidoc
forward port of https://github.com/elastic/ecs/pull/2209
> [main] adding release notes for ecs 8.8 (#2209)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/container.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/container.json
- generated/elasticsearch/legacy/template.json
- schemas/container.yml
> Added `container.privileged` field

- docs/fields/field-details.asciidoc
- docs/fields/field-values.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
New PR to properly generate docs by better following the contributing guide.
Added "is" to clear up a sentence and made more fields stick out using the ` characters which makes it more consistent with the rest of the documentation.
Cancels #2220
> [Event] Clean up Event fields

- docs/fields/field-details.asciidoc
- docs/fields/field-values.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
This will backport the following commits from `main` to `8.9`:
- [Clean up Event fields (#2226)](https://github.com/elastic/ecs/pull/2226)
> [8.9] Clean up Event fields (#2226)

- docs/fields/field-details.asciidoc
- docs/fields/field-values.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
This will backport the following commits from `main` to `8.8`:
- [Clean up Event fields (#2226)](https://github.com/elastic/ecs/pull/2226)
> [8.8] Clean up Event fields (#2226)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/container.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/container.json
- generated/elasticsearch/legacy/template.json
- schemas/container.yml
> Fix privileged flag

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/process.yml
- schemas/subsets/main.yml
Being able to gather and track Linux capabilities for a process (thread) could allow us to detect and prevent various activities such as container escapes, privilege escalation and exploitation.
> Add process.thread.capabilities

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/container.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/container.json
- generated/elasticsearch/legacy/template.json
- schemas/container.yml
My previous PR had the wrong type name.
bool -> boolean
> container.security context.privileged boolean

- rfcs/text/0042-risk-score-extensions.md
- rfcs/text/0042/risk.yml
> [RFC] Risk Score Extensions - Stage 1

- scripts/requirements.txt
This will backport the following commits from `main` to `8.10`:
- [Bump gitpython from 3.1.30 to 3.1.32 in /scripts (#2251)](https://github.com/elastic/ecs/pull/2251)
> [8.10] Bump gitpython from 3.1.30 to 3.1.32 in /scripts (#2251)

- CHANGELOG.next.md
- scripts/requirements.txt
This will backport the following commits from `main` to `8.10`:
- [Bump gitpython from 3.1.32 to 3.1.34 in /scripts (#2264)](https://github.com/elastic/ecs/pull/2264)
> [8.10] Bump gitpython from 3.1.32 to 3.1.34 in /scripts (#2264)

- CHANGELOG.next.md
- scripts/requirements.txt
This will backport the following commits from `main` to `8.10`:
- [Bump gitpython from 3.1.34 to 3.1.35 in /scripts (#2265)](https://github.com/elastic/ecs/pull/2265)
> [8.10] Bump gitpython from 3.1.34 to 3.1.35 in /scripts (#2265)

- rfcs/text/0040-volume-device.md
- rfcs/text/0040/volume.yml
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? Yes
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? Yes
- If submitting code/script changes, have you verified all tests pass locally using `make test`? N/A
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? N/A
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. Yes …
> [RFC] Stage 2 for volume device

- CHANGELOG.md
- CHANGELOG.next.md
> [main] Finalize 8.10 changelog (#2271)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/threat.yml
The `threat.indicator.name` and `threat.enrichments.indicator.name` are misusing the `expected_value` parameter in their field definitions. This change removes `expected_value`.
I propose the removal is a bug fix vs. a breaking change since the current `expected_values` on these fields is not useful for real-world applications.
> Remove `expected_values` from *.indicator.name field defs

- scripts/requirements.txt
This will backport the following commits from `main` to `8.11`:
- [Bump gitpython from 3.1.35 to 3.1.37 in /scripts (#2292)](https://github.com/elastic/ecs/pull/2292)
> [8.11] Bump gitpython from 3.1.35 to 3.1.37 in /scripts (#2292)

- CHANGELOG.md
Correcting erroneous entry for PR https://github.com/elastic/ecs/pull/2269 in the 8.11 changelog (& moved to 8.12)
> [8.11] Removing entry for volume field set addition

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
Promote process.env_vars to GA. This field has been stabilized and in use for some time now, so it should be promoted to GA status.
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?  ✅
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? ✅
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? N/A
- If submitting code/script changes, have you verified all tests pass locally using `make test`? ✅
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? ✅
- Is your pull request against main? Unless there is a good reason …
> Promote process.env_vars to GA

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
Remove process.io and process.tty fields from beta, and promote to GA.
These fields have stabilized and are used in released features, so they can leave beta.
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? ✅
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? ✅
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process] (https://github.com/elastic/ecs/blob/main/rfcs/README.md)? N/A
- If submitting code/script changes, have you verified all tests pass locally using `make test`? ✅
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? ✅
- Is your pull request against main? Unless …
> Promote process.io and process.tty fields to GA

- CONTRIBUTING.md
The feature freeze process included in `CONTRIBUTING.md` is out-of-date. Also added a description of the `schemas/subsets` file and their function.
> Update `CONTRIBUTING` doc

- .github/workflows/docs-preview-comment.yml
Following the migration from Jenkins to Buildkite, docs previews are now available at <repo>_bk_<PR>.
More context in https://github.com/elastic/docs/pull/2898
Note - a shared GH action can also be found here: https://github.com/elastic/docs/tree/master/.github/actions/docs-preview
- If submitting schema/fields updates, have you …
> Update docs-preview link

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/threat.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/threat.json
- generated/elasticsearch/legacy/template.json
- schemas/threat.yml
**Note: This is a recreated PR from https://github.com/elastic/ecs/pull/2307. See [comment](https://github.com/elastic/ecs/pull/2307#issuecomment-2023092713) for reason.**
Added `threat.indicator.id` field. Resolves #2252.
The new field `threat.indicator.id` will allow for security systems to append a threat.indicator.id. This field can have multiple values to allow for the identification of the same indicator across systems that use different ID formats.
Common serialization format you may expect to see here is a STIX 2.x indicator id. Here is an example of one being produced.
```json
{
"type": "indicator",
"spec_version": "2.1",
"id": "indicator--8a8c60c4-00a8-43dd-ad76-8004ee718c39",
"created": "2023-12-21T17:55:29.187214Z",
"modified": "2023-12-21T17:55:29.187214Z",
"name": "Malicious …
```
> [RFC] added new field: threat.indicator.id - resolves GH-2252

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/vulnerability.yml
The current link for vulnerability.id is: https://cve.mitre.org/about/faqs.html#what_is_cve_id) which is a broken link.
This PR makes the link useable as: https://cve.mitre.org/about/faqs.html#what_is_cve_id
> Fix broken link for vulnerabilty.id (correct commits)

- CHANGELOG.next.md
- CONTRIBUTING.md
- README.md
Elastic has [announced](https://www.elastic.co/blog/ecs-elastic-common-schema-otel-opentelemetry-faq) that it will donate ECS to the OpenTelemetry Semantic Conventions. In this announcement, we shared our intention to achieve convergence of ECS and OTel Semantic Conventions into a single standard maintained by OpenTelemetry.
This documentation provides the process and guidelines for contributing to ECS during the OTel donation process.
> Special guidance for ECS contributions during OTel donation

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/subsets/main.yml
Add `process.group` fields as the effective group for the process schema. `process.group` was (probably mistakenly) being excluded from the schema, as it wasn't part of `schemas/subsets/main.yml`. The other related process group fields are already included in the schema (real_group, saved_group), and `process.group` is defined with field re-use in [group.yml](https://github.com/elastic/ecs/blob/main/schemas/group.yml#L32-L34).
---
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README …
> Add `process.group` fields to generated schemas

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/process.yml
Related PR: https://github.com/elastic/integrations/pull/9850
This PR aims to add a subfield to the `process.name` and `process.executable` fields to improve the compatibility of data sources like System, Sysmon, etc., with our Elastic Defend data. This enables us to handle language limitations in KQL more effectively.
Elastic Defend Mapping:
> Add .caseless subfield to process.name & process.executable

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/process.yml
Reverts elastic/ecs#2341
This is being reverted due to storage concerns. The goal will be to advance the native querying capabilities (ES|QL, KQL) of the Elastic stack such that this extra normalized multi-field is not necessary. In the meantime, localized overrides of the ECS field definition will be used to add the additional multi-field where needed. The downside of localized overrides are that it creates inconsistency across usages of the this field.
> Revert "Add .caseless subfield to process.name & process.executable"

- .github/workflows/stale.yml
Add a friendlier stale PR message, based from the [Beats stale message](https://github.com/elastic/beats/blob/main/.github/stale.yml#L63-L74).
This will hopefully also prompt contributors to respond, so we'll be better able to track PRs people are still interested in contributing.
--- 
- If submitting schema/fields …
> Update the stale PR bot message

- .github/workflows/stale.yml
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/device.json
- experimental/generated/elasticsearch/composable/component/dll.json
- experimental/generated/elasticsearch/composable/component/email.json
- experimental/generated/elasticsearch/composable/component/file.json
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/composable/component/threat.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/device.json
- generated/elasticsearch/composable/component/dll.json
- generated/elasticsearch/composable/component/email.json
- generated/elasticsearch/composable/component/file.json
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/composable/component/threat.json
- generated/elasticsearch/legacy/template.json
- rfcs/text/0044-add-apple-platform-specific-fields.md
- schemas/code_signature.yml
- schemas/device.yml
- schemas/hash.yml
- schemas/process.yml
Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes
Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? Yes
For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? Yes
If submitting code/script changes, have you verified all tests pass locally using make test? N/A
If submitting schema/fields updates, have you generated new artifacts by running make and committed those changes? N/A
Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. Yes
Have you added an entry to the …
> [RFC] Stage 2: Adding Apple Platform specific fields

- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/dll.json
- experimental/generated/elasticsearch/composable/component/file.json
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/composable/component/threat.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/dll.json
- generated/elasticsearch/composable/component/file.json
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/composable/component/threat.json
- generated/elasticsearch/legacy/template.json
- rfcs/text/0044/code_signature.yml
- schemas/code_signature.yml
- scripts/tests/test_ecs_spec.py
Change the type of `code_signature.flags` to `keyword`, which is what it should be. Also add a unit test that will verify all types are valid.
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?   ✅
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? ✅
- If submitting code/script changes, have you verified all tests pass locally using `make test`? ✅
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? ✅
- Is your pull request against main? Unless there is a good …
> Fix type in code signature

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/x509.yml
This proposes enforcing the base encoding of x509.serial_number to be 16.
The current definition is too loose and leaves room for interpretation, base 16 is also more common and it will help users correlate the value with existing tools. This change was prompted by elastic/sdh-beats#5089 where a customer expected to see it in the same format as other tools.
Particularly relevant comment from @andrewkroh here:  https://github.com/elastic/sdh-beats/issues/5089#issuecomment-2349046226
Narrow the definition of x509.serial_number to be encoded in hexadecimal, otherwise we end up with integrations choosing their own encoding, as noted below, Zeek uses base 16 while the rest of beats is using base 10.
> Define base encoding in x509.serial_number

- CHANGELOG.md
- CHANGELOG.next.md
Finalize 8.16.0 changelog
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. n/a
- Have you added an entry to …
> Finalize 8.16.0 changelog

- docs/release-notes/8.16.asciidoc
- docs/release-notes/index.asciidoc
Add 8.16 release notes
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. n/a
- Have you added an entry to …
> Add 8.16 release notes

- USAGE.md
The example for template.json in the usage doc for the custom template and mapping setting section was incorrect and did not work for both template types. This fixes the example to work with both.
--- …
> Update template example in usage doc

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/dns.yml
- schemas/elf.yml
- schemas/macho.yml
- schemas/pe.yml
- schemas/server.yml
- schemas/source.yml
- schemas/url.yml
- schemas/vulnerability.yml
- Removed link text markup, causes issues since final rendering of docs can be in either markdown or asciidoc
- Replace http with https in links
- #2416
> Fix link rendering issues and usage of http in links

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/dns.yml
- schemas/elf.yml
- schemas/macho.yml
- schemas/pe.yml
- schemas/server.yml
- schemas/source.yml
- schemas/url.yml
- schemas/vulnerability.yml
- Removed link text markup, causes issues since final rendering of docs can be in either markdown or asciidoc
- Replace http with https in links
> [Backport 8.x] Fix link rendering issues and usage of http in links

- docs/docset.yml
- docs/reference/ecs-conventions.md
- docs/reference/ecs-faq.md
- docs/reference/ecs-products-solutions.md
Related to https://github.com/elastic/logstash/pull/17405 
Updates Logstash plugin link.
✨  **Bonus**: Updates a couple redirecting links related to https://github.com/elastic/elasticsearch/pull/125663 ✨
> [docs] Update Logstash plugin link

- docs/reference/ecs-converting.md
Fixes image paths to work with docs-assembler.
Notes for the reviewer:
* I was not able to get images in reference, extend, or release-notes to work using the `:::{image}` syntax because it seems to resolve differently than the Markdown `![]()` syntax. We should address this in docs-builder, but in order to get images working as soon as possible, I've used Markdown syntax and left us a `TO DO` in a code comment to add back the `screenshot` class where applicable. 
* Can you please add the appropriate labels needed for backporting?
> [docs] Fix image paths for docs-assembler

- .github/workflows/docs-build.yml
This is needed to start onboarding `9.0` to the documentation build
https://github.com/elastic/docs-builder/pull/1180
Requires:
https://github.com/elastic/docs-builder/pull/1297
https://github.com/elastic/docs-builder/pull/1299
To be merged before merging and backporting this to `9.0`
> Ensure docs are build for version branches

- CONTRIBUTING.md
Most of the content still seems relevant to me. I removed the rebase instructions per the [issue](https://github.com/elastic/integration-experience/issues/142), but also added a note that we want a changelog entry for PRs. 
Closes https://github.com/elastic/integration-experience/issues/142
> Updating the Git/GitHub guidelines

- CONTRIBUTING.md
A couple small updates to the Submitting changes section of the Contributing guide: 1) adding a note to run make check and 2) providing more information on what we expect to be included in the submitted PR from the Git/Github guidelines section of the guide.  
Closes https://github.com/elastic/integration-experience/issues/141
> Updates to the submitting changes section of the contributing guide

- docs/release-notes/index.md
Backport 9.1.0 release notes into the 9.1 branch.
> [backport 9.1] Add 9.1.0 release notes to docs (#2544)
