elastic/ecs

- scripts/schemas.py
- scripts/use-cases.py
Fixes `make` on systems where Python 3 is default.
> Update scripts for Python 3 compatibility

- README.md
- schema.csv
- schemas/agent.yml
- schemas/base.yml
- schemas/cloud.yml
- schemas/container.yml
- schemas/destination.yml
- schemas/device.yml
- schemas/error.yml
- schemas/event.yml
- schemas/file.yml
- schemas/geoip.yml
- schemas/host.yml
- schemas/kubernetes.yml
- schemas/log.yml
- schemas/network.yml
- schemas/organization.yml
- schemas/os.yml
- schemas/process.yml
- schemas/service.yml
- schemas/source.yml
- schemas/url.yml
- schemas/user.yml
- schemas/user_agent.yml
- template.json
Schema file edits (YAML)
Contains `schema.csv` and `template.json` which I did not mean to include.  Thought I had unstaged them, but it didn't work.
> [DISCUSS]  Edits to schema YAML files

- README.md
- docs/about.md
Small change to readme file.  This PR is more of a test of GitHub process on my new MacBook setup. Only line 508 is changed.  Other diffs seem to be artifacts of my editor (Atom).
> Tweak to README.md

- CHANGELOG.md
- README.md
- schema.csv
- schemas/http.yml
- template.json
Should fix https://github.com/elastic/ecs/issues/41 Please review
> Add http.request.method and http.version

- scripts/helper.py
This opens up the possibility to add other files like localized READMEs in the future...
But the real reason is that I use Vim, and the generator barfed on Vim swapfiles ;-)
> Force the generator to load only yaml files under schema/

- README.md
- schema.csv
- schemas/event.yml
- template.json
> Clarify event.risk_score, add normalized field.

- scripts/schemas.py
- scripts/template.go
Very similar to #88. Hadn't been hit by this one yet :-)
> Fix the glob to load schemas in `template.go` as well.

- README.md
- scripts/helper.py
- use-cases/apm.md
- use-cases/auditbeat.md
- use-cases/beats.md
- use-cases/filebeat-apache-access.md
- use-cases/kubernetes.md
- use-cases/logging.md
- use-cases/metricbeat.md
- use-cases/tls.md
It's currently 100% empty. Also, the script as it is now is already displaying
them by rendering additional rows anyway.
> Remove the 'Multi Field' column

- fields.yml
- schemas/geo.yml
- schemas/os.yml
- schemas/user.yml
- scripts/helper.py
The shorter word appears to be used 40x more than the longer one
(according to Google) :-)
> Use word reusable rather than reuseable.

- scripts/template.go
Method signature for `template.New` changed in Beats recently.
Closes #199
> Fix template generation

- Makefile
Will be helpful to force updates, after changes like #202
> Add `go get -u` commands to `make setup` to force update the go deps.

- README.md
- schema.csv
- scripts/helper.py
- use-cases/filebeat-apache-access.md
- use-cases/web-logs.md
Closes https://github.com/elastic/ecs/issues/250
> Fix that non index field are shown with keyword in table

- Makefile
- scripts/template.go
- template.json
Move the version variable to the Makefile.
> Add VERSION variable to Makefile

- CONTRIBUTING.md
In preparation for the intro blog post.
> Minor tweaks to contributor guidelines

- TODO.md
Cherry-pick of PR #273 to 1.0 branch.
> Backport: Remove the obsolete TODO file (#273)

- CONTRIBUTING.md
Backport of PR #319 to 1.0 branch.
> Backport #319 to 1.0: Minor tweaks to contributor guidelines (#319)

- .backportrc.json
- .gitignore
Add support for https://github.com/sqren/backport backport tool.
> Add backport script config

- CHANGELOG.md
> Backport #325 to 1.0: clarify host definition wording (#325)

- CHANGELOG.md
- fields.yml
- schemas/base.yml
Backport of PR #331 to 1.0 branch.
> Backport #331 to 1.0: Specify the `object_type` for field `labels`. (#331)

- generated/elasticsearch/README.md
Backport of PR #346 to 1.0 branch.
> Backport #346 to 1.0: Simple steps to experiment with the Elasticsearch ECS templates (#346)

- CHANGELOG.md
- README.md
- fields.yml
- generated/legacy/schema.csv
- schemas/url.yml
Backport of PR #339 to 1.0 branch.
> Backport #339 to 1.0: Change url.port datatype to long (#339)

- Makefile
- generated/legacy/template.json
- scripts/template.go
Backport of PR #279 to 1.0 branch. Original message:
Move the version variable to the Makefile.
> Backport #279 to 1.0: Add VERSION variable to Makefile (#279)

- CHANGELOG.md
- CHANGELOG.next.md
Backport of PR #378 to 1.0 branch.
> Backport #378 to 1.0: Add changelog.next.md for all new entries (#378)

- docs/index.asciidoc
This PR adds a title for the book so that it matches other books in the library. 
If "Overview" isn't an appropriate replacement for the subsection, it can be changed.
> [DOCS] Adds book title

- docs/index.asciidoc
> Backport #397 to 1.0: [DOCS] Adds book title (#397)

- docs/index.asciidoc
I knew I'd get bit by this not being generated.
I didn't know it would happen this fast :facepalm:
> Fix version at the top of the docs.

- docs/field-details.asciidoc
- scripts/generators/asciidoc_fields.py
Backport of PR #406 to 1.0 branch.
> Backport #406 to 1.0: Fix links to reused fields at the bottom of field set detail pages

- Makefile
Backport of PR #435 to 1.0 branch
> Backport #435 to 1.0: Adjust make targets for documentation to use docker/asciidoctor

- CHANGELOG.next.md
Add missing changelog for #486
cc @thomas ;-)
> Add missing changelog for #486

- Makefile
- schema.json
The schema.json was not being rebuilt when `make` was executed.
> Update schema.json on 'make'

- schema.json
- scripts/generator.py
- scripts/schema_reader.py
- scripts/tests/test_ecs_spec.py
- scripts/tests/test_schema_reader.py
- Keep the ECS file glob encapsulated, to avoid relative path mistakes
- Rename variables to better represent that they're no longer necessarily ECS per se
- tweak description of the CLI argument
> A few tweaks on top of recent work to include external dirs

- code/go/ecs/process.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schema.json
- schemas/process.yml
> Added process.thread.name

- CHANGELOG.next.md
Add missing changelog entry for #517
> Add missing changelog entry for #517

- docs/index.asciidoc
This file has moved. Also, we'd prefer to link to the last released
version.
> Docs: Update an include file (backports #550)

- CHANGELOG.next.md
- code/go/ecs/observer.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schema.json
- schemas/observer.yml
This PR is meant to finalize the work on #557 by applying the feedback in time
for ECS 1.2.0. Thanks for getting this started, @mbudge!
Closes #557
> Add observer.name and observer.product

- CHANGELOG.md
- CHANGELOG.next.md
We were missing an entry for #533
> Cut changelog for 1.2.0

- code/go/ecs/package.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schema.json
- schemas/package.yml
> Slight clarification of the wording for package.reference

- docs/index.asciidoc
- docs/products-solutions.asciidoc
Adds links to SIEM and Endpoint server on the Products and Solutions that Support ECS page, as requested in #619.
> Adds links to the SIEM app and Endpoint server

- CHANGELOG.next.md
- code/go/ecs/process.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/legacy/template.json
- schema.json
- schemas/process.yml
Backport of PR #615 to 1.3 branch.
> Backport #615 to 1.3: Added `process.args_count`

- docs/index.asciidoc
- docs/products-solutions.asciidoc
Backport of PR #622 to 1.3 branch.
> Backport #622 to 1.3: Adds links to the list of products that support ECS

- generated/csv/fields.csv
- scripts/generators/csv_generator.py
This ensures it's easy to have the column as a boolean in Elasticsearch.
This is a follow-up to #621.
> Make the 'Index' column lowercase.

- code/go/ecs/package.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/package.yml
Backport of PR #614 to 1.3 branch.
> Backport #614 to 1.3: Slight clarification of the wording for package.reference

- CHANGELOG.md
- CHANGELOG.next.md
> Forward port the 1.3.0 changelog to master

- code/go/ecs/dns.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schema.json
- schemas/dns.yml
Backport of PR #655 to 1.2 branch.
> Backport #655 to 1.2: Fix typo in DNS fields documentation

- code/go/ecs/vulnerability.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/vulnerability.yml
Adds URL labels to fix table formatting in https://www.elastic.co/guide/en/ecs/current/ecs-vulnerability.html.
Closes #659 
[Preview](http://ecs_660.docs-preview.app.elstc.co/guide/en/ecs/master/ecs-vulnerability.html)
> [ECS] [Docs] Quick fix for table formatting

- code/go/ecs/dns.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/dns.yml
Backport of PR #655 to 1.3 branch.
> Backport #655 to 1.3: Fix typo in DNS fields documentation

- code/go/ecs/dns.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schema.json
- schemas/dns.yml
Backport of PR #655 to 1.1 branch.
> Backport #655 to 1.1: Fix typo in DNS fields documentation

- code/go/ecs/vulnerability.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/vulnerability.yml
Backport of PR #660 to 1.3 branch.
> Backport #660 to 1.3: Format URLs in vulnerability, to fix table formatting

- CHANGELOG.next.md
- code/go/ecs/event.go
- docs/field-details.asciidoc
- docs/field-values.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- scripts/generators/asciidoc_fields.py
Backport of PR #692 to 1.4 branch.
> Backport #692 to 1.4: Introduce the initial values for ECS categorization

- code/go/ecs/related.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/related.yml
Also use an actual IP, in an example in the field set description.
> Add `related.hash`.

- CHANGELOG.next.md
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
> changelog for python 3 PR

- docs/using-custom-fields.asciidoc
- docs/using.asciidoc
[Preview of the new page](http://ecs_713.docs-preview.app.elstc.co/guide/en/ecs/master/ecs-custom-fields-in-ecs.html)
> Add a documentation section about custom fields

- generated/beats/fields.ecs.yml
- scripts/generators/beats.py
- scripts/generators/beats_default_fields_whitelist.yml
Backport of PR #717 to 1.4 branch.
> Backport #717  to 1.4: Beats: Set default_field=false in multi_fields

- CONTRIBUTING.md
* Table of contents
* Git/Github guidelines
* Documentation and Additional Information sections.
* Bullet point for ensuring tests pass with `make check`
* Link to CLA
* Minor adjustments to existing wording
> Updating Contributing Guidelines

- USAGE.md
Submitting some additional improvements to new usage docs as a follow-up from #884.
- Incorporating some additional feedback post-merge from #884 
- documenting the updated `--subset` functionality & declaration from #873
> Usage documentation improvements

- CHANGELOG.next.md
- code/go/ecs/client.go
- code/go/ecs/destination.go
- code/go/ecs/dns.go
- code/go/ecs/event.go
- code/go/ecs/server.go
- code/go/ecs/source.go
- code/go/ecs/url.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/client.yml
- schemas/destination.yml
- schemas/dns.yml
- schemas/event.yml
- schemas/server.yml
- schemas/source.yml
- schemas/tls.yml
- schemas/url.yml
Backports the following commits to 1.5:
- Use appropriate reserved domain for example URLs (#910)
> [1.5] Use appropriate reserved domain for example URLs (#910)

- CHANGELOG.md
- code/go/ecs/related.go
- docs/field-details.asciidoc
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- schemas/related.yml
> [1.6] add related.hosts (#913)

- docs/products-solutions.asciidoc
- docs/using-getting-started.asciidoc
This is a backport of #908 to the 1.6 branch.
> [1.6][DOCS] Fixes SIEM links

- docs/products-solutions.asciidoc
Backports https://github.com/elastic/ecs/pull/908
> [1.4][DOCS] Fixes SIEM links

- docs/products-solutions.asciidoc
> [1.3][DOCS] Fixes SIEM links

- docs/products-solutions.asciidoc
- docs/using-getting-started.asciidoc
Backports https://github.com/elastic/ecs/pull/908
> [1.5][DOCS] Fixes SIEM links

- .backportrc.json
- CONTRIBUTING.md
Two updates for improving backporting support:
* Update the backport project config to capture the newer release branches and branching strategy.
* Capture branching strategy and basic tooling usage.
> Improve backport support

- CHANGELOG.next.md
- docs/field-details.asciidoc
- docs/field-values.asciidoc
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- Add event category configuration (#963)
> [1.x] Add event category configuration (#963)

- docs/converting.asciidoc
* Mention ECS Mapper in the main documentation (#987)
> [1.x] Mention ECS Mapper in the main documentation (#987)

- docs/field-details.asciidoc
- scripts/templates/field_details/field_reuse_section.j2
- scripts/templates/field_details/nestings_table_header.j2
- scripts/templates/field_details/table_header.j2
> [1.6][DOCS] Adding discrete markers

- docs/field-details.asciidoc
> [1.5][DOCS] Adding discrete markers

- docs/field-details.asciidoc
> [1.4][DOCS] Adding discrete markers

- docs/field-details.asciidoc
> [1.3][DOCS] Adding discrete headers

- docs/field-details.asciidoc
> [1.2][DOCS] Adding discrete markers

- docs/field-details.asciidoc
> [1.1][DOCS] Adding discrete markers

- CHANGELOG.md
- CHANGELOG.next.md
> [master] Cut 1.7 changelog (#1010)

- .backportrc.json
> Add 1.7 as a backport target branch

- CHANGELOG.next.md
- docs/field-details.asciidoc
- docs/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
Adding this category has been mentioned in the "session" RFC (#935).
I'm not sure we need to wait for the RFC to introduce the category itself, however. This was one of the early categories we were considering, and is already in use in places like Elastic Endpoint.
> Add event.category session.

- USAGE.md
> Add constant_keyword to OSS fallback types list

- Makefile
* New default make task that generates main and experimental artifacts. (#1041)
> [1.x] New default make task that generates main and experimental artifacts. (#1041)

- Makefile
* New default make task that generates main and experimental artifacts. (#1041)
> [1.7] New default make task that generates main and experimental artifacts. (#1041)

- CHANGELOG.md
- experimental/generated/elasticsearch/7/template.json
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/README.md
- scripts/generators/es_template.py
* Change the index pattern in the sample template. (#1048)
> [1.x] Change the index pattern in the sample template.

- CHANGELOG.md
- experimental/generated/elasticsearch/7/template.json
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/README.md
- scripts/generators/es_template.py
* Change the index pattern in the sample template. (#1048)
> [1.7] Change the index pattern in the sample template.

- scripts/generators/asciidoc_fields.py
Backports the following commits to 1.4:
- [1.5] Add [discrete] headers to Asciidoc generator (#1089)
> [1.4] Add [discrete] headers to Asciidoc generator (#1089)

- scripts/generators/asciidoc_fields.py
Backports the following commits to 1.3:
- [1.5] Add [discrete] headers to Asciidoc generator (#1089)
> [1.3] Add [discrete] headers to Asciidoc generator (#1089)

- rfcs/text/0005-host-metric-fields.md
Forgot to assign the date, when merging #1028
> Set the merge date on RFC 0005 stage 2

- rfcs/text/0002-rfc-environment.md
Improvement of the RFC for the Service Environment Field
[RFC Preview](https://github.com/elastic/ecs/blob/service-environment-field-rfc-improvement/rfcs/text/0002-rfc-environment.md)
> [RFC] Service Environment Field - stage 1

- CONTRIBUTING.md
> Add section about jinja2 whitespace control

- CHANGELOG.next.md
- docs/additional.asciidoc
- docs/artifacts.asciidoc
- docs/index.asciidoc
- docs/using-conventions.asciidoc
> [1.x] Artifacts docs page (#1189)

- .backportrc.json
> Add 1.8 branch to backport config

- CHANGELOG.next.md
- code/go/ecs/cloud.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/cloud.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/cloud.json
- schemas/cloud.yml
- add cloud.service.name (#1204)
> [1.x] add cloud.service.name (#1204)

- CHANGELOG.next.md
Relocate changelog entry for #1169 to `Unreleased` section.
> Relocate `hash.ssdeep` changelog entry

- rfcs/text/0002-rfc-environment.md
Update the service environment field RFC proposal's stage naming to align with new RFC [proposal stages](https://elastic.github.io/ecs/stages.html).
> [RFC] Service Environment Field - Update to align with new proposal stages

- docs/field-values-usage.asciidoc
- docs/field-values.asciidoc
- scripts/templates/field_values.j2
- Add categorization fields usage docs (#1242)
> [1.x] Add categorization fields usage docs (#1242)

- CHANGELOG.md
- CHANGELOG.next.md
> Cut 1.8 changelog

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- experimental/schemas/as.yml
- experimental/schemas/file.yml
- experimental/schemas/geo.yml
- experimental/schemas/hash.yml
- experimental/schemas/pe.yml
- experimental/schemas/registry.yml
- experimental/schemas/threat.yml
- Stage 1 experimental changes for RFC 0008 - threat.indicator fields (#1268)
> [1.x] Stage 1 experimental changes for RFC 0008 - threat.indicator fields (#1268)

- CHANGELOG.next.md
* Cut 1.9 FF CHANGELOG.next.md #1277
> [master] Cut 1.9 FF CHANGELOG.next.md (#1277)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/orchestrator.json
- experimental/generated/elasticsearch/template.json
- experimental/schemas/orchestrator.yml
- Stage 1 experimental changes for RFC 0012 - orchestrator fieldset (#1292)
> [1.x] Stage 1 experimental changes for RFC 0012 - orchestrator fieldset (#1292)

- CHANGELOG.next.md
- docs/field-values.asciidoc
- docs/products-solutions.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- scripts/go.sum
To better align with the security solution product naming, these are some description updates to Elastic Security from Elastic SIEM.
> Updating descriptions to Elastic Security

- rfcs/text/0005-host-metric-fields.md
This PR is to move adding host metric fields RFC from candidate to finished.
> Move host metric fields RFC to finished

- CHANGELOG.md
- CHANGELOG.next.md
> [1.x] Cut 1.9 changelog (#1328)

- rfcs/0000-rfc-template.md
- rfcs/PROCESS.md
Adding in mention of the RFC folder to the guidance on RFCs
> adding process info on rfc folder

- CHANGELOG.next.md
- rfcs/text/0018-extend-threat-group-software.md
- rfcs/text/0018/threat.yml
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/master/CONTRIBUTING.md)? Yes
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/master/rfcs/README.md)? Yes
- If submitting code/script changes, have you verified all tests pass locally using `make test`? NA
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? Yes
- Is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. Yes …
> [RFC] Extend Threat Fieldset - Stage 1

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- experimental/schemas/threat.yml
- Stage 1 experimental changes for RFC 0018 - extend threat fieldset (#1344)
> [1.x] Stage 1 experimental changes for RFC 0018 - extend threat fieldset (#1344)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- scripts/templates/field_details.j2
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/master/rfcs/README.md)? n/a
- If submitting code/script changes, have you verified all tests pass locally using `make test`? Y
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? Y
- Is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. Y …
> Adjustments to the field set "usage" docs

- rfcs/text/0000-rpc-fieldset.md
- rfcs/text/0019-rpc-fieldset.md
I would like to propose a new `rpc` fieldset, for capturing details of a remote procedure call such as gRPC service and method name, and status code.
> Stage 0 RFC for `rpc` fieldset

- CHANGELOG.next.md
- docs/field-details.asciidoc
- docs/usage/README.md
- docs/usage/user.asciidoc
- scripts/templates/field_details.j2
- Adjust field set usage docs sidebar links (#1354)
> [1.x] Adjust field set usage docs sidebar links (#1354)

- CHANGELOG.next.md
> [master] Cut 1.10 changelog (#1371)

- CHANGELOG.next.md
- code/go/ecs/process.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/process.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/process.json
- schemas/process.yml
> Revert "Add `user` to process schema"

- rfcs/text/0018-extend-threat-group-software.md
The date wasn't updated when merging #1395
> Set the merge date on RFC 0018 stage 2

- rfcs/text/0025-container-metric-fields.md
> Set the merge date on RFC 0025 stage 0

- CHANGELOG.next.md
- code/go/ecs/cloud.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/cloud.yml
- Improve cloud region and AZ field descriptions (#1452)
> [1.x] Improve cloud region and AZ field descriptions (#1452)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- experimental/schemas/as.yml
- experimental/schemas/event.yml
- experimental/schemas/file.yml
- experimental/schemas/geo.yml
- experimental/schemas/pe.yml
- experimental/schemas/registry.yml
- experimental/schemas/threat.yml
- experimental/schemas/url.yml
- experimental/schemas/x509.yml
Apply changes from stage 1 of the threat enrichment RFC [0021](https://github.com/elastic/ecs/blob/master/rfcs/text/0021-threat-enrichment.md): #1400
> Stage 1 changes for RFC 0021 - threat enrichment

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- experimental/schemas/as.yml
- experimental/schemas/event.yml
- experimental/schemas/file.yml
- experimental/schemas/geo.yml
- experimental/schemas/pe.yml
- experimental/schemas/registry.yml
- experimental/schemas/threat.yml
- experimental/schemas/url.yml
- experimental/schemas/x509.yml
- Stage 1 changes for RFC 0021 - threat enrichment (#1457)
> [1.x] Stage 1 changes for RFC 0021 - threat enrichment (#1457)

- CHANGELOG.next.md
> Cut the changelog in the release branch

- CHANGELOG.next.md
> [master] update changelog for FF

- CHANGELOG.next.md
> [1.x] changelog forward port for FF

- .backportrc.json
> added 1.11

- .gitignore
- docs/converting.asciidoc
- docs/fields.asciidoc
- scripts/templates/fields.j2
> Backport [Docs] added reference to CSV (#1317) to 1.x

- .gitignore
- docs/converting.asciidoc
- docs/fields.asciidoc
- scripts/templates/fields.j2
> Backport [Docs] added reference to CSV (#1317) to 1.11

- CHANGELOG.next.md
- code/go/ecs/event.go
- code/go/ecs/threat.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/threat.json
- schemas/as.yml
- schemas/event.yml
- schemas/file.yml
- schemas/geo.yml
- schemas/hash.yml
- schemas/pe.yml
- schemas/registry.yml
- schemas/threat.yml
- schemas/url.yml
- schemas/x509.yml
- Threat intelligence RFCs stage 2 addenda (#1504)
> [1.x] Threat intelligence RFCs stage 2 addenda (#1504)

- CHANGELOG.next.md
- code/go/ecs/event.go
- code/go/ecs/threat.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/threat.json
- schemas/as.yml
- schemas/event.yml
- schemas/file.yml
- schemas/geo.yml
- schemas/hash.yml
- schemas/pe.yml
- schemas/registry.yml
- schemas/threat.yml
- schemas/url.yml
- schemas/x509.yml
- Threat intelligence RFCs stage 2 addenda (#1504)
> [1.11] Threat intelligence RFCs stage 2 addenda (#1504)

- CHANGELOG.next.md
- code/go/ecs/file.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/file.json
- experimental/generated/elasticsearch/component/threat.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/file.json
- generated/elasticsearch/component/threat.json
- schemas/file.yml
- Add file.fork_name to ECS (#1288)
> [1.x] Add file.fork_name to ECS (#1288)

- CHANGELOG.next.md
- code/go/ecs/service.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/service.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/service.json
- schemas/service.yml
- Adding service.address (#1537)
> [1.x] Adding service.address (#1537)

- CHANGELOG.next.md
- code/go/ecs/threat.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/threat.json
- schemas/threat.yml
- Stage 3 changes for RFC 0018 - extend `threat.*` field set (#1540)
> [1.x] Stage 3 changes for RFC 0018 - extend `threat.*` field set (#1540)

- CHANGELOG.next.md
- code/go/ecs/process.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/process.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/process.json
- schemas/process.yml
Adds process.end field.
Relates to #1523
> Add process.end field

- CHANGELOG.next.md
- code/go/ecs/process.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/process.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/process.json
- schemas/process.yml
- Add process.end field (#1544)
> [1.x] Add process.end field (#1544)

- docs/field-details.asciidoc
- docs/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
- New event categorization values to support threat intel use cases (#1510)
> [1.x] New event categorization values to support threat intel use cases (#1510)

- rfcs/text/0022-remove-process-ppid.md
Forgot to set the advancing date correctly when merging #1450.
> RFC 0022 - correct advancement date

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/user.yml
- Update user name & id docs for clarity (#1566)
> [1.x] Update user name & id docs for clarity (#1566)

- CHANGELOG.next.md
- Makefile
Cherry-picks @ypid-geberit commit from #1565
> fix: Prevent failure if no files need to be deleted `find | xargs rm`

- docs/field-details.asciidoc
- docs/usage/cloud.asciidoc
- docs/usage/service.asciidoc
- rfcs/text/0027-faas-fields.md
- rfcs/text/0027/cloud.yml
- rfcs/text/0027/service.yml
> [RFC] Faas fields - stage 2

- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/7/template.json
- experimental/generated/elasticsearch/component/threat.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/6/template.json
- generated/elasticsearch/7/template.json
- generated/elasticsearch/component/threat.json
- schemas/hash.yml
- Threat implementation reuse correction (#1604)
> [1.12] Threat implementation reuse correction (#1604)

- CHANGELOG.next.md
- docs/field-details.asciidoc
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/threat.yml
- Enrichments normalize fix (#1608)
> [1.12] Enrichments normalize fix (#1608)

- experimental/generated/beats/fields.ecs.yml
- generated/beats/fields.ecs.yml
Missed updating https://github.com/elastic/ecs/pull/1628 with https://github.com/elastic/ecs/pull/1633
> updated artifacts

- rfcs/text/0028-cgroups.md
Based on the merge date from #1627
> RFC 0028 - updating stage 1 advancement date

- .github/ISSUE_TEMPLATE/schema-changes-additions.md
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.next.md
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/master/rfcs/README.md)? Y 
- Is your pull request against master? Unless there is a good reason otherwise, we prefer pull requests against master and will backport as needed. No, it is against main (sic)
- Have you added an …
> Main master pr template

- CHANGELOG.next.md
- USAGE.md
- scripts/generators/ecs_helpers.py
- scripts/schema/loader.py
- scripts/tests/test_ecs_helpers.py
- scripts/tests/unit/test_schema_loader.py
- Align input options for --include and --subset arguments (#1519)
> [8.0] Align input options for --include and --subset arguments (#1519)

- CONTRIBUTING.md
I adjusted the `Branching` section of `CONTRIBUTING.md` to reflect current processes better. Also, I updated the `backport` tooling example with more recent branches.
> Refactor branching contributing docs

- code/go/ecs/process.go
- docs/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/process.yml
> Revert "Ppid deprecation notice"

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- generated/beats/fields.ecs.yml
- scripts/generators/beats.py
- scripts/generators/ecs_helpers.py
- scripts/tests/unit/test_beats_generator.py
- Beats: fix default_field setting for root fields (#1711)
> [8.1] Beats: fix default_field setting for root fields (#1711)

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- generated/beats/fields.ecs.yml
- scripts/generators/beats.py
- scripts/generators/ecs_helpers.py
- scripts/tests/unit/test_beats_generator.py
- Beats: fix default_field setting for root fields (#1711)
> [8.0] Beats: fix default_field setting for root fields (#1711)

- CHANGELOG.md
> Fix typo for 1.12.2 changelog

- rfcs/text/0000-risk-fields.md
- rfcs/text/0031-risk-fields.md
This is a proposal to add a reusable `risk` field set, to support two new features i.e. Host Risk Score and User Risk Score being added to the Security Solution. This new field set will help correlate information present in indices corresponding to these features, with other security-related indices.
> [RFC] Add a reusable `risk` field set

- docs/using-ecs/design.asciidoc
- docs/using-ecs/guidelines.asciidoc
- docs/using-ecs/guidelines/conventions.asciidoc
- docs/using-ecs/guidelines/implementation.asciidoc
- docs/using-ecs/guidelines/mapping-network-events.asciidoc
- docs/using-ecs/index.asciidoc
- Add `Principles` docs section (#1703)
> [8.1] Add `Principles` docs section (#1703)

- docs/using-ecs/design.asciidoc
- docs/using-ecs/guidelines.asciidoc
- docs/using-ecs/guidelines/conventions.asciidoc
- docs/using-ecs/guidelines/implementation.asciidoc
- docs/using-ecs/guidelines/mapping-network-events.asciidoc
- docs/using-ecs/index.asciidoc
- Add `Principles` docs section (#1703)
> [8.0] Add `Principles` docs section (#1703)

- CHANGELOG.next.md
- scripts/requirements-dev.txt
- scripts/requirements.txt
Bump both base and developer dependencies.
Reviewed release notes, verified successful unit tests, and performed manually testing with generator script.
> Bump dependencies

- CHANGELOG.md
- CHANGELOG.next.md
Somehow messed up merge conflict resolution the first time, so take 2
> [main] Cut 8.1.0 release changelog part 2

- docs/fields/usage/threat.asciidoc
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? ✅ 
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? 👍 
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? `N/A`
- If submitting code/script changes, have you verified all tests pass locally using `make test`? `N/A`
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? `N/A`
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. ✅  …
> Updated tlp key in usage example

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/host.json
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/host.json
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- rfcs/text/0030/process.yml
- schemas/group.yml
- schemas/host.yml
- schemas/process.yml
- schemas/source.yml
- schemas/user.yml
- Implement proposed changes from RFC 00300 - linux event model fields (#1842)
> [8.2] Implement proposed changes from RFC 00300 - linux event model fields (#1842)

- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/subsets/main.yml
Removed a few unnecessary mappings from process. cc @ebeahan @kqualters-elastic
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as …
> Follow up on the process mapping filter PR.

- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/subsets/main.yml
- Follow up on the process mapping filter PR. (#1850)
> [8.2] Follow up on the process mapping filter PR. (#1850)

- rfcs/text/0030-linux-event-model.md
The link to the proposed changes was to an outdated commit. Updated to use main now that it's merged.
> Linux event model RFC link update

- docs/release-notes/8.1.asciidoc
Forward-porting https://github.com/elastic/ecs/pull/1829
> [main] add release notes to 8.1 (#1829)

- CHANGELOG.md
- CHANGELOG.next.md
Forward ports #1932 to `8.3` branch
> [8.3] Changelog cleanup 8.2.1 (#1932)

- docs/release-notes/8.3.asciidoc
Backports the following commits to 8.3:
- Release notes 8.3 (#1967)
> [8.3] Release notes 8.3 (#1967)

- docs/release-notes/8.3.asciidoc
Backports the following commits to 8.4:
- Release notes 8.3 (#1967)
> [8.4] Release notes 8.3 (#1967)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/service.yml
forward-port of https://github.com/elastic/ecs/pull/1976
> [8.4] Deprecate service.node.role

- rfcs/0000-new-cloud-fields.md
- rfcs/text/0033-new-cloud-fields.md
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? yes
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? yes
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? yes …
> [RFC] Stage 0 - Add new cloud fields

- rfcs/text/0000-device-fields.md
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)?  - YES
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? - YES
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? - YES
- If submitting code/script changes, have you verified all tests pass locally using `make test`? - N/A
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? - N/A
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.  - YES …
> [RFC] Stage 0 - New Fieldset for Device

- scripts/generators/asciidoc_fields.py
> fix: fields asciidoc folder needs to be created

- rfcs/text/0034-device-fields.md
- rfcs/text/0034/device.yml
> RFC Stage 1: Device fields

- rfcs/text/0031-risk-fields.md
- rfcs/text/0031/example-alert.json
Continuing onto Stage 2 of the proposal to add a `risk` field set to the schema.
Stage 2 (Candidate) Criteria:
[Preview of markdown proposal](https://github.com/elastic/ecs/blob/0031/stage-2/rfcs/text/0031-risk-fields.md)
> [RFC] Risk Fields- Stage 2

- rfcs/text/0031-risk-fields.md
Continuing onto Stage 3 of the proposal to add a `risk` field set to the schema.
[Preview of markdown proposal](https://github.com/elastic/ecs/blob/0031/stage-3/rfcs/text/0031-risk-fields.md)
> [RFC] Risk Fields- Stage 3

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- docs/fields/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
Resolves https://github.com/elastic/ecs/issues/2028
> Add vulnerability to event.category

- CHANGELOG.next.md
> cut 8.6 SFF Changelog

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/threat.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/threat.json
- generated/elasticsearch/legacy/template.json
- schemas/threat.yml
> [8.6] Update to TLP (#2074)

- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/macho.yml
- schemas/pe.yml
No changelog entry since there has not been a release including these fields.
Please take a look.
> Fix typos in macho and pe schema files

- docs/release-notes/8.5.2.asciidoc
- docs/release-notes/index.asciidoc
> [8.6] Release notes for 8.5.2

- CHANGELOG.next.md
- docs/fields/usage/threat.asciidoc
- Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? Yes
- Have you followed the [contributor guidelines](https://github.com/elastic/ecs/blob/main/CONTRIBUTING.md)? Yes
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? NA
- If submitting code/script changes, have you verified all tests pass locally using `make test`? Yes
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? yes
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. NA …
> [Docs] Add url.domain to the Threat usage docs

- docs/release-notes/8.6.asciidoc
Update the release notes file for the given release (e.g., docs/release-notes/8.0.0.asciidoc) using this version's
changelog information from CHANGELOG.md. Do not merge. This PR should be merged on the day of the release.
> 8.6 update release notes

- CHANGELOG.md
- CHANGELOG.next.md
Forward port 8.6 changelog to main
> Forward port 8.6 changelog to main

- CHANGELOG.md
- CHANGELOG.next.md
8.6_finalize_changelog_in_release_branch (#2130)
> 8.6_finalize_changelog_in_release_branch (#2130)

- docs/release-notes/8.6.asciidoc
8.6_update_release_notes (#2131)
> 8.6_update_release_notes (#2131)

- docs/release-notes/8.7.asciidoc
- docs/release-notes/index.asciidoc
> [SFF 8.7.0] Add release notes

- docs/release-notes/8.7.asciidoc
- docs/release-notes/index.asciidoc
8.7 SFF add release notes placeholder
> Forward-port 8.7 SFF add release notes placeholder

- CHANGELOG.next.md
> Cut 8.7 SFF changelog

- CHANGELOG.next.md
> [Forward-port] Cut 8.7 SFF changelog

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/threat.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/threat.json
- generated/elasticsearch/legacy/template.json
- schemas/threat.yml
Forward porting https://github.com/elastic/ecs/pull/2156
> [main] Tlp patch #2156

- CHANGELOG.md
forward port of https://github.com/elastic/ecs/pull/2159
> [8.7] 8.6.1 changelog

- CHANGELOG.md
forward port of https://github.com/elastic/ecs/pull/2159
> [main] 8.6.1 changelog

- docs/release-notes/8.6.1.asciidoc
- docs/release-notes/index.asciidoc
forward port https://github.com/elastic/ecs/pull/2160
> [main] 8.6.1 release notes

- docs/release-notes/8.6.1.asciidoc
- docs/release-notes/index.asciidoc
forward port https://github.com/elastic/ecs/pull/2160
> [8.7] 8.6.1 release notes

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- docs/fields/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
> [backport][8.7] Adding library category to the schema #2154

- CHANGELOG.next.md
> [main][forward-port][8.7-hff] Prepare changelog for 8.7 HFF (#2167)

- CHANGELOG.md
- CHANGELOG.next.md
> [8.7.0 release] Move 8.7.0 entries from CHANGELOG.next.md to CHANGELOG.md

- docs/release-notes/8.7.asciidoc
> [8.7.0 release] Add 8.7.0 release notes

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- docs/fields/field-values.asciidoc
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- schemas/event.yml
Introduce the changes proposed in [RFC 0038](https://github.com/elastic/ecs/blob/main/rfcs/text/0038-event-kind-asset.md) as a `beta` category for `event.kind`.
Stage 2 proposal PR: https://github.com/elastic/ecs/pull/2178
> RFC 0038: Add `event.kind: asset` - stage 2 changes

- CHANGELOG.next.md
Forward port of https://github.com/elastic/ecs/pull/2198
> [main] Changelog for 8.8 ff (#2198)

- CHANGELOG.md
- CHANGELOG.next.md
forward port of https://github.com/elastic/ecs/pull/2208
> [main] Finalize 8.8 changelog (#2208)

- CHANGELOG.next.md
- docs/fields/field-details.asciidoc
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/csv/fields.csv
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- experimental/generated/elasticsearch/composable/component/process.json
- experimental/generated/elasticsearch/legacy/template.json
- generated/beats/fields.ecs.yml
- generated/csv/fields.csv
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- generated/elasticsearch/composable/component/process.json
- generated/elasticsearch/legacy/template.json
- schemas/process.yml
- schemas/subsets/main.yml
> Introduce process.vpid

- CHANGELOG.md
- docs/release-notes/8.8.asciidoc
Addresses https://github.com/elastic/ecs/issues/2214
> Clarifying changelog entry text

- rfcs/text/0042-risk-score-extensions.md
> [RFC] Risk field extensions [Stage 0]

- CHANGELOG.next.md
Related: https://github.com/elastic/security-team/issues/7248
> Prepare CHANGELOG.next.md as part of 8.10.0 FF

- .backportrc.json
Related: https://github.com/elastic/security-team/issues/7248
> Add v8.10 to backport tool

- docs/release-notes/8.10.asciidoc
- docs/release-notes/index.asciidoc
> [main] Release notes for ECS 8.10 (#2273)

- CHANGELOG.next.md
> 8.11 FF changelog updates

- scripts/requirements.txt
- scripts/schema/cleaner.py
This PR does two things:
1) Resolves build failures due to https://github.com/yaml/pyyaml/issues/601 by upgrading the dependency from pyyaml 6.0.0 to 6.0.1
2) Switching a few usages of f-string to string.format to address build formatting failures
<details>
<summary>Formatting build errors</summary>
```
if isinstance(example_value, (list, dict)):
field_name: str = field['field_details']['name']
-        msg: str = f"Example value for field `{field_name}` contains an object or array which must be quoted to avoid YAML interpretation."
+        msg: str = f"Example value for field `{
+            field_name}` contains an object or array which must be quoted to avoid YAML interpretation."
strict_warning_handler(msg, strict)
@@ -295,13 +296,15 @@ def check_example_value(field: Union[List, …
```
> Upgrading pyyaml dependency to fix build failures

- scripts/requirements.txt
- scripts/schema/cleaner.py
Backports the following commits to 8.11:
- Upgrading pyyaml dependency to fix build failures (#2300)
> [8.11] Upgrading pyyaml dependency to fix build failures (#2300)

- CHANGELOG.md
> Finalize 8.11 changelog

- docs/release-notes/8.11.asciidoc
- docs/release-notes/index.asciidoc
> Release notes for 8.11

- CONTRIBUTING.md
This PR describes the ECS release cadence during the Otel donation period.
> Clarification of ECS release process during Otel donation period

- rfcs/text/0044-add-apple-platform-specific-fields.md
Update some templated fields that were missed before merging the RFC
> Update templated fields in RFC0044

- CHANGELOG.md
- CHANGELOG.next.md
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. y …
> forward-port 8.16.0 changelog

- docs/release-notes/8.16.asciidoc
- docs/release-notes/index.asciidoc
Add 8.16 release notes to main
- For proposing substantial changes or additions to the schema, have you reviewed the [RFC process](https://github.com/elastic/ecs/blob/main/rfcs/README.md)? y
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? y
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. y
- Have you added an entry to …
> Add 8.16 release notes

- CHANGELOG.md
- CHANGELOG.next.md
- docs/release-notes/8.16.asciidoc
- docs/release-notes/index.asciidoc
Forward-port 8.16 documentation and changelog changes to 8.x branch
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? y
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as …
> Forward port 8.16 changes to 8.x

- CHANGELOG.next.md
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. n/a …
> Prepare CHANGELOG.next for 8.17 release

- .backportrc.json
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. y …
> Add 8.17 as backport target

- CHANGELOG.md
- CHANGELOG.next.md
> Prepare changelog for 8.17 release

- CHANGELOG.next.md
- Is your pull request against main? Unless there is a good reason otherwise, we prefer pull requests against main and will backport as needed. n/a …
> Prepare changelog for 9.0.0 feature freeze

- .backportrc.json
Update backportrc.json with 9.0 branch
- If submitting schema/fields updates, have you generated new artifacts by running `make` and committed those changes? y
- Is your pull request against main? yUnless there is a good reason otherwise, we prefer pull requests against main and will backport as needed.
- Have you added an …
> Update backportrc.json with 9.0

- CHANGELOG.next.md
- experimental/generated/beats/fields.ecs.yml
- experimental/generated/ecs/ecs_flat.yml
- experimental/generated/ecs/ecs_nested.yml
- generated/beats/fields.ecs.yml
- generated/ecs/ecs_flat.yml
- generated/ecs/ecs_nested.yml
- scripts/generators/ecs_helpers.py
Update to allow Unicode characters when outputting ECS generated yml files
Closes https://github.com/elastic/ecs/issues/2420
> Updating to allow unicode in yaml dump

- CHANGELOG.md
- CHANGELOG.next.md
Update changelog for the upcoming 9.1.0 release
None
N/A
YES
YES
---
Update changelog with changes included in 9.1.0
> Prepare changelog for 9.1

- .backportrc.json
> Add 9.2 to backportrc
